### ISSUE TITLE
Redirect from Firebase Login with Redirect

### ISSUE THREAD

**Issue by romucci** [ionic-team/capacitor#1054]
I have built an Vue.js app with Capacitor, and everything works awesome, but I am not certain on how to redirect a Firebase login to the app!

**Comment by dennington-bear** [comment]
Had a look at this myself it seems capacitor has an issue with redirections when i use the firebase method of `signInWithRedirect` the redirect never gets displayed but immediately the` {user: null} `returns . I can use this method when running as webapp but not mobile. I'm going to look into implementation of it manually but I would love to see if any dev can let us know if redirection is the issue or if its something thats not possible to be multi-client. Have a question about this very thing up on [Stack Overflow](https://stackoverflow.com/questions/54312601/angular-capacitor-app-crashes-on-firebase-login-due-to-redirect)

**Comment by nadhir-falta** [comment]
Is there any workaround for this? I'm getting the same thing with Angular 7

**Comment by jcesarmobile** [comment]
@dennington-bear maybe you can explain how you did it as on your question the problem was a bug that was resolved on beta 17.

Going to close as this is a question and not an issue. But another way is just to use url schemes to open the app, that will fire App's appUrlOpen event with the url used to open the app, that should contain the required information, that's how native apps do it.
