### ISSUE TITLE
Ionic 4 Access to service workers is denied in this document origin.

### ISSUE THREAD

**Issue by iliyaZelenko** [ionic-team/capacitor#1076]
I use this command to run the liveserver on my android virtual device.

```bash
ionic capacitor run android --livereload --livereload-url=localhost
```

I get these errors:

![image](https://user-images.githubusercontent.com/13103045/50421501-d5413a00-0848-11e9-9a9c-2062e56c676f.png)

The same error on my device screen.

Perhaps I should use another console command for this purpose?

**ionic info**

```
Ionic:

   ionic (Ionic CLI)             : 4.6.0 (C:\Users\User\AppData\Local\Yarn\Data\global\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0-beta.13
   @capacitor/core           : 1.0.0-beta.13

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.11.0 (D:\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

```

**Comment by jcesarmobile** [comment]
Are you using your own server or rely on the one `--livereload` starts?

I don't think you can use both `--livereload --livereload-url=localhost` at the same time, if I do that the local server is not started.
Also `localhost` is not a valid url, it should have the protocol (http or https) and usually a port too to match your running server.
And Android emulator won't understand "localhost" as Android emulators are virtual machines, so localhost is the emulator and not your computer running the server.

If I use `ionic capacitor run android --livereload` the server is tarted at `http://192.168.1.131:8100` (that's my local IP) and it works fine on Android emulator and real devices connected to the same network.

In your screenshot I can see it's loading `about:blank` page, not your server url, that's why you see that error. Just don't use `--livereload-url=localhost` as that's for using some other server you have already running.

**Comment by GuilhermeBCC** [comment]
This command not documented: ionic capacitor run android --livereload
Works with Monorepo as well, but to be perfect it is necessary to move node_modules and package.json from the project root folder (app/one/node_modules) to the workspace root (/node_modules)
