### ISSUE TITLE
How to move the ios build folder?

### ISSUE THREAD

**Issue by scriptPilot** [ionic-team/capacitor#1084]
To put in the end all builds (pwa / ios / android) in a specific folder, I want to move the ios build folder after build. But then, I have an error that the "Capacitor" cannot be imported in the Swift file. I tried to change the URL to the @capacitor/ios module accordingly, run pod install again but the error was still there.

So - my question:

How to move the ios build files / Xcode project files the proper way?

**Comment by jcesarmobile** [comment]
I would advise against doing this, if you move the ios folder the copy/update/sync commands won't work.
There is no proper way of doing this as is not supported, but updating the path and running pod install works, try running `pod install` with Xcode closed, and then open the project by double clicking the `App.xcworkspace` and not the `App.xcodeproj`. I've tried that and it works.

You can also change the Podfile to use the published version instead of the local version

```
  pod 'Capacitor', "1.0.0-beta.13"
  pod 'CapacitorCordova', "1.0.0-beta.13"
```

**Comment by scriptPilot** [comment]
@jcesarmobile - Thanks for your proposition :-)

**Comment by bernardoadc** [comment]
This should be easy to implement, though. Similar to `"webDir": "www"` config, it could have a "deployDir" setting.
