### ISSUE TITLE
Cordova Plugin: Casts to CordovaActivity will fail

### ISSUE THREAD

**Issue by redwolf2** [ionic-team/capacitor#1091]
`((CordovaActivity)this.cordova.getActivity())` will fail with an exception:

```
D/Cordova Intents Shim: Action: registerBroadcastReceiver
E/PluginManager: Uncaught exception from plugin
    java.lang.ClassCastException: de.test.example.MainActivity cannot be cast to ```
org.apache.cordova.CordovaActivity
        at com.darryncampbell.cordova.plugin.intent.IntentShim.execute(IntentShim.java:118)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:73)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

`this.cordova.getActivity()` works. The problem is due to MainActivity not extending [CordovaActivity](https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CordovaActivity.java). This may be intended and a nofix issue.

Might be implemented by extending CordovaActivity and wrapping an [AppCompatDelegate  ](https://developer.android.com/reference/android/support/v7/app/AppCompatDelegate) instead of [AppCompatActivity ](https://developer.android.com/reference/android/support/v7/app/AppCompatActivity) as a base class.

See this issue:
https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/issues/64

See changes neccessary for the plugin:
https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/pull/65/files

That line is not uncommon:
https://github.com/search?q=%28%28CordovaActivity%29this.cordova.getActivity%28%29%29&type=Code

**Comment by jcesarmobile** [comment]
Yeah, Capacitor apps extend `BridgeActivity` and not `CordovaActivity`, so if other plugins cast to it, it will fail as mentioned. The fix on Capacitor is not as simple as extending CordovaActivity as it will then use Cordova WebView instead of Capacitor's one.

The fix on the plugins seems very simple, so I'll close this issue and tag it as "known incompatible cordova plugin" label so it gets some visibility in case other users face this problem in a different plugin and hopefully they can fix it as you did on `darryncampbell-cordova-plugin-intent`.

The github search is not very accurate, so there are a lot of false positives on the results, hopefully not so much real plugins use this cast.

**Comment by redwolf2** [comment]
Just for info: My changes were integrated into https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent
