### ISSUE TITLE
Capacitor startActivityFoResult  does not pass data to Ionic

### ISSUE THREAD

**Issue by alireza23** [ionic-team/capacitor#1100]
One of best Capacitor features is Custom native code! but When I use startActivityFoResult (to start activity from same app) I can not get resault back to Ionic. I think it is a must have feature. I think data instead of plugin goes to MainActivity. can anybody help please?!

**Comment by jcesarmobile** [comment]
Capacitor by default can only get the result of a Capacitor or Cordova plugin.

If you want to get the result from custom code instead of from a plugin you'll have to overwrite the `onActivityResult` by adding the method to your MainActivity.java class and use the bridge eval function to execute javascript, something like this:

 ```
@Override
  protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (requestCode == yourCustomRequestCode){
      this.bridge.eval("doSomething();", null);
    } else {
      // Important to call super method so Cordova/Capacitor plugins keep working.
      super.onActivityResult(requestCode, resultCode, data);
    }
  }
```

**Comment by gbkwiatt** [comment]
It's an old question, but it did give me a hint. I can't figure out, what to do with that `bridge.eval`, but ideally, is there a way, to go back to plugin with a data returned ? Ideal solution would be if I can attach plugin activity to "registerForResult" so it returns to plugin rather than MainActivity
