### ISSUE TITLE
Android Studio complaining about obselete API:s

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#1163]
1. API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.

2. API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.

Using Beta 17.

**Comment by 13546777510** [comment]
I don't seem to see if capacitor is using this outdated API. Android Studio will throw this warning every time it is compiled after opening this project, which makes me very anxious. Because I am afraid that my project will fail to compile in Android Studio in the near future. If anyone knows any answers about these, please let me know here, thank you.

**Comment by jcesarmobile** [comment]
Those are from the plugin we use for release, so it won’t affect your project.
A solution (for us) might be to change the release plugin to the proposed on 
https://github.com/ionic-team/capacitor/pull/75

If you don’t want to seem them do what I said on 
https://github.com/ionic-team/capacitor/issues/863

**Comment by raphrmx** [comment]
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
