### ISSUE TITLE
List of author-verified Cordova plugins

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#1209]
How about adding a list of verified author plugins to a `verified-cordova-plugins.md` file in this repo, or to the docs?

For example, [Pushwoosh](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin) recently [added support for Capacitor](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/290). I'm sure you're also already aware of a few other cordova plugins that has been verified and works.

**Comment by jcesarmobile** [comment]
Most Cordova plugins work, so that list would be very big. And if they don't work we'll try our best to make them compatible, so I'm not in favour of not having that list.

If a Plugin doesn't work just report it and we'll try our best to make it compatible.

What we have is a Capacitor plugin list https://capacitor.ionicframework.com/docs/community/plugins/

**Comment by sandstrom** [comment]
@jcesarmobile Got it, makes sense! 👍
