### ISSUE TITLE
Filesystem.stat, please include original file-name or absolute path

### ISSUE THREAD

**Issue by vh13294** [ionic-team/capacitor#1235]
"Filesystem.stat" method return StatResult base on the path-uri

```typescript
interface StatResult {
  ctime : number
  mtime : number
  size : number
  type : string
  uri : string
}
```

Example:

path-uri = "file:///data/user/0/1655.12321564.jpg"

I want to get this: "/mnt/sdcard/myPicture.jpg"

**Comment by jcesarmobile** [comment]
why do you need that?

**Comment by vh13294** [comment]
In the capacitor-camera plugin, I can only return URI, but I also want to display the file name . Which photo has been selected.

**Comment by HarelM** [comment]
@vh13294 did you find a way to do it?
@jcesarmobile I want to be able to share a file with my app, this file sharing in android uses the file url, I would like to get the file name in order to use it for display.
I couldn't find anything in capacitor file API that allows that.
Am I missing anything?
I don't need the file path on the device, just the file name.
Much like it was in Cordova's `FileEntry` `name` property.
P.S. I'm trying to migrate my app from Cordova to Capacitor.
