### ISSUE TITLE
Files over HTTP do not support 206 Partial Content

### ISSUE THREAD

**Issue by diachedelic** [ionic-team/capacitor#1343]
HTML5 `<audio>` and `<video>` elements make use of [Range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) to estimate media duration, and facilitate seeking.  It appears that Capacitor's file server, at least on Android, does not support the `Range` header on requests:

```
GET http://localhost/_capacitor_file_/storage/emulated/0/Documents/1553226944608.webm
Range: bytes=0-

HTTP/1.1 200 OK
Content-Length: 124870
Content-Type: video/webm
Cache-Control: no-cache
Client-Via: shouldInterceptRequest
```

Along with serving correct `Content-Type` headers, I feel this feature is necessary for streaming media from the filesystem.

**Comment by diachedelic** [comment]
I see that [there is support for 206 responses](https://github.com/ionic-team/capacitor/blob/a36306540ec0f6bc0c25d5913e04ba661f04fe90/android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java#L200) in some capacity, am I just doing something wrong?

**Comment by jcesarmobile** [comment]
Looking at the code, the Range is only checked for the app assets (public folder), not to downloaded files, will fix it.

**Comment by llorenspujol** [comment]
Range request are not working correctly in my case, actually I may do something worng, but it only fails using the capacitor server... I opened this [issue ](https://github.com/ionic-team/capacitor/issues/2978) explaining the use case.

Is quite annoying since I can't put sound in my app... well... I can maybe play the first 3 seconds of the audio 🤣 , just kidding, but any help would be really appreciated :) !

**Comment by Losses** [comment]
THIS IS BECAUSE IT IS TRYING TO SEE IF THE FILE HAVE AN EXTENSION NAME OF "MEDIA":
https://github.com/ionic-team/capacitor/blob/0b5c2b740e9613512a100051b8822fd1361f4aeb/ios/Capacitor/Capacitor/WebViewAssetHandler.swift#L39-L41

AND WEBM IS NOT A CANDIDATE:
https://github.com/ionic-team/capacitor/blob/0b5c2b740e9613512a100051b8822fd1361f4aeb/ios/Capacitor/Capacitor/WebViewAssetHandler.swift#L103-L105

ONLY "MEDIA" WILL RESPONSE TO REQUEST WITH THE RANGE HEADER!

THE PEOPLE, WHO WROTE THESE CODE, YOU SHOULD GO BACK TO YOUR UNIVERSITY, RETAKE YOUR COMPUTER NETWORKING COURSE AND SAY SORRY TO YOUR TEACHER!
