### ISSUE TITLE
Video html tag is not playing/working for android

### ISSUE THREAD

**Issue by zhongjixiuxing** [ionic-team/capacitor#1402]
Description of the problem:

Affected platform
- [*] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [*] macOS
- [ ] linux

Other information:

Capacitor version:
latest

Steps to reproduce:

1. npx cap open android
2. use Anroid Studio IDE to build debug emulator app, and run it
3. video is not playing!!!

Link to sample project:

`https://github.com/zhongjixiuxing/capacitor-demo`

**Comment by solojuve1897** [comment]
When I run the app on my phone via Android Studio I get two videos showing. When I then press play on them they both play. What's the problem exactly?

**Comment by jcesarmobile** [comment]
I've been able to reproduce on an old emulator, but not on any real device (tested on 5 different devices from Android 5 to 9).
On the emulator I can see codec and decoder error messages, so the problem is probably related to that emulator not supporting those codecs, try with a newer one (I tested Nexus 5X emulator with API 28 and worked fine) or use real devices for testing.
