### ISSUE TITLE
cordova-plugin-braintree not working

### ISSUE THREAD

**Issue by rgolea** [ionic-team/capacitor#1415]
Hi there!

I would love to have an option to pay inside capacitor. I found in the Ionic docs a plugin called `cordova-plugin-braintree` that uses a `@ionic-native/braintree` interface.

For some reason, when building the project on iOS, it doesn't seem to find some `.h` files, even when I link the entire framework.

Any ideas? Thank you.

**Comment by jcesarmobile** [comment]
Looks like the plugin's .frameworks files are not compatible with CocoaPods for some reason (maybe because they are built with Carthage).
The plugin should be updated to get the libraries from CocoaPods instead of providing the .framework files, or should build them in a different way.

I don't think that will happen as current npm plugin is not maintained anymore, the github page points to a fork, which doesn't seem to be maintained neither and doesn't even work on cordova (it's a different problem, but still, doesn't work).
I've added it to the incompatible plugin list that is skipped on update so at least it doesn't cause build issues https://github.com/ionic-team/capacitor/pull/1424

**Comment by rgolea** [comment]
Great! @jcesarmobile Thanks a lot! Do we have on the capacitor page a page where we have a list of incompatible cordova plugins? Or just a reference to an issue?

**Comment by jcesarmobile** [comment]
here are the ones that cause build issues
https://github.com/ionic-team/capacitor/blob/master/cli/src/cordova.ts#L298

Some other plugins that don't work but might not cause build issues are tagged with the known incompatible cordova plugin, you can check all by clicking this issue label or here https://github.com/ionic-team/capacitor/issues?q=label%3A%22known+incompatible+cordova+plugin%22+is%3Aclosed

**Comment by rgolea** [comment]
Great! Thanks!
