### ISSUE TITLE
Android platform pause and resume events do not fire.

### ISSUE THREAD

**Issue by madmacc** [ionic-team/capacitor#1422]
Description of the problem:
The platform pause and resume events do not fire.
If I build the project using Cordova it works as expected.

```
constructor(private platform: Platform) {
    platform.ready().then(() => {
      this.onPauseSubscription = this.platform.pause.subscribe(() => {
          // Does not get here
        });

      this.onResumeSubscription = this.platform.resume.subscribe(() => {
       // Does not get here
      });
    });
}
```

Affected platform
- [*] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [*] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
1.0.0-beta.19

node version:
v10.7.0

npm version:
6.1.0

CocoaPods version:
N/A

Steps to reproduce:
Run app on device.
Put app into background by minimizing app or locking device
Console.logs in the pause or resume events do not fire

**Comment by solojuve1897** [comment]
https://capacitor.ionicframework.com/docs/apis/app/#type-16

Check out appStateChange

**Comment by madmacc** [comment]
Thanks @solojuve1897 I'll give it a go.  
Unfortunately I don't think it is going to work as for my project I am targeting a device that is locked to webview v44 and the capacitor/core plugins cause it to have a proxy error.  I'm hoping to get a firmware update to fix the webview version but it hasn't eventuated yet.

Do you know if this the new way to access these events or will accessing via Platform be added in the future?

**Comment by solojuve1897** [comment]
With Capacitor you should use the App API to handle these kinds of events.

From the docs:
> "For example, this API emits events when the app enters and leaves the foreground, handles deeplinks, opens other apps, and manages persisted plugin state."
https://capacitor.ionicframework.com/docs/apis/app

I suspect you are using a Cordova-plugin to listen to the events since I don't know where "Platform" is coming from in your code. Is it perhaps from Ionic Native? Ionic Native is still tightly coupled with Cordova. When Capacitor is released I guess that will change. We're still in Beta.

From the docs:
> "Ionic Native is a curated set of Cordova plugins that make it easy to add native functionality to any Ionic app."
https://ionicframework.com/docs/native/

**Comment by solojuve1897** [comment]
FYI:

"Ionic Native is supported in Capacitor. Currently, Ionic Native contains only Cordova plugins, so whenever you find an Ionic Native wrapper you'd like to use, install it and then install the corresponding Cordova plugin by running"

https://capacitor.ionicframework.com/docs/getting-started/with-ionic/

**Comment by jcesarmobile** [comment]
Platform is from `@ionic/angular`, it listen for Cordova pause and resume events, which were not implemented on Capacitor.

I've added them now for better compatibility

**Comment by toxaq** [comment]
This was only changed on Android? Searching for triggerDocumentEvent only appears in .java files.

**Comment by jcesarmobile** [comment]
Please, don’t comment on old issues.
https://github.com/ionic-team/capacitor/blob/b893a57aaaf3a16e13db9c33037a12f1a5ac92e0/ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.m#L67

**Comment by toxaq** [comment]
> Please, don’t comment on old issues.

It's not an old issue. The events don't fire. Close the issue for comments if you're unwilling to take submissions on them.

**Comment by jcesarmobile** [comment]
This is an Android issue and was fixed for Android, I've pointed you to the code where it's done on iOS.
If it's not working now it could have been broken for another reason, so it's not the same issue anymore, if you are facing it, instead of commenting in a 2 year old issue, report a new issue providing more information.
