### ISSUE TITLE
Question about Capacitor's plugins future

### ISSUE THREAD

**Issue by Genarito** [ionic-team/capacitor#1430]
Hi, I heard about Capacitor a few months ago. I was able to build a few examples using several Capacitor's plugins like Geolocation and Storage.

I was really fascinated about the idea of all the plugins being developed and maintained by such an excellent company as Ionic, because using Ionic with Cordova for 2 years I've faced a lot of headaches like:

- Plugins unmaintained since 2 years ago or more. ([case 1](https://github.com/apla/me.apla.cordova.app-preferences), [case 2](https://github.com/Rohfosho/CordovaCallNumberPlugin), ...)
- Plugins incompatibles with other plugins ([only one of a lot of cases](https://github.com/apache/cordova-android/issues/602))
- Plugins with pull requests with fixed critical bugs not merged for months ([one case](https://github.com/katzer/cordova-plugin-background-mode/issues/264)). And because of this I've some projects with at least three plugins fetched from forked repos.

Althouth It's cool to have such tools and solution, when you have to develop a big app with tons of plugins, all the items listed above become a serious problem as developers depends on the good predisposition of all the people behind those cool plugins.

That's why I think Capacitor will be THE solution to this problematic.

But yesterday I realized about [the community plugins section](https://capacitor.ionicframework.com/docs/community/plugins/) and wondered if you could clarify what are the intentios of the Ionic company about official plugins. Do you have in mind to develop and maintain all the Ionic native plugins (like NFC, QR Scanner, SQLite, etc) over the time? Or only a few and led the rest to the community? Would you accept PR for official plugins instead of only mention them in the community plugins section?

Thanks in advance and sorry about my English

**Comment by stewwan** [comment]
Im not from the core team but I think the answer would be `only a few`.

**Comment by mlynch** [comment]
Hey there,

What you're running up against is, unfortunately, the nature of supporting such a large surface area of functionality through community-supported plugins. This is not a Cordova specific problem nor is it necessarily solvable without a huge engineering team and a lot of money.

That means we likely can't maintain or support for free some of the more complicated ones out there, and some likely just don't fit in the core distribution. However, for some really necessary plugins like Push we are able to.

We also *are* able to support some of the more elaborate plugins for paying customers which makes it possible to hire for and actually maintain long term. A good example of this is our biometric authentication and security solution we call [Identity Vault](https://ionicframework.com/enterprise/identity-vault) (which works with Capacitor). We don't offer this one for free because it's pretty complicated and it is primarily useful for enterprises.

As for accepting new plugins, we're certainly open to it. In order to fit in the main runtime it would need to be something most apps need that can be supported with a relatively small amount of code so it can be maintained and also doesn't cause problems if someone doesn't use it (since it'll still be included).

Beyond that, we've invested a lot of effort in making building *and maintaining* plugins much easier in Capacitor than Cordova. We hope that means more people will make plugins and the ecosystem will see better maintenance because of that.

**Comment by Genarito** [comment]
Thank so much for the clarification!
