### ISSUE TITLE
currently there is no way to disable logs

### ISSUE THREAD

**Issue by stewwan** [ionic-team/capacitor#1431]
I think it's a must-have feature, we would be able to better isolate and debug issues on native part.

https://github.com/ionic-team/capacitor/blob/8158d910905790dd98bfffe3b927e445ecfb8c6e/ios/Capacitor/Capacitor/CAPBridgeDelegate.swift#L38

**Comment by mlynch** [comment]
Marking this as high priority because it also has performance implications and we don't need to print out this stuff out by default but could be useful for debugging.

**Comment by biesbjerg** [comment]
This looks like it was only solved for iOS? Or am I mistaken?

**Comment by Boosten** [comment]
@biesbjerg you might be right :-) I don't see any config option to hide logs in the Android code from capacitor.

**Comment by fifafu** [comment]
It would be really good if there was a flag for Android also. This is often an issue in enterprise builds because the security teams don't want the risk for any sensitive data being logged. (Which can happen easily, for example if you have a password store native plugin).

For now the only way seems to be to manually comment all the log statements.
