### ISSUE TITLE
Electron v5 not supported

### ISSUE THREAD

**Issue by gnesher** [ionic-team/capacitor#1491]
Description of the problem:

Affected platform
- [ ] Android
- [ ] iOS
- [X] electron
- [ ] web

OS of the development machine
- [X] Windows
- [ ] macOS
- [ ] linux

Other information:
Electron 5 was released on April, when trying to run a build with v5 installed app stalls at splash screen.

Capacitor version:
Tried beta.19 and beta.24

node version:
v10.15.3

npm version:
6.4.1

CocoaPods version:
---

Steps to reproduce:
Simply try to run an Electron app - I've used https://github.com/gnesher/phaser-capacitor as a starting point (uses beta.19 but upgrade to beta.24 doesn't help) but can also reproduce on an empty Capacitor project

Link to sample project:

**Comment by bcallaghan-fri** [comment]
I created a brand new Ionic application, added Capacitor, and added Electron through Capacitor's CLI. I then updated Electron to version 5. My app continued to function, but the default "Loading..." text disappeared from the splash screen. Later, when I tried to add @ionic/storage to my app, the electron app stalled at the splash screen. Running the app as a PWA worked just fine. Ultimately, I downgraded Electron back to 4.2.1. My app suddenly started working again, including the splash screen text and @ionic/storage. It would be great if Capacitor could be updated to use the latest version of Electron since it brings along Node 12, which will soon be the LTS version.

**Comment by mlynch** [comment]
Thanks, will likely make it soon after 1.0

**Comment by jcesarmobile** [comment]
It works in some apps and fails in others, not sure why, but the problem is in the `injectCapacitor` function.

Next release (1.1.0) will deprecate that method and will be removed in 2.0.0.

People will need to make this changes in their index.js to not use `injectCapacitor`, not a mandatory change for now, only if having issues when using electron 5.
https://github.com/ionic-team/capacitor/pull/1672
