### ISSUE TITLE
Refactor Electron Splash Screen

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#1529]
Needs some love, and has a ton of hard coded paths and project structure expectations that aren't clearly defined or documented.

**Comment by jcesarmobile** [comment]
from https://github.com/ionic-team/capacitor/issues/2011

I'm running a electron app pointed to a local dev server `http://127.0.0.1:8080` with webpack-dev-server. Unfortunately if I have the splash screen enabled in electron I get redirected back to electrons static files at the `file://` protocol. This breaks the autoreloading and HMR of webpack.

After inspecting the SplashScreen code I don't find any options for changing what URL the SplashScreen opens after 4500ms. But now I've disabled the SplashScreen instead.

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Other information:

I assume this section of `@capacitor/electron/index.js` is causing the redirect.

```js
    this.splashWindow.loadURL(`data:text/html;charset=UTF-8,${splashHtml}`, {baseURLForDataURL: `file://${rootPath}/splash_assets/`});

    this.splashWindow.webContents.on('dom-ready', async () => {
      this.splashWindow.show();
      setTimeout(async () => {
        if (inject) {
          this.mainWindowRef.loadURL(await injectCapacitor(`file://${rootPath}/app/index.html`), {baseURLForDataURL: `file://${rootPath}/app/`});
        } else {
          this.mainWindowRef.loadURL(`file://${rootPath}/app/index.html`);
        }
      }, 4500);
    });
```

Capacitor version: 1.2.1

Steps to reproduce:
Install the normal boilerplate from the cli and point the mainWindow.loadUrl in electron to a http protocol url instead of `file://`

**Comment by jcesarmobile** [comment]
from https://github.com/ionic-team/capacitor/issues/1949

Description of the problem:
The Splash Screen plugin is hard-coded to read the config file from `./capacitor.config.json`. This works fine during local development, as the current working directory is the directory containing `index.js`. When using `electron-builder` to package my application, the current working directory is the directory containing the packaged `.exe` file when the file `capacitor.config.json` is actually at the top-level of the `app.asar` archive. This results in a silent error where the settings from the config file are not actually read.

As a recommended fix, read the file from `${app.getPath()}/capacitor.config.json`. This path is correct for both Windows and macOS and works for both local debugging and deployment.

Affected platform
- [ ] Android
- [ ] iOS
- [x] electron
- [ ] web

OS of the development machine
- [x] Windows
- [x] macOS
- [ ] linux

Other information:
Windows file paths
```
getAppPath(): C:\Users\...\dist\win-unpacked\resources\app.asar
__dirname: C:\Users\...\dist\win-unpacked\resources\app.asar
execPath: C:\Users\...\win-unpacked\My App.exe
cwd: C:\Users\...\dist\win-unpacked
config file: C:\Users\...\dist\win-unpacked\resources\app.asar\capacitor.config.json
Error: ENOENT: no such file or directory, open './capacitor.config.json'
```
macOS file paths
```
getAppPath(): /Users/.../dist/mac/My App.app/Contents/Resources/app.asar
__dirname: /Users/.../dist/mac/My App.app/Contents/Resources/app.asar
execPath: /Users/.../mac/My App.app/Contents/MacOS/My App
cwd: /
config file: /Users/.../mac/My App.app/Contents/Resources/app.asar/capacitor.config.json
Error: ENOENT: no such file or directory, open './capacitor.config.json'
```
Capacitor version: 1.2.0

node version: 12.4.0

npm version: 6.9.0

Steps to reproduce:
1. Create a new Electron/Capacitor app. The default template already uses the Splash Screen plugin.
2. Change the Splash Screen configuration in the `capacitor.config.json` file. This is to create a clear difference between the defaults and the desired configuration. For example, 
```json
{
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 10000
    }
  }
}
```
3. Package the project using `electron-builder` and the default configuration. Only packaging the application is necessary. An installer is not needed.
4. Observe that the default behavior for the Splash Screen is used, not the overridden behavior from the config file.

**Comment by IT-MikeS** [comment]
Might be able to close this and move future issues around electron to the community org.
