### ISSUE TITLE
[Android] Keyboard event-listeners aren't removed

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#1534]
Description of the problem:
In my app the following works:

```
created () {
    let _this = this
    window.addEventListener('keyboardWillShow', _this.keyboardWillShow)
  },
  beforeDestroy () {
    let _this = this
    window.removeEventListener('keyboardWillShow', _this.keyboardWillShow)
  }
```

And the following doesn't:

```
  created () {
    let _this = this
    Keyboard.addListener('keyboardWillShow', _this.keyboardWillShow)
  },
  beforeDestroy () {
    let _this = this
    Keyboard.removeListener('keyboardWillShow', _this.keyboardWillShow)
  }

```

The removal of the event-listener doesn't occur. What am I missing?

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [x] Windows
- [ ] macOS
- [ ] linux

Other information:

Capacitor version:
Beta 25
node version:

npm version:

CocoaPods version:

Steps to reproduce:

Link to sample project:

**Comment by jcesarmobile** [comment]
This is more a documentation/types problem than a bug.
`removeListener` doesn't work and never has worked, because that's not the way of removing the listener, addListener returns a `PluginListenerHandle` which is a function that allows to remove the listener.
I've removed the removeListener from types and injected js so it can't be used https://github.com/ionic-team/capacitor/pull/1543

So usage is like this:
```
listener: PluginListenerHandle

created () {
    let _this = this
    _this.listener = Keyboard.addListener('keyboardWillShow', _this.keyboardWillShow)
  },
  beforeDestroy () {
    let _this = this
    _this.listener.remove()
  }
```
