### ISSUE TITLE
Set unlimited storage

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#158]
From @nampdn:

> Can I enable something in Chrome flag like --unlimited-storage to make the app able to use all the available local storage space instead of 10% per domain?
> Crosswalk with in Cordova can do this, and my app is using it.

**Comment by bartvanderwal** [comment]
@nampdn Hmm.. interesting question. Is this for PWA's or hybrid app? I searched, but the interweb doesn't provide a quick definitive yes or no (yet). But it doesn't seem like it. The ionic cli now allows setting the browser for ionic serve, but it doesn't seem to support passing parameters like --unlimited-storage. You can always browse to localhost yourself. But all this is only for testing purposes anyway, can't rely on this for your users, since they'll have standard Chrome.

There's an similar question for iOS's WKWebView still open: https://stackoverflow.com/questions/30381044/how-can-you-programmatically-increase-the-localstorage-size-limit-of-wkwebview-o



In any case it seems like you have to port something of your Crosswalk app, to store the bulk of data in the/a backend. Perhaps a good time to also switch to the new ApplicationCache (serviceWorker), it seems to have most available size. This article from 2014 gives an overview, https://www.html5rocks.com/en/tutorials/offline/quota-research



It also mentions a setting 'browser.cache.offline.capacity' for the maxSize in Chrome. That was version 40, but the setting is nowhere to be found in the current Chrome 64 (it aso seems mostly relevant for Chrome apps (e.g. extensions).

**Comment by mlynch** [comment]
Did some quick research, it seems that every storage API for the `WebView` in Android has been deprecated and is a no-op. Instead, they are using new HTML5 APIs to manage this, such as https://developers.google.com/web/updates/2016/06/persistent-storage

**Comment by nampdn** [comment]
Thank you for looking at this.
The main purpose of my app is storing content in a hybrid app, I use Google's shaka-player for my Ionic app to stream and store offline content [https://github.com/google/shaka-player/blob/master/lib/offline/db_engine.js](https://github.com/google/shaka-player/blob/master/lib/offline/db_engine.js). The only platform I target is Android which can be set `--unlimited-storage` via Crosswalk Webview Plugin.

**Comment by mlynch** [comment]
@nampdn have you tried any of the persistent storage APIs? Seems like the way Chrome is going, though you could always get around that with a native storage option

**Comment by sandstrom** [comment]
*Just chiming in on something `localStorage` related.*

In iOS webview running under Cordova storage will be cleared arbitrarily (for example of the device is running low on disk). It's essentially [treated as cache](https://cordova.apache.org/docs/en/latest/cordova/storage/storage.html#localstorage).

There are plugins such as [cordova-plugin-nativestorage](https://github.com/TheCocoaProject/cordova-plugin-nativestorage), but it would be even better if localStorage was stored in a durable location instead.
