### ISSUE TITLE
google-maps not incompatible at capacitor 1.0

### ISSUE THREAD

**Issue by JeongJun-Lee** [ionic-team/capacitor#1637]
At capacitor, there is no more config.xml. But when remove it, the IDE emits configuration build error like below:

Caused by: org.gradle.api.GradleException: Please add `<preference name="GOOGLE_MAPS_ANDROID_API_KEY" />` to the config.xml file.

**Comment by solojuve1897** [comment]
From the docs:

"Capacitor considers each platform project a source asset instead of a build time asset. That means you'll check your Xcode and Android Studio projects into source control, as well as use those IDEs when necessary for platform-specific configuration and running/testing.

This change in approach has a few implications. First, Capacitor does not use config.xml or a similar custom configuration for platform settings. Instead, configuration changes are made by editing the appropriate platform-specific configuration files directly, such as AndroidManifest.xml for Android and Info.plist for Xcode."

**Comment by jcesarmobile** [comment]
Looks like the plugin changed to using preferences instead of variables.

The plugin now read the preference from a root `config.xml`, so even if Capacitor doesn't use that file, you can still create it and add your API key like this:

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="your.app.id" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
 <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="yourkey" />
</widget>
```

There was another bug causing the plugin to crash, but I've fixed it here https://github.com/ionic-team/capacitor/pull/1643

Also it fails to build on iOS because it uses some Cordova classes that are not available in Capacitor, so I'm going to add it to the incompatible list, but just for iOS.
https://github.com/ionic-team/capacitor/pull/1645
