### ISSUE TITLE
No podspec found for Capacitor when running pod update or install.

### ISSUE THREAD

**Issue by warrenbell** [ionic-team/capacitor#1676]
I am trying to add an ios framework to a Capacitor plugin I am building. I am getting the following error when running "pod update" or "pod install" on the Podfile located at ios/App/Podfile.

No podspec found for 'Capacitor' in '../../node_modules/@capacitor/ios'

I have seen other posts and nothing has worked so far. I have updated to the latest cocoapod version, ran "pod repo update", recreated the whole ios folder with "ionic capacitor add ios" and have clean the build folder over and over again.

Ionic version 4.12.0
Capacitor version: 1.0.0
XCode version: 10.1
Cocoapods: 1.7.2

What am I missing ?

**Comment by jcesarmobile** [comment]
Did you create the plugin with `plugin:generate` command?
or are you creating it manually?

**Comment by warrenbell** [comment]
I created the plugin with:

npx @capacitor/cli plugin:generate

**Comment by jcesarmobile** [comment]
> I traced the path and you need to go up 2 directories to get access to node_modules.

so you changed to path and added that extra `../`?

If I create a new project, the Podfile is inside ios folder, and node_modules is on the root, so the path I provided is ok. 
Can you provide your folder structure?

**Comment by warrenbell** [comment]
I deleted the ios directory and the node_modules directory and started from scratch running:

npm install
ionic capacitor add ios
pod update
pod install

And that worked

I then added the line to install the ios library and that worked. It was not a path problem at all. The error message made it seem like it was.

Thanks for your input.

**Comment by jcesarmobile** [comment]
Oh, I thought the problems were with the actual plugin and not in the app project you are using to test.

BTW, if creating a plugin, you should put the dependencies in the plugin's .podspec, not in the project Podfile, that way they will be installed for users instead of making them modify their Podfile (see an example at the end https://guides.cocoapods.org/syntax/podspec.html)

**Comment by jcesarmobile** [comment]
Going to close as you solved your issue and it's not clear what was causing the problem.

**Comment by hardmouse** [comment]
In my case it's simply missing ios in node_module. Solve it by reinstall it:
`npm i @capacitor/ios`

**Comment by ibrahimAboelsuod** [comment]
I had the same problem -with a slightly different error message.

The pod file had the wrong type of slash for some spec files. it had `\` instead of `/` ! which gives the same error message just with the slaches the other way around.

This happened because I develop on 2 environments: win & mac and windows changed it at some point without me noticing.

Replacing them with the correct type fixed the problem.
