### ISSUE TITLE
Android run not live reloading

### ISSUE THREAD

**Issue by matheo** [ionic-team/capacitor#1745]
Description of the problem:

I have an `Ionic` app and now it's migrated to `Capacitor` and building successfully after some fixes to setup the FacebookConnect plugin settings manually.

Following the documentation, I've tried to `ionic capacitor run android --livereload` and I see that the emulator remains black, sometimes pressing the power button it shows the application, but doesn't live-reload the changes made to the ionic application.

Affected platform
- [x] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ ] macOS
- [x] linux

Other information:

@capacitor/cli 1.1.0
@capacitor/core 1.1.0
@capacitor/ios 1.1.0
@capacitor/android 1.1.0
node version: 10.16.0
npm version: 6.9.0

Steps to reproduce:

I've created a new Ionic + Capacitor project to see if the issue was about my project and nope, the same happens for a blank ionic project.

Link to sample project:

Clone, install and run `npm run android` of:  
https://github.com/matheo/capacitor  
attempt to change the `tab1.component.html` to see the live-reloading feature in action.

**Comment by jcesarmobile** [comment]
I can't reproduce on macOS.

Can you test on a real device? what you say about the power button looks strange, might be some Android emulator problem on linux.

Doesn't look related to Capacitor as it just loads the url you tell you to, so going to close. If you think the problem is in the live reload server then report it on https://github.com/ionic-team/ionic-cli/issues
