### ISSUE TITLE
[error] Missing appId in config. Please add it

### ISSUE THREAD

**Issue by innovateworld** [ionic-team/capacitor#176]
I have followed the steps one by one from [https://capacitor.ionicframework.com/docs/getting-started/with-ionic](url) and when adding any platform (like `npx cap add ios`) I receive the error:

>[error] Missing appId in config. Please add it

**Comment by mlynch** [comment]
k I see the issue, create isn't creating `capacitor.config.json` now, will fix

**Comment by mlynch** [comment]
Fixed in eaaad6dfc8387bf1e6c011f2c324e6a0d6eb0547

**Comment by rodigo55235523** [comment]
Good afternoon
Max Lynch mlynch I need a tip from you ,
and the first time I'm going to publish an app in the store
  I ran all the command to sign the apk
everything went right
  ,but when it's time to upload the app.release.aab file to the playStore
a message appeared

  the "appId": "io.ionic.starter", already exists in the playstore

this message comes from the capacitor.config.json file
{
"appId": "io.ionic.starter",
"appName": "my app",
"webDir": "www",
"bundledWebRuntime": false
}
what has to change here in the "appId": "io.ionic.starter",?
   can i put my email
because I don't have a website or blog

I appreciate if you can help me
