### ISSUE TITLE
Unregister Push Notifications

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#1777]
I want to toggle them on and off but I can only see a register function for push notifications.

Is it possible to unregister for push notifications?

**Comment by naveedahmed1** [comment]
Any update on this? Its a must I believe. Every app has an option to turnoff notifications.

**Comment by oliverandersencox** [comment]
@jcesarmobile are we missing something here. I dont see any docs on how to handle unregistering or blocking notifications using the capacitor code itself.

**Comment by naveedahmed1** [comment]
Yes you're right currently there's no option to unregister.

**Comment by danielprrazevedo** [comment]
I recommend the complementary plugin: [https://github.com/stewwan/capacitor-fcm](capacitor-fcm), it has a method to `deleteInstance()` method

**Comment by naveedahmed1** [comment]
@danielprrazevedo thanks for sharing, but I believe this is very basic functionality and should be implemented in official Push notificaiton plugin of capacitor.

**Comment by danielprrazevedo** [comment]
@naveedahmed1 This plug-in is not a replacement for PushNotification, it works in a complementary way. A good example is the "register ()" method that triggers the event that returns the token, but in ios, it returns the APN's token.

**Comment by mlynch** [comment]
Hey all, we aren't going to support this for a few reasons. One, Apple recommends against using the unregister calls for notifications: https://developer.apple.com/documentation/uikit/uiapplication/1623093-unregisterforremotenotifications

Two, the "correct" way to implement a feature like this is to have toggles in the app that control server-side flags. So, if a user wants to disable notifications or specific notifications, that would trigger an API call to your server which would change what notifications you send to them. That is the preferred way to implement a feature like this.

**Comment by mrodal** [comment]
Hey @mlynch @jcesarmobile , I think this is some basic functionality that should be supported and shouldnt be too hard to implement. The device on its own should be able to stop receiving notifications without depending on the server.

For example, its a common case where on logout the app should stop receiving notifications. Without this, and implementing the "correct" way, the app **must** be online in order to send to the server the *"stop sending me stuff"* order.. if the device is offline or the server is unavailable at the moment, the server will never get the order, and will keep sending notifications after the session is closed.
