### ISSUE TITLE
Cordova plugin not working: cordova-plugin-inapppurchase

### ISSUE THREAD

**Issue by biesbjerg** [ionic-team/capacitor#1808]
[cordova-plugin-inapppurchase](https://github.com/AlexDisler/cordova-plugin-inapppurchase) has a hardcoded (native layer) requirement of a file existing at `www/manifest.json`, but when using Capacitor the location is at `public/manifest.json`.

Native layer code:
```java
context.getAssets().open("www/manifest.json");
```

Could Capacitor add a symlinked dir (`www` -> `public`) for better compatibility or maybe a way to configure the [Android webdir](https://github.com/ionic-team/capacitor/blob/1c4a3a929af39d47cd20ceae046fcb025e09130a/cli/src/config.ts#L34) to `www`?

Edit: I guess in my case I can easily add the symlink myself and check it into version control, but maybe other cordova plugins relies on assets being located in `www` and it would be an easy way to make those plugins compatible out of the box.

**Comment by jcesarmobile** [comment]
closing as incompatible with workaround

**Comment by scamposd** [comment]
Friends please your help, I present this problem currently.

Unable to read manifest file:java.io.FileNotFoundException: www/manifest.json
Error: Billing cannot be initialized
restorePurchases() {"code":-2,"message":"Billing cannot be initialized","errorCode":-2}

Finally, how to solve the www folder, since capacitor does not find the path

**Comment by Gautammer** [comment]
@farzammalekzad You saved life, your solution works for capacitor with ionic v6
Thanks.. 🙏
