### ISSUE TITLE
SetInterval in background-task doesn't work

### ISSUE THREAD

**Issue by abhilashbr92** [ionic-team/capacitor#1867]
Description of the problem:
Hello, I am trying to send user location data to the server every 5 minutes when the app is inactive/background. But the location is not sent to the server after the interval. When I open the app, then all locations are sent to the server automatically. I think data is sent to the server if the app is in the foreground. I am using https://capacitor.ionicframework.com/docs/apis/background-task to identify whether the app is in foreground/background.
Is there any way in the capacitor to send the user locations at regular intervals to the server if the app is in the background?

Affected platform
Android( No iOS)

OS of the development machine
Windows

Below is my code:
`  
SubscribeAppStateChange() {
    App.addListener('appStateChange', (state) => {
      if (!state.isActive) {
             clearInterval(this.intervalId);
             this.intervalId = setInterval(() => { this.GetLocation(); }, 30000);
      }
    });
  }
`

`
  GetLocation() {
    this.geolocation.getCurrentPosition().then((resp) => {
      this.locationAPI.SaveLocation({ latitude: resp.coords.latitude, longitude: resp.coords.longitude }).subscribe((response: any) => {
        console.log(response);
      });
    }).catch((error) => {
      console.log('Error getting location', error);
    });
  }
`

Can somebody please tell me how to get the locations at regular intervals if the app is in background?

**Comment by jcesarmobile** [comment]
I've tried your code (except for the part that sends the data to a server) and seems to work fine, I get the location with the device in background.

Anyway, it might depend on the device as some Android versions or devices can prevent apps from running in the background, and BackgroundTask plugin doesn't really do anything on Android at the moment.

**Comment by nicobytes** [comment]
Hello! What is the better approach for background task for a timer, I'm making an app for sleep routines with sounds, when user wants start to sleep start a sequence.

I have a timer for each phases when the time is up should continues with the next phase with a new sound.

But in IOS my timer stops in cordova I use the background-mode-plugin and works but with Capacitor what is the better approach?

**Comment by ziftytodd** [comment]
I ran into this problem and found a solution. The problem is that when the app pauses, Capacitor tells the WebView (on Android) to stop the timers and intervals. So at five minutes after the app is paused, those timers and intervals stop firing. I modified the code of the plugin to call the "resumeTimers()" method of the webview, and then it kept running indefinitely on Android. I use the background geolocation plugin on iOS and it works fine keeping things running indefinitely while in the background (so long as you have GPS running before the app pauses and background geolocation capability turned on).
