### ISSUE TITLE
Camera - Android - Not respecting SaveGallery Flag when set to False

### ISSUE THREAD

**Issue by carlos2712** [ionic-team/capacitor#1879]
Description of the problem:
Using Capacitor camera plugin and adding  saveToGallery: false, the picture it's being saved anyway on the galery, only happening on Android. 
Affected platform
- [ x ] Android
- [ ] iOS
- [ ] electron
- [ ] web

OS of the development machine
- [ ] Windows
- [ x] macOS
- [ ] linux

Other information:
Here's my function : 
`
  async takePicture(metadata) {  
 const milliseconds = new Date().getTime();
    const timestamp = (milliseconds.toString()).substring(9, 13);
    const image = await Plugins.Camera.getPhoto({
      quality: 70,
      resultType: CameraResultType.Uri,
      saveToGallery: false,
      source: CameraSource.Camera
    });
  }
`

Capacitor version:
1.1.1
node version:
v10.16.0
npm version:
6.9.0
CocoaPods version:
1.7.5

Steps to reproduce:
1. Take a picture using Android. 
1. Go to pictures gallery the image will be there. 

Link to sample project:

**Comment by parthnayak7448** [comment]
Hello is there any solutions for this

**Comment by BlackToothGrin96** [comment]
Hi, is this issue still ongoing?

I am working on an enterprise App that requires us to take pictures and (preferably) NOT save the images to the device.

The saveToGallery: false flag has no effect on Android and my attempts to implement a system to delete the images after the fact via Capacitor's Filesystem API have also met with mixed results.

Thanks.

**Comment by jcesarmobile** [comment]
Some devices save an additional copy of the photo in a DCIM folder (or even in sub folders inside DCIM folder) and it's device/vendor specific. 
The image that appears in the gallery is the one in the DCIM folder, not the one returned to the user, that's why it doesn't disappear if you remove it, because it's a different copy. 
I don't think we can prevent that behaviour.

**Comment by eddyouedraogo** [comment]
Hi @BlackToothGrin96,

Is there any more details you can provide regarding your use of the Filesystem API to work around the issue? 
I am currently facing the same problem and trying to use this API to acces the DCIM folder and delete the file. 
I changed my resultType to CameraResultType.Uri in order to get a path and a file name. 
But the path is not the one leading to the DCIM/Camera repository it is a path in the cache of my app (something like file:///data/user/0/com.my.app/cache/JPEG_20200717_.........jpg). 

Thanks in advance for your answer.

**Comment by DjulLau** [comment]
Hi. I'm also interested in a solution to this. I can also confirm that it seems to be device specific.

**Comment by gunsha** [comment]
Hey guys, i've found out about this issue today as one client of my app was complaining of low storage space, which was weird as I was using base64 capture, thought that the temporary images were deleted after capture, but no, and if you don't use Uri result type you don't get the full path of the image, so in the meantime i'm just clearing the pictures folder content, hope that this helps someone:
```
async clearPicturesFolder(){
        if (this.platform.is('android')){
            const picturesFolder = await Filesystem.getUri({directory: FilesystemDirectory.External, path: 'Pictures'});
            Filesystem.readdir({path: picturesFolder.uri}).then( (dir) => {
                dir.files.forEach((file) => {
                    Filesystem.deleteFile({path: picturesFolder.uri + '/' + file });
                });
            });
        }
    }
```

**Comment by jcesarmobile** [comment]
Camera plugin has been moved to https://github.com/ionic-team/capacitor-plugins, and had some changes that might have fixed the issue, but if you still face the saveToGallery issue, please, report it in https://github.com/ionic-team/capacitor-plugins/issues

For the camera not doing cleanup of images I created https://github.com/ionic-team/capacitor-plugins/issues/431
