### ISSUE TITLE
Feature Request - Support for Action Buttons in Push Notifications Plugin

### ISSUE THREAD

**Issue by naveedahmed1** [ionic-team/capacitor#1938]
Description of the problem:

I was exploring Capacitor, it awesome, Great job 👍.

Here's a feature request to add support for Actions Buttons in Push Notifications plugin? I believe its very common for Push Notifications and would be helpful for developers.

May be some code could be ported from `phonegap-plugin-push` repository https://github.com/phonegap/phonegap-plugin-push/tree/master/src/android/com/adobe/phonegap/push

A similar API which is already familiar to the developers of Cordova/Ionic community would be great, the docs of their api for action buttons is available here

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons

Affected platform
- [x ] Android
- [x ] iOS
- [ x] web

OS of the development machine
- [x ] Windows

Capacitor version:
1.2.0

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

**Comment by rossholdway** [comment]
Hi @jcesarmobile Is this now supported via the `pushNotificationActionPerformed` event?

If not, I see there are a number of +1 👍 on the issue. Is this something that could be in the pipeline anytime soon? Thanks.

**Comment by naveedahmed1** [comment]
BTW for my Android app I am now using Trusted Web Activities, and so far its working great.

**Comment by jcesarmobile** [comment]
I'm removing the feature request label since this is actually possible on iOS at the moment.
With LocalNotifications plugin you can register actions with `LocalNotifications.registerActionTypes` method (check example app for sample usage).
Despite it's in `LocalNotifications` plugin and not in `PushNotifications`, you can still use those actions in a push message by passing a `"category" : "ID_OF_THE_REGISTERED_ACTION"`.

On Android is also possible for local notifications, not on push notifications as requested, but considering Capacitor doesn't display the push notifications to the user, I think it's out of the scope, the user can trigger local notifications based on the notification payload received and show any action with the mentioned method.

**Comment by savgiannis** [comment]
But how to trigger the local notifcations (via the push that came from the server) when the app is in background/killed, on android?

**Comment by fromage9747** [comment]
2021 using the latest versions.  You still cannot trigger the local notifications on the received event as it only triggers when the app is in the foreground.  Nothing is triggered when the app is in the background.
