### ISSUE TITLE
Custom plugin 'No web implementation' unless registerWebPlugin manually called in/after app constructor

### ISSUE THREAD

**Issue by Cloov** [ionic-team/capacitor#1985]
Description of the problem:

I'm trying to develop a custom plugin that makes full use of the `WebPlugin` variant as well as native variants. I've generated a capacitor project using the getting-started documentation, and the built-in plugin generation script (pages URLs that I used are below).

https://capacitor.ionicframework.com/docs/getting-started/
https://capacitor.ionicframework.com/docs/plugins/

I modify my starter project to install the plugin node-module, and I import it in `home.ts` and add code to invoke a method in the plugin. This method is fully defined in my plugin, in both the iOS code, and in the web plugin variant, with the method signatures being as compliant as I think they can be.

When running natively, the plugin runs, but when running on web, I'm told there's no web implementation.

If I make a call to `registerWebPlugin` in certain other locations - like in the app's constructor in `app.component.ts`, then the web plugin works.

I can see that `registerWebPlugin` now sits inside `web.ts` in plugins generated with the command line script, but it seems like it's not having any effect for me. Like I say, if I call `registerWebPlugin` from the app constructor, that works, and it works regardless of whether or not I've removed the identical call from the plugin's `web.ts` file.

Here are repositories for the app and plugin that manifest the issue.

App: *https://github.com/Cloov/capacitor-plugin-test.git*
Plugin: *https://github.com/Cloov/concatenate.git*

'Concatenate' is my sample plugin; it has one method, that combines two input strings.

Currently, the extra `registerWebPlugin` call is instated, but remove it from the constructor in `app.component.ts`, and the plugin should, once again, report at runtime that there's no web implementation.

---

Affected platform
- [] Android
- [] iOS
- [] electron
- [x] web

OS of the development machine
- [ ] Windows
- [x] macOS
- [ ] linux

Capacitor version: 1.2.1
node version:  v11.2.0
npm version: 6.4.1
CocoaPods version: 1.7.1

**Comment by typeoneerror** [comment]
Same issue here. No web implementation.

**Comment by biesbjerg** [comment]
Same issue. What happens if you do:

```ts
import { Concatenate } from 'concatenate'; // package name from package.json
```

**Comment by mludi** [comment]
I'll have a look. Thanks @biesbjerg !

**Comment by Timeswitch** [comment]
You can also just import your plugin inside your app.
It's just really uggly, since you have to do something like this:

```js
import { Plugins } from '@capacitor/core';
import { MyAwesomePlugin } from 'my-awesome-plugin';

function SomewhereInYourApp()
{
   const {MyAwesomePlugin} = Plugins;
   MyAwesomePlugin.doStuff();
 
}

```

If you don't import your Plugin, `registerWebPlugin` won't get called, so the registry doesn't know there is a web implementation.
The reason you native implementations work, is because they get picked up by capacitors auto-binding.

I'm not sure, if this is an oversight in the API or if somebody forgot to document how to do this properly. This get's even worse, if you try to figure out how to register electron plugins...

If you want to use TypeScript typings, your only choice right now is to import the plugin and cast the auto-bindings to you plugin interface. This registers the plugin by default.
Maybe that's why I haven't seen that many people having difficulties figuring this out.
