### ISSUE TITLE
bug: enabling UIApplicationSupportsMultipleScenes causes black screen

### ISSUE THREAD

**Issue by CrixuAMG** [ionic-team/capacitor#2062]
# Bug Report

## Capacitor Version
```
`npx cap doctor` output:
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 1.2.1

  @capacitor/core: 1.2.1

  @capacitor/android: 1.2.1

  @capacitor/ios: 1.2.1

Installed Dependencies:

  @capacitor/cli 1.2.1

  @capacitor/core 1.2.1

  @capacitor/android 1.2.1

  @capacitor/ios 1.2.1


[success] Android looking great! 👌
  Found 2 Capacitor plugins for ios:
    cordova-plugin-inapppurchase (1.2.0)
    cordova-plugin-inapppurchase-fixed (1.1.2)
[success] iOS looking great! 👌
```

## Affected Platform(s)
- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
When enabling "Supports multiple windows" in Xcode and building the app, the result is a black screen, no errors logged. Disabling this option it works as expected.
This also occurs on iPhones, not only iPads are affected.

## Expected Behavior
When enabling "Supports multiple windows" the app should run and display the app.

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v10.16.3

`pod --version` output (iOS issues only): 1.7.5

**Comment by jcesarmobile** [comment]
Since this is a new iOS 13 feature, I'm tagging the issue as feature request.

Issues tagged with feature request are closed but tracked for reactions to gauge interest.

But have in mind that this is not compatible with iOS 12 and Capacitor still supports iOS 11, so enabling it for iOS 13 while keeping compatibility with iOS 11 and 12 will be challenging.
