### ISSUE TITLE
feat: make capacitor really cross-platform 

### ISSUE THREAD

**Issue by LifeIsStrange** [ionic-team/capacitor#2069]
# Feature Request

## Describe the Feature Request
When I look at https://cordova.apache.org/plugins/
I see that Cordova plugins can support the following platforms:
Android
IOS
Windows
Browser
MacOS

I see that capacitor advertise support for
Android
iOS
Electron
Web

My first question is what % of support do you have per platform vs Cordova? (what percentage of Cordova plugins works in capacitor per platform)

My second question is:
Cordova advertise windows and macOS while you claim electron support. 
Are there meaningful differences? 
The cordova windows/macOS compatible plugins will work in capacitor electron? 
Do they support more things than electron, what for example? 
How mature is your electron support? 

Off topic:
I would have hoped that capacitor and electron would merge in order to be the most compatible and consistent.

Thanks

Final question:
https://cordova.apache.org/plugins/
Is awesome to browse plugins. 
It would be really nice if you contributed to this webpage by adding a filter by capacitor compatible plugins.
You could offer a forked version of the webpage on ionic website, showing capacitor plugins by default.
Capacitor really needs plugin searchability and transparency about known compatible plugins to really be trusted.
As a developer I am not going to switch to capacitor until I know that most of the 4643 plugins are capacitor compatible.

**Comment by jcesarmobile** [comment]
Please, don't use github issues to ask questions. For asking questions you can use the [forums](https://forum.ionicframework.com/) or join [slack](https://getcapacitor.herokuapp.com)

Most of the questions can be answered by a bit of googling and some of them are not even related to Capacitor. Some "questions" are not questions.

And the % questions are impossible to measure because nobody knows what % of cordova plugins work on latest versions of cordova-cli, cordova-ios and cordova-android, so not possible to compare.

Known incompatible plugins are documented [here](https://capacitor.ionicframework.com/docs/cordova/known-incompatible-plugins)

You can find a list with some 3rd party plugins [here](https://capacitor.ionicframework.com/docs/community/plugins) 

And also use [npmjs search with capacitor keyword](https://www.npmjs.com/search?q=keywords%3Acapacitor)
