### ISSUE TITLE
Installation of ionic capacitor app to device (Android)

### ISSUE THREAD

**Issue by AlluNandaKishore** [ionic-team/capacitor#2073]
Hi,
I'm trying to install **capacitor** application to new device and it is installing in few devices.
When i try to install in **Tablet** sized device its showing black screen.
On inspect, i can see this error **SyntaxError: Use of const in strict mode**.

Can anyone help me with this issue...

**Comment by jcesarmobile** [comment]
what's the Android version of the device? 
Is it a device or emulator?
what do you get if you run `navigator.userAgent` on Chrome inspector?

**Comment by AlluNandaKishore** [comment]
Device android version is 5.0.
On **navigator.userAgent** it shows
**"Mozilla/5.0 (Linux; Android 5.1; TL_S933L Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36"**

**Comment by jcesarmobile** [comment]
You might be using an old version of Capacitor, because it doesn't use const in the code anymore. Or that might come from some plugin.

Anyway, Capacitor [requires](https://capacitor.ionicframework.com/docs/getting-started/dependencies#android-development) an Android WebView with Chrome version 50 or later. Your device has 39.0.0.0.

**Comment by AlluNandaKishore** [comment]
Thank you **jcesarmobile**

**Comment by AlluNandaKishore** [comment]
Hi,
I felt on updating **Android WebView** version by installing app in device will solve my issue.
But, i still have the same issue, its installing the application but on opening it has a blank white screen.
No screens were displayed
