### ISSUE TITLE
bug: can't install capacitor/ios from local repo

### ISSUE THREAD

**Issue by josh-m-sharpe** [ionic-team/capacitor#2097]
# Bug Report

## Capacitor Version

- master
- tags/1.2.1

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
These all work:

yarn add ../../capacitor/android
yarn add ../../capacitor/core
yarn add -D ../../capacitor/cli

This does not:
yarn add ../../capacitor/ios

## Sample Code or Sample Application Repo

```
 $ yarn add ../../capacitor/android
yarn add v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @capacitor/android@1.2.1
info All dependencies
└─ @capacitor/android@1.2.1
✨  Done in 15.16s.
 
 $ yarn add ../../capacitor/core
yarn add v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved 1 new dependency.
info Direct dependencies
└─ @capacitor/core@1.2.1
info All dependencies
└─ @capacitor/core@1.2.1
✨  Done in 8.86s.

 $ yarn add -D ../../capacitor/cli
yarn add v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @capacitor/cli@1.2.1
info All dependencies
└─ @capacitor/cli@1.2.1
   Done in 9.41s.


 $ yarn add ../../capacitor/ios
yarn add v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error /Users/jsharpe/capacitor@0.0.0: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

## Other Technical Details

`npm --version` output:
6.9.0
`node --version` output:
v10.16.3
`pod --version` output (iOS issues only):
1.8.4

**Comment by PR1YANKPAT3L** [comment]
https://github.com/ionic-team/capacitor/tree/master/example Did you follow this step?

**Comment by josh-m-sharpe** [comment]
I saw that.  I don't want to test capacitor in the confines of an example app.  I want to test it in my app.  Actually - to test your PR: https://github.com/ionic-team/capacitor/pull/2045

**Comment by bibyzan** [comment]
Did you try changing your podfile in `ios/App/Podfile` to point to your local fork? 
```pod 'Capacitor', :path => '../forked-repos/capacitor'
  pod 'CapacitorCordova', :path => '../forked-repos/capacitor'```
Then run `pod update` in the `ios/App` directory

**Comment by PR1YANKPAT3L** [comment]
This is somewhat janky but you can also just set a postinstall hook to copy ios files over.

```
"postinstall": "npm run ios:copy && ...",
"ios:copy": "cp -r ../capacitor/ios ./node_modules/@capacitor/ios/ios",
```

**Comment by josh-m-sharpe** [comment]
Truthfully, I have no usecase to test `@capacitor/ios` locally at this moment.  I only noticed the issue when trying to install core, cli and android locally.  All of those install with `yarn add ~/path/to/capacitor/XYZ`.  As ios was an exception to that I opened this issue thinking it might be a quick fix and/or I was doing something wrong.

That said, I also cannot build a an android app even after installing `capacitor/android` locally.

I think all of this is general shortcomings of this document:
https://github.com/ionic-team/capacitor/blob/master/.github/CONTRIBUTING.md

Are there steps that outline how to develop on the platforms using local versions of capacitor?

**Comment by bibyzan** [comment]
That document links to this one https://github.com/ionic-team/capacitor/blob/master/example/README.md which explains installing the pods on the IonicRunner project. I was able to pretty easily take the instructions on the example app and apply it  to my own project with prior cocoa pods experience, but perhaps it could be made more clear how to use it on your own. Also the link to this document from the `CONTRIBUTING.MD` needs to be way more apparent I would think because I passed it the first time I read through it.

**Comment by jcesarmobile** [comment]
This is because ios folder is not a proper package. It's like that because CocoaPods doesn't allow pods in folders, they need to be on the root to the github repository (notice that Capacitor.podspec and CapacitorCordova.podspec are both in the root of this repository).
That conflicts with ios folder being a proper npm package.

So, what we do is, as part of the publish process, `./scripts/generate.sh` is run and it creates a new capacitor-ios folder with a proper npm package and that's what publish.

So as workaround you can run that script and then install with `yarn add ../../capacitor/capacitor-ios`. But it's not something we can fix. Will close as won't fix.

**Comment by josh-m-sharpe** [comment]
Probably worth spelling those steps out in the README so others can help out in the future.

**Comment by jcesarmobile** [comment]
ios folder is a proper package now and can be installed from local repo, so removing the won't fix label
