### ISSUE TITLE
bug: Cors error 

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/capacitor#2132]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
npx cap doctor
   Capacitor Doctor
Latest Dependencies:
  @capacitor/cli: 1.3.0
  @capacitor/core: 1.3.0
  @capacitor/android: 1.3.0
  @capacitor/ios: 1.3.0

Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/cli 1.3.0
  @capacitor/core 1.3.0
  @capacitor/android 1.3.0
```

## Affected Platform(s)

- [X ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Getting cors error in real device even cors is already enabled at backend side. With ionic 3 it is working fine.
```
Access to XMLHttpRequest at 'https://xxx.xx.xxx/getuser' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource
```
I have set this in capacitor.config.json
```
  "android": {
    "allowMixedContent": true
  }
```

## Expected Behavior

It should work like ionic 3.

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v10.16.3

`pod --version` output (iOS issues only):

## Other Information

```
ionic info

Ionic:

   Ionic CLI                     : 5.4.4 (C:\Users\indra26\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.2
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.9

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Comment by pklime2** [comment]
I'm seeing a similar issue on Android only since upgrading to v1.3.0.  From what I can tell based on the logs it may be related to this change 

https://github.com/ionic-team/capacitor/commit/ccc00b3666dec87d7345866295604378aef15c5c
Specifically line 175 of android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

The logs indicate that my server's API URL is being treated as a local request and is calling handleLocalRequest instead of handleProxyRequest.  In my case the "server.url" property is not set in capacitor.config.json which means this is always evaluating to true.

I'm not 100% certain this is the case, but I'm going to downgrade to v1.2.0 in the interim.

**Comment by indraraj26** [comment]
Hi @pklime2 ,

Can you share your capacitor.config.json, i am not sure whether i will have to add
```
 server :{
url:yourdomain'
}
```

btw what is the purpose of this server url.

Thank you

**Comment by pklime2** [comment]
This is what I currently have set

```
{
  "appId": "com.myapp",
  "appName": "App",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "www",
  "server": {
    "allowNavigation": [
      "*.mydomain.com"
    ]
  },
  "plugins": {
    "Keyboard": {
      "resize": "ionic"
    },
    "SplashScreen": {
      "launchAutoHide": false
    }
  }
}
```
Based on the documentation it looks like the server.url property is used for loading a local web server for live reloading (e.g. Angular), but in my case I'm seeing this error on a build created using `ionic build --prod`.
