### ISSUE TITLE
bug: Camera API getPhoto does not indicate if user cancelled the initial dialog

### ISSUE THREAD

**Issue by tjbeanz** [ionic-team/capacitor#2196]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
```
Latest Dependencies:
  @capacitor/cli: 1.3.0
  @capacitor/core: 1.3.0
  @capacitor/android: 1.3.0
  @capacitor/ios: 1.3.0

Installed Dependencies:
  @capacitor/cli 1.2.1
  @capacitor/ios 1.2.1
  @capacitor/android 1.2.1
  @capacitor/core 1.2.1
```

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When using the Capacitor Camera API and calling `getPhoto` with the default source as "PROMPT", if you select "Cancel" from the first view (the `UIAlertController`), there is no way to detect that the user has cancelled photo selection.

## Expected Behavior

The behavior should be similar to what happens if they select "From Photos" or "Take Picture" in the `UIAlertController` and then choose "Cancel".  The same change that was made in [this PR](https://github.com/ionic-team/capacitor/pull/808)

## Other Information

Discussed [here](https://getcapacitor.slack.com/archives/C94SE07NJ/p1574202077119100)

**Comment by arnotixe** [comment]
I'm wondering if this also bites me in browser? I get multiple uploads when:

- clicking something that calls Camera.getPhoto() which opens a file upload prompt in web browser
- Cancelling that dialog
- clicking something that calls Camera.getPhoto() again, this time uploading a photo from web browser
- The photo is uploaded twice (or, to be precise, it uploads as many duplicates as the number of times I first cancel the file upload dialog)
My code:
```
async takePicture() {
    await Camera.getPhoto({
      quality: 90,
      saveToGallery: false,
      promptLabelHeader: 'Ta bilde eller last opp',
      resultType: CameraResultType.Base64,
      width: 1500, // save disk and download resources
    })
      .then((image) => {
        
        // waat? cancelling the dialog makes the same image upload twice / as many times as the dialog has been cancelled
        console.log('now upload picture', image);
        this.uploadBase64("data:image/jpeg;base64, " + image.base64String); // new function
      })
.catch( err => {
```
I DO have catch, but does not catch on cancel in browser

I have capacitor 2.4.1 and if I read the fix correctly, it was fixed in 3.0.0+ (?) so I will try updating capacitor to >3 when I have time to see if that helps before pushing more on this.
