### ISSUE TITLE
Android build not working: SyntaxError Unexpected token

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ionic-team/capacitor#2201]
# Bug Report

## Capacitor Version
```
    "@capacitor/android": "1.0.0",
    "@capacitor/cli": "1.0.0",
    "@capacitor/core": "1.0.0",
    "@capacitor/ios": "1.0.0",
```

## Affected Platform(s)

- [x ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

**Only Android**

## Current Behavior
When I run the App in Android it shows a weird error `Unexpected token = `, it works well in other platforms.

## Sample Code or Sample Application Repo

<img width="587" alt="Screen Shot 2019-11-21 at 7 01 07 PM" src="https://user-images.githubusercontent.com/11672878/69386983-4f18b800-0c92-11ea-90d3-a87eb4290ae5.png">

## Reproduction Steps

My friend tried on his computer and it works (same versions of node/capacitor), doesn't look related to our code. 

## Other Technical Details

`npm --version` output: 6.9.0

`node --version` output: v12.3.1

**Comment by bryplano** [comment]
Can you update your versions to the latest and try again?

**Comment by sta55en** [comment]
Which device are you testing with? I'm seeing the same type of error on a Galaxy S6.

`Uncaught SyntaxError: Unexpected token {`

I believe it is happening because of ES6 destructuring being used like so:

```
const { Filesystem } = Plugins;
```
I don't think the older device supports this language feature and I don't think it is being transpiled into something that the older browser can use.

**Comment by jcesarmobile** [comment]
closing since none of the questions were answered and the reporter is using a very old capacitor version.
