### ISSUE TITLE
bug: Browser Plugin toolbarColor does not show up correctly. Probably is set as translucent

### ISSUE THREAD

**Issue by rrlevy** [ionic-team/capacitor#2240]
# Bug Report

## Capacitor Version

Latest Dependencies:
  @capacitor/cli: 1.4.0
  @capacitor/core: 1.4.0
  @capacitor/android: 1.4.0
  @capacitor/ios: 1.4.0

Installed Dependencies:
  @capacitor/cli 1.4.0
  @capacitor/core 1.4.0
  @capacitor/android 1.4.0
  @capacitor/ios 1.4.0

[success] Android looking great! 👌
  Found 3 Capacitor plugins for ios:
    capacitor-fcm (0.1.0)
    cordova-plugin-ionic (5.4.5)
    cordova-plugin-whitelist (1.3.4)
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When opening an InApp Browser link using the Capacitor Browser plugin while setting a toolbarColor, the actual color of the toolbar is not the same as the one set.c

Maybe the In App Browser is being opened using the translucent option.

## Expected Behavior

There should be an option to turn translucent on or off

**Comment by jcesarmobile** [comment]
can you provide a sample app and some screenshots? 

I've set it to FF0000 and to me it looks the same as on my computer screen

**Comment by jcesarmobile** [comment]
closing as there was no response and I can't reproduce

**Comment by ghernagon** [comment]
Even when this issue is closed, could you try with a color like #EC0000? this is a red color but in iOS there is a little opacity implemented on navBar and depends on what kind of content you are loading inside SFSafariViewController you can see the blur effect under the navBar when you scroll your site. So the real color is lighten a little by the OS. I don't know if there is any way to fix this, maybe replace SFSafariViewController with a WKWebView
