### ISSUE TITLE
bug: Crash / restart due to OOM, when capturing a photo via <input> element

### ISSUE THREAD

**Issue by sandstrom** [ionic-team/capacitor#2265]
# Bug Report

The app crashes/restarts when taking photos via file-input element (intermittently). Probably due to an out of memory (OOM) issue, where the OS tells the app to free memory.

## Capacitor Version

<details>
<summary>Using Capacitor 1.2.1  (expand for npx capacitor doctor command)
</summary>

```
$ npx capacitor doctor
💊   Capacitor Doctor  💊 
Latest Dependencies:
  @capacitor/cli: 1.4.0
  @capacitor/core: 1.4.0
  @capacitor/android: 1.4.0
  @capacitor/ios: 1.4.0

Installed Dependencies:
  @capacitor/cli 1.2.1
  @capacitor/core 1.2.1
  @capacitor/ios 1.2.1
  @capacitor/android 1.2.1

[success] Android looking great! 👌
  Found 1 Capacitor plugin for ios:
    cordova-plugin-nativestorage (2.3.2)

[success] iOS looking great! 👌
```

</details>

## Affected Platform(s)
- iOS
- * Android not affected*
- * Electron not affected*
- * Web not affected*

## Current Behavior
Take a photograph using the camera on iOS, via an html input element. This happens ~1/5 times on an iPhone 8 (with 2 gb ram and 20 gb of free disk storage).

When checking the logs when connected to XCode this message is shown:

```
2019-12-17 14:03:20.020185+0100 App[26652:8475493] Received memory pressure event 1 vm pressure 0

Received memory pressure event 1 vm pressure 0
2019-12-17 14:04:06.478996+0100 App[26652:8475493] Received memory pressure event 4 vm pressure 1

Received memory pressure event 4 vm pressure 1

```

## Expected Behavior
Camera will return to the webview, and the input element will have the `files` property populated. This works ~4/5 times.

## Sample Code & Reproduction Steps

```html
<p>
1. Open a bunch of other apps on the phone (running in the background).
2. Try taking photos repeatedly using this html snippet.
3. The webview will crash/reload (the actual iOS app doesn't crash).
</p>

<input type='file' multiple accept='image/*'>
```

## Reproduction Steps

*See steps in sample code above.*

## Other Technical Details

*n/a*

## Other Information
We've recently ported our app over from Cordova to Capacitor. This code has worked flawlessly for several years and tens of thousands of users. In other words, this technique for grabbing photos via the input element has been robust.

Overall we're very happy with the move to Capacitor! But this issue has appeared after the migration.

Maybe there is some type of memory tuning that Cordova was doing on its web view, that Capacitor isn't doing? (just a guess)

This seems to be what Capacitor is doing right now:
```swift
  override public func didReceiveMemoryWarning() {
    super.didReceiveMemoryWarning()
    // Dispose of any resources that can be recreated.
  }
```

1. Does iOS send this message to all apps? In that case it would be better if Capacitor didn't jumped forward offering to trash (calling super), if background apps could release stuff.

2. Can we somehow track that the camera is in the foreground and skip calling super in that case?

3. Would it be possible to detect that the webview isn't in the foreground (and infer that the camera is running via an input element, therefore we shouldn't be quick to dispose of any resources)?

4. Would it be possible to adjust `webViewWebContentProcessDidTerminate` so that the JS-layer could be aware of the restart, i.e. know that the app crashed and restarted. Even though we wouldn't know the reason, at least we'd know that it happened.

After looking through the Cordova source I noticed that this is how they handle this:
https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/Public/CDVViewController.m#L578

It isn't obvious to me why we've never seen this issue under Cordova, since their handling seems similar (since I don't think any plugin would return `hasPendingOperation` only because an input element has triggered the camera). But I suspect there are more factors in play here besides just the call to `didReceiveMemoryWarning`.

Also, I'm guessing the restart may be due to `webViewWebContentProcessDidTerminate` being called in `CAPBridgeViewController`.

**Comment by jcesarmobile** [comment]
Not sure if when you were using Cordova you were using UIWebView or WKWebView, but WKWebView consumes more memory than UIWebView.

input file is entirely handled by the webview, not by Capacitor. It internally uses `UIImagePickerController`, which is also used in Camera plugins (for both Cordova and Capacitor) and for Cordova I've seen multiple similar issues reported over time, so it's probably a problem on the `UIImagePickerController` itself.

Also some iOS versions have had memory handling problems on WKWebView that caused the webview to "restart".

It's also possible that Capacitor consumes a bit more memory than a regular Cordova app since it ships with all the plugins, while in Cordova you can control which ones to install.

**Comment by sandstrom** [comment]
@jcesarmobile Makes sense, thanks!

Alright, perhaps we'll be able to include plugins selectively in Capacitor in the future, to cut down on memory usage. But you're right, we did use `UIWebView` in Cordova, so that is also a factor.

And how about the `didReceiveMemoryWarning` call, any chance tweaking it would avoid some crashes, by having the OOM kill other stuff in the app instead of the active Capacitor app? Would seem more reasonable to kill other stuff first.

https://github.com/ionic-team/capacitor/blob/0a25cce21f935c0d18cdeb9b0e04a9b6145f2072/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L380-L383

```objective-c
- (void)didReceiveMemoryWarning
{
    // iterate through all the plugin objects, and call hasPendingOperation
    // if at least one has a pending operation, we don't call [super didReceiveMemoryWarning]

    NSEnumerator* enumerator = [self.pluginObjects objectEnumerator];
    CDVPlugin* plugin;

    BOOL doPurge = YES;

    while ((plugin = [enumerator nextObject])) {
        if (plugin.hasPendingOperation) {
            NSLog(@"Plugin '%@' has a pending operation, memory purge is delayed for didReceiveMemoryWarning.", NSStringFromClass([plugin class]));
            doPurge = NO;
        }
    }

    if (doPurge) {
        // Releases the view if it doesn't have a superview.
        [super didReceiveMemoryWarning];
    }

    // Release any cached data, images, etc. that aren't in use.
}
```

https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/Public/CDVViewController.m#L578

***

I've opened an issue (https://github.com/ionic-team/capacitor/issues/2379) for better insight into crashes. If we knew that the app had crashed at least we could notify the user.

**Comment by jcesarmobile** [comment]
the webview "crash" is detected in `webViewWebContentProcessDidTerminate`, and what we do there is to reload the app.
That method wasn't available on UIWebView, there the apps just might hang or crash. I think the reload, despite can be annoying, is less annoying that being unresponsive or a crash.

It's not clear what happens before that method gets called, and can't be prevented, and as I said on my previous comment, in some iOS versions it gets called too often, I see it even when using Safari, some websites restart a lot and it's because of that.

**Comment by sandstrom** [comment]
@jcesarmobile I think I understand. My suggestion in https://github.com/ionic-team/capacitor/issues/2379 is that perhaps we could let the JS-layer know about the crash, for example using an event-listener + trigger that event after the reload has completed.

That way, the app can take appropriate measures, for example restore unsaved data from local storage, or let the user know that the app has crashed.

In our particular example we'd let the user know that the camera crashed and that no photo was uploaded to our servers. Otherwise they may think they've uploaded a photo, but they haven't and they'll wonder why (and what happened).

**Comment by diachedelic** [comment]
I am experiencing this same intermittent reloading of the webview after capturing photos via an <input> element - it was very difficult to diagnose, because the webview reloaded so quickly I didn't notice it (seems like #2379 would help with this). Our users are experiencing data loss due to this issue so it would be great to find a solution, thought I understand it's probably due to some webkit memory leak.

**Comment by diachedelic** [comment]
For anyone else who comes across this problem, for me it was caused by a serious memory leak in iOS 12+ when using canvas the resize the captured image: https://github.com/openlayers/openlayers/issues/9291. Fortunately there is a simple workaround - set the canvas dimensions to zero to "dispose" of it.
