### ISSUE TITLE
feat: Browser Plugin execute javascript and insert CSS

### ISSUE THREAD

**Issue by digaus** [ionic-team/capacitor#2274]
# Feature Request

## Describe the Feature Request

Add methods to execute javascript and insert CSS after the browser finished loading. 
## Platform Support Requested

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Additional Context

Currently am using inappbrowser plugin. This however results in a warning from Apple since UIWebView is deprecated and might get removed.

So my preferable solution is to switch to a capacitor alternative. However for this it would need the described functions.

**Comment by jcesarmobile** [comment]
Capacitor uses SFSafariViewController on iOS and Chrome Custom Tabs in Browser plugin, so this can't be implemented because they don't provide such APIs.

InAppBrowser plugin also allows to use WKWebView instead of UIWebView, latest version included a compiler flag to "remove" the UIWebView code, next major release will delete all the UIWebView code.

**Comment by digaus** [comment]
> Capacitor uses SFSafariViewController on iOS and Chrome Custom Tabs in Browser plugin, so this can't be implemented because they don't provide such APIs.
> 
> InAppBrowser plugin also allows to use WKWebView instead of UIWebView, latest version included a compiler flag to "remove" the UIWebView code, next major release will delete all the UIWebView code.

Yep saw that issue there and seems to be on final steps to be released. I also noticed that it is not possible with the current implement in capacitor.

I just prefer to move everything to capacitor and only use cordova plugins if necessary.
