### ISSUE TITLE
bug: iOS sync or copy generates multiple config.xml and capacitor.config.json files

### ISSUE THREAD

**Issue by digaus** [ionic-team/capacitor#2292]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

All 1.4

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Calling sync or copy results in duplicate files 
![20191231_124641](https://user-images.githubusercontent.com/15358538/71620868-72f1e680-2bcc-11ea-8706-03ef3ae8c6d2.jpg)

## Expected Behavior

Copy and sync should only update old files

**Comment by jcesarmobile** [comment]
I can't reproduce, can you provide more information and/or a sample project?

**Comment by digaus** [comment]
> I can't reproduce, can you provide more information and/or a sample project?

Think I made a mistake. Duplicates got generated by `npm run build -- --prod`.

This happens on macOS. I can added you to the private repo. Make sure to also init the git submodules after you cloned the repo.

**Comment by jcesarmobile** [comment]
I've not been able to run your project since it references a few plugins that are out of the committed code. When we ask for a sample project, it's usually a simple project where the problem can be reproduced easily, not your real project.

I've been trying to reproduce on my own project, running sync and copy at the same time and even doing an Xcode archive while executing copy and sync and the files were never duplicated.

Might be related to the node version, I tested on v10.17.0.

Anyway, since it's hard to reproduce even to you, I'm marking this a low priority.

**Comment by digaus** [comment]
> I've not been able to run your project since it references a few plugins that are out of the committed code. When we ask for a sample project, it's usually a simple project where the problem can be reproduced easily, not your real project.
> 
> I've been trying to reproduce on my own project, running sync and copy at the same time and even doing an Xcode archive while executing copy and sync and the files were never duplicated.
> 
> Might be related to the node version, I tested on v10.17.0.
> 
> Anyway, since it's hard to reproduce even to you, I'm marking this a low priority.

Yeah my bad. Forgot to change my plugins.

It is not a big error anyways. Will see if changing node version helps.

Will close it and if anyone else also has this issue we can look again

**Comment by riderx** [comment]
i have the issue too

**Comment by digaus** [comment]
> i have the issue too

Can you pinpoint the exact moment when this happens and what IDE are you using?

**Comment by riderx** [comment]
I use Vs code, but i don't know when that started

**Comment by digaus** [comment]
> I use Vs code, but i don't know when that started

Yep also using VS Code. I think it might also happen on run build.
