### ISSUE TITLE
Remove or implement FilesystemDirectory.Application

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/capacitor#2312]
Current implementation has [never worked](https://github.com/ionic-team/capacitor/issues/1835), so I think it should be removed or properly implemented.

It raises a few questions:
1) Do we really want it when everything in the public folder is already accessible with a fetch/xhr call?
2) Should it be the public folder or the root of the app (the parent of public folder)?
3) In case of using Appflow's deploy feature (or something similar), should it be the original files the app shipped with or the downloaded files?

Supporting it on iOS is just a few lines change, but on Android it's a bit more complex because the files in assets folder are not really accesible as File objects, only as InputStreams.

In case it's implemented, it should be documented that it's read only, and all write functions should return an error if trying to write there. 

Either if we remove it or implement properly it's a breaking change since people might be using it in Android, despite it doesn't provide the application folder, it returns a folder, so the changes will remove the option or return a different folder.

**Comment by nphyatt** [comment]
I think this was basically intended to be the equivalent of the Application Directory in the cordova-plugin-file which was the root of the app (parent of public). I'm guessing that because of the involved nature of the Android side where it was punted on. My vote would be to remove it. If we see that it's a highly requested feature we can bring it back and it wouldn't be a breaking change at that point as it would be new functionality.
