### ISSUE TITLE
feat: Camera select multiple photos

### ISSUE THREAD

**Issue by Kepro** [ionic-team/capacitor#2316]
# Feature Request

## Describe the Feature Request
I want to be able to select multiple photos from the gallery

## Platform Support Requested

- [x] Android
- [x] iOS
- [x] Electron
- [x] Web

## Describe Preferred Solution
create method getPhotos same as getPhoto just return an array

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Note that you can use the html `input` tag with type `file` and `multiple` attribute, that should work on all platforms.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

**Comment by vernondris** [comment]
> Issues tagged with feature request are closed but tracked for reactions to gauge interest.
> 
> Note that you can use the html `input` tag with type `file` and `multiple` attribute, that should work on all platforms.
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

But this approach is different. Adding multiple selection to capacitor will be better

**Comment by Kepro** [comment]
also with input file multiple you cannot limit maximum files to select for example...

**Comment by kevinclarkadstech** [comment]
Any update on this?  It's the only thing that prevents me from using Capacitor for choosing from the gallery.

**Comment by Kepro** [comment]
I switch to react-native forget about the hybrid application it's pain with minimum support...

**Comment by davidst2017** [comment]
> I switch to react-native forget about the hybrid application it's pain with minimum support...

I am right now having the same issue as you and it is really easy to fix. I don't think it's the framework's problem. It might be yours. If you are not willing to put effort into things, you will also quickly be stuck with react-native.

**Comment by Komock** [comment]
After a short investigation, I think it's an important feature and should be in Camera Plugin.
Because if you replace plugin call with just click on `<input type="file" multiple>` you can't constrain few possibilities:
1. User can take video or photo (but I need the only photo for example)
2. User can upload any size/quality (which can be constrained with the plugin, I don't want to upload 6mb photos from iPhone to my backend)

<img src="https://user-images.githubusercontent.com/7387686/103476723-4c5f2080-4dc9-11eb-840e-ba2f85b4a835.png" width="277" height="x600" />
