### ISSUE TITLE
When `npx cap add ios` fails (because of missing `www`), error message is only semi helpul

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#232]
```
MacBook-Pro:ionic-epubjs sujan$ npx cap add ios
✔ Adding native xcode project in: /Users/sujan/ionic-epubjs/ios in 38.45ms
✔ add in 40.57ms
✖ copy: Web dir doesn't exist. Make sure you've run npm build then run npx cap copy again
[error] Error: Web dir doesn't exist. Make sure you've run npm build then run npx cap copy again
    at common_1.runTask (/Users/sujan/ionic-epubjs/node_modules/@capacitor/cli/dist/tasks/copy.js:29:19)
    at <anonymous>
```

I never ran `npx cap copy`, so I don't really understand how this relates to what I actually wanted to do.

**Comment by janpio** [comment]
Related, if I actually build the app and run the same command again the proejct seems to be in a broken state:

```
MacBook-Pro:ionic-epubjs sujan$ npx cap add ios
[error] "ios" platform already exists.
    To add a new "ios" platform, please remove "/Users/sujan/ionic-epubjs/ios" and run this command again.
    WARNING! your xcode setup will be completely removed.
```

Maybe this could be covered by the earlier failing CLI command?

**Comment by janpio** [comment]
Re my first message: Ah, this error messgae should say: 
> ... sure you've run `npm build` then run `npx cap copy` again
Maybe it would make sense to mention that `www` is missing or empty and that the user should build their web app.

**Comment by jcesarmobile** [comment]
There is another problem, as copy fails, update is not run and the native projects are broken because of that.
So we should change it for:
1. Show a better error message
2. Run update anyways

I think what you say about running `npx cap add ios` again is expected, despite it failed to complete, it already created the project, so you shouldn't run it again. But we should make sure update is run to avoid problems.

**Comment by jcesarmobile** [comment]
I think this is fixed now, closing.
Please reopen if you still think it's not clear enough
