### ISSUE TITLE
feat: console log to native console

### ISSUE THREAD

**Issue by disbelief** [ionic-team/capacitor#2320]
# Feature Request

Send console.log lines to the native logging system on iOS.

## Describe the Feature Request

I'd love to see my `console.log` lines from my iOS app show up in the macOS console when I have my iPhone connected to my Mac.

I can currently see them in XCode, but I'm talking about running the real app on my phone, connecting it to my Mac, and viewing the logs using the macOS console.app.

## Platform Support Requested

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

I'm not very experienced with iOS development, so I'd defer to whatever solution is provided. Just want to get access to the logs to see what's going on with my app, since there are things that can't be tested in the simulator alone.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.


This is a really easy  to implement, Console plugin should just use NSLog instead of print, but NSLog is slower, so I wouldn't make this default, should be configurable and keep using print by default.

**Comment by disbelief** [comment]
In the meantime if anyone is interested I built a quick Capacitor plugin that does what I needed using Apple's [recommended](https://developer.apple.com/documentation/os/logging) `os_log` system. 

https://github.com/Mote-OU/capacitor-native-log

It only has web and iOS support at the moment but Android will be added shortly. Comments, suggestions are very welcome!

**Comment by disbelief** [comment]
Added Android support in version `0.2.0` https://www.npmjs.com/package/capacitor-native-log

**Comment by gugahoi** [comment]
Adding this would very much improve debuggability of a Capacitor app. Use case we currently have:

- we have deep links implemented but we observe that they only work when app is backgrounded 
- on cold starts, we want to know what is happening but can't get those logs via XCode. This is because XCode auto starts the app and attaches the logger to the running instance. If you close the app (not background it), then you can no longer get the logs in the XCode console.
- since we need to debug "opening the app from a cold start, through a deep link", we can't get the logs through XCode

It's unfortunate that `console.log` doesn't show up in the `Console.app` and this makes debugging this issue much harder. I would imagine that would be other use cases that require a fresh app start as well.

**Comment by maxfloden** [comment]
@jcesarmobile Any update on this issue? 

(I am currently trying to debug an issue that only occurs in published app (ie not debug or Testflight) making the console.app the only way known to me to see app logging)
