### ISSUE TITLE
bug: iosScheme 'file' is not used as origin

### ISSUE THREAD

**Issue by adamhannigan** [ionic-team/capacitor#2345]
# Bug Report

## Capacitor Version

`npx cap doctor` output:

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 1.4.0

  @capacitor/core: 1.4.0

  @capacitor/android: 1.4.0

  @capacitor/ios: 1.4.0

Installed Dependencies:

  @capacitor/cli 1.3.0

  @capacitor/core 1.4.0

  @capacitor/ios 1.4.0

  @capacitor/android 1.4.0


[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```
## Affected Platform(s)

- [X] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

When migrating from a vanilla Cordova application (non-Ionic) to Capacitor, the device loses all localStorage and indexedDB data that is bound to the origin scheme.

Cordova binds these resources to the `file://` scheme by default. Inside the IOS file storage these can still be found inside the WebKit cache under the IndexedDB `file__0` directory.

However, when `file` is used as the scheme, it does not override the `capacitor` scheme that is used.

```
  "server": {
      "iosScheme": "file"
  }
```

## Expected Behavior

Setting `iosScheme` to file, binds the apps resources to the `file://` origin and allows users to migrate from a vanilla Cordova app to a Capacitor app.

## Other Technical Details

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

**Comment by sandstrom** [comment]
One solution is to (1) add a "native storage" plugin in your Cordova app, (2) migrate the keys from localStorage to `Sharedpreferences` (in Android) and `NSUserDefaults` (in iOS), (3) move to Capacitor and (4) read data from these locations, (5) optionally write back to localStorage under new origin. 

But generally, `localStorage` is a bad choice because it'll get arbitrarily wiped on iOS and Android when disk storage is running low. You'll see much better data durability in the two aforementioned native storage layers.

**Comment by jcesarmobile** [comment]
schemes that are already registered by the WKWebView (http, https, file, etc) are not allowed as custom schemes (by the WKWebView, not us).

Also file scheme has a number of issues on WKWebView, that's why Capacitor uses custom schemes, and Cordova will probably do that on next major release too.

There are plugins that move the data from the webkit folders, people has used them when migrating to UIWebView to cordova-plugin-ionic-webview and between cordova-plugin-ionic-webview plugin versions (from 2 to 3 where the custom schemes were introduced). Not sure if they work in Capacitor, but you can check their code and do the same. We don't plan to do data migrations, that's up to the user.

**Comment by adamhannigan** [comment]
Thanks for clarity.

@sandstrom We would prefer not to do 2 separate releases of migrating the data into a more reliable location (SharedPrefs/SQLite etc) and then migrating to capacitor. It will be difficult to ensure users have downloaded the first release before the second.

@jcesarmobile That makes sense. I will experiment with these plugins or attempt to use the `File` API to copy the cached schemes.

**Comment by adamhannigan** [comment]
For those interested. We achieved an IOS IndexedDB migration using the capacitor `FileSystem` plugin.

Example.

```
import { Capacitor, Plugins, FilesystemDirectory } from '@capacitor/core'

const { Filesystem, Device } = Plugins

function migrateCordovaToCapacitor() {
		const cordovaDirectory = 'file__0'
		const capacitorDirectory = 'capacitor_localhost_0'

		// FilesystemDirectory does not support WebKit directory so go to sibling first
        const cacheFilePath = await Filesystem.getUri({
            path: '',
            directory: FilesystemDirectory.Cache,
        })

        // Remove the Cache path to get to the WebKit parent directory
        const libraryPath = cacheFilePath.uri.slice(0, -9)

        // Grab all the content inside of the old directory
        const oldDirectoryPath = `${libraryPath}/WebKit/WebsiteData/IndexedDB/v1/${cordovaDirectory}/0E8427A40831C384F7F1DE368BF96DF520C1559C6EF19FD7211E5971849679FD`
        const directoryContents = await Filesystem.readdir({
            path: oldDirectoryPath,
        })

        const newDirectoryPath = `${libraryPath}/WebKit/WebsiteData/IndexedDB/v1/${capacitorDirectory}/0E8427A40831C384F7F1DE368BF96DF520C1559C6EF19FD7211E5971849679FD`

        // Copy all the old content into the new directory
        await Promise.all(directoryContents.files.map(async (file) => {
            await Filesystem.copy({
                from: `${oldDirectoryPath}/${file}`,
                to: `${newDirectoryPath}/${file}`,
            })
        }))
}
```

**Comment by larsblumberg** [comment]
> schemes that are already registered by the WKWebView (http, https, file, etc) are not allowed as custom schemes (by the WKWebView, not us).

@jcesarmobile please update https://capacitorjs.com/docs/basics/configuring-your-app to let us developers know that certain iOS schemes are not supported. so we immediately know what's going wrong.

**Comment by ovictoraurelio** [comment]
Hi. I'm using Capacitor 3 to create a new release to my WebApp migrating from Cordova.

The app by Cap3 is losing my localStorage data... Because is loaded in http://localhost instead of file://android_asset... like in cordova before.

I'm trying to use the conf “server”: { “androidScheme”: “file” } but now I'm facing the error: 

The webpage at file://localhost could not be loaded because: net::ERR_ACCESS_DENIED

Any of you had the same problem before?

**Comment by beyondlevi** [comment]
Having the same issue as @ovictoraurelio.

Any workarround?

**Comment by jcesarmobile** [comment]
Using file is not supported in Capacitor and not recommended in Cordova (cordova-android 10 uses https by default now)
We didn't handle the case where users set the androidScheme to values that are unsupported, but we will in Capacitor 4
https://github.com/ionic-team/capacitor/issues/3854

There are Cordova plugins to do the data migration from file to http or https

**Comment by ArinaWik** [comment]
> Hi. I'm using Capacitor 3 to create a new release to my WebApp migrating from Cordova.
> 
> The app by Cap3 is losing my localStorage data... Because is loaded in http://localhost instead of file://android_asset... like in cordova before.
> 
> I'm trying to use the conf “server”: { “androidScheme”: “file” } but now I'm facing the error:
> 
> The webpage at file://localhost could not be loaded because: net::ERR_ACCESS_DENIED
> 
> Any of you had the same problem before?

Have you solved the issue ? I am having exactly the same problem. HELP PLEASE
