### ISSUE TITLE
Recommended method of testing contributing

### ISSUE THREAD

**Issue by MrPutuLips** [ionic-team/capacitor#243]
Hello there

I have written some code in a fork I now want to test.

What is the best way for me to quickly test the fork on a small project? Preferably without having to re-compile the entire project every time I change a line of code.

Thank you!

**Comment by jcesarmobile** [comment]
It depends, which code did you change? on the CLI? on native code?

**Comment by MrPutuLips** [comment]
I changed code in core for web plugins

**Comment by jcesarmobile** [comment]
Recommended way is using the example apps in example folder, and instead of installing @capacitor/core from npm, link it as explained on the [README.md](https://github.com/ionic-team/capacitor/blob/master/example/README.md)

for not recompiling, try running `npm run watch` from core folder, that works, at least with cli changes, didn't test with core.
