### ISSUE TITLE
App ID case forced lowercase and [a-z] only?

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#251]
```
C:\Projects
λ npx @capacitor/cli create Capacitor/createTest createTest de.janpiotrowski.capacitor.createTest
npx: installed 212 in 35.707s
C:\Users\Jan\AppData\Roaming\npm-cache\_npx\14876\node_modules\@capacitor\cli\bin\capacitor
Usage: npx @capacitor/cli create appDir appName appId
Example: npx @capacitor/cli create my-app "My App" "com.example.myapp"
[error] Invalid App ID "de.janpiotrowski.capacitor.createTest". Must be in domain form (ex: com.example.app)
```

Is this actually a valid requirements that the app ID is all lowercase?

Same for not allowing `-`:

```
λ npx @capacitor/cli create pluginDemos "Capacitor Plugin Demos" de.janpiotrowski.capacitor.plugin-demos
npx: installed 212 in 36.105s
C:\Users\Jan\AppData\Roaming\npm-cache\_npx\17600\node_modules\@capacitor\cli\bin\capacitor
Usage: npx @capacitor/cli create appDir appName appId
Example: npx @capacitor/cli create my-app "My App" "com.example.myapp"
[error] Invalid App ID "de.janpiotrowski.capacitor.plugin-demos". Must be in domain form (ex: com.example.app)
```

**Comment by HardikDG** [comment]
I think Apple is allowing uppercase case characters for the id.I have changed bundle id to uppercase in the Xcode and it run successfully. 

In another suggestion, I think in the documentation and in the example they should write bundle ID instead of App ID. As what they are showing in the example and documentation is bundle ID. App ID is a combination of the TeamID and Bundle ID for iOS development. I think they don't need that, they only need the bundle ID like we are using it in config.xml. 

I don't have any idea about requirements in the Android project as in all the projects I have been using lowercase letters

**Comment by janpio** [comment]
"Bundle ID" is an Apple specific term, for Android the equivalent would be "Package Name" or "Application ID", so it makes sense to normalize on an more abstract term like "App ID".

**Comment by mlynch** [comment]
We do this for now because Android requires a certain type of app id layout that impacts your Java package. We are pushing `com.example.app` as the standard pattern for App IDs. We then turn that into `com/example/app` on Android, and for iOS this pattern is common so I think it's fair. You can always go and change the bundle id yourself manually later in Xcode.

**Comment by janpio** [comment]
Does this exclude `-`?
Could this not just lowercase uppercase characters?

(I actually don't care _that_ much, was just surprised as I intuitively chose those names and then it didn't work)
