### ISSUE TITLE
iOS: XHR response headers missing

### ISSUE THREAD

**Issue by alexsasharegan** [ionic-team/capacitor#2517]
# Bug Report

This appears to be opposite end of the problem in #951, the response headers from my API server are not accessible via the XMLHttpRequest instance running the request. Perhaps there's some middle layer (isn't there a local webserver that proxies requests?) that does not pipe the response to JS verbatim.

## Capacitor Version

<details>
<summary>
`npx cap doctor` output:
</summary>

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.5.0

  @capacitor/core: 1.5.0

  @capacitor/android: 1.5.0

  @capacitor/ios: 1.5.0

Installed Dependencies:

  @capacitor/android not installed

  @capacitor/cli 1.5.0

  @capacitor/core 1.5.0

  @capacitor/ios 1.5.0


  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌
```

</details>

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

Currently, requests made via `XMLHttpRequest` only read back `Content-Length` and `Content-Type` headers, despite numerous other headers being sent.

## Expected Behavior

Expect access to all the response headers that a web browser would allow. Providing access to response headers would need to take care to hide some of the private headers (like `Set-Cookie` I believe), but I specifically need to access my API's custom `X-Header-Name` type headers.

## Reproduction Steps

- Use XMLHttpRequest to make a request: `https://jsonplaceholder.typicode.com/todos/1`
- Use the xhr instance to pull a custom header `xhr.getResponseHeader("x-powered-by")`
- Expect to see `"Express"`, but receive `null`

**Comment by jcesarmobile** [comment]
The provided url is not configured to allow CORS.

Anyway, not all headers are accesible, unless you configure `Access-Control-Allow-Headers` in the server, so that's probably the issue.

**Comment by alexsasharegan** [comment]
Cool, thanks for not taking this very seriously.

**Comment by alexsasharegan** [comment]
JSON placeholder is configured to allow cors. I can make a request from any browser page. I have been working really hard on getting passed this, I would appreciate you take more time on this.

**Comment by jcesarmobile** [comment]
Sorry, I meant, it's not configured to allow `capacitor://localhost`, which Capacitor iOS app use. Since you have checked the iOS checkbox I assume your problem is on iOS.

It allows CORS if loaded from http/https url (i.e. from Android or from a browser)
If I run from chrome it works, but I get the `Refused to get unsafe header "x-powered-by"`.

Also, before asking maintainers "to take more time on this", you should dedicate more time to provide good issues with reproduction steps or sample apps, not just "do a XHR call to this server", and an image proof that fetch works.

**Comment by alexsasharegan** [comment]
I'm very new to capacitor. Creating a reproducible case is very challenging for me. I don't have enough time to explore a case I can use to demonstrate this. I've already created a server proxy to relay headers to get around my internal, unsharable issue. I understand the difficulty of having maintainers follow every loose end, but I'm just limited in this and the XHR functionality is very clearly problematic in the given state of cordova apps. My team has already moved on with this potentially unsafe fix.

I'll see what I can do to improve the repro, but I guess I just wish this was enough work from my end to let you capacitor experts help check my issue.

**Comment by jcesarmobile** [comment]
If not a full app, at least the XHR code you used instead of saying "do a XHR call", or providing a line of code where you where do do the fetch call instead of showing an image  where you do it so I don't have to type the code from the image.

But I've typed your same code from the image and I get the same 4 headers, so I still don't think it's a bug. And when doing a XHR call from Chrome, I get the `Refused to get unsafe header "x-powered-by"`. My googling skills tell me that's a server configuration problem, not a Capacitor problem.

And even if it was, it's a WKWebView problem, not a Capacitor issue. We don't do anything to XHR/fetch, and there is nothing we can do about it. You can wait for the HTTP plugin 
https://github.com/ionic-team/capacitor/pull/2495

**Comment by alexsasharegan** [comment]
Thank you for taking some more time to help me! I will look into this more!

**Comment by kirstenfrager** [comment]
@alexsasharegan did you manage to resolve this issue? I am facing the same and am stumped.

**Comment by alexsasharegan** [comment]
@kirstenfrager, my team built an internal proxy api to relay headers to the capacitor client. This also allowed us to set x-cookie headers that the proxy server patches into the real cookie header before passing the request along to our backend. This has the advantage of tying into our existing cookie based auth. I don’t know what’s going on with the capacitor chain to cause us this issue, but I just don’t have the bandwidth to figure it out, so this presented as the solution we were most comfortable with maintaining.
