### ISSUE TITLE
bug: iOS - playing large video from filesystem freezes the app

### ISSUE THREAD

**Issue by lucasfernog** [ionic-team/capacitor#2634]
# Bug Report

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 1.5.1

  @capacitor/core: 1.5.1

  @capacitor/android: 1.5.1

  @capacitor/ios: 1.5.1

Installed Dependencies:

  @capacitor/cli 1.4.0

  @capacitor/core 1.4.0

  @capacitor/android 1.4.0

  @capacitor/ios 1.5.0

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

After downloading a large file (more than 1GB) and saving it to the disk, trying to play it with the HTML5 video player freezes the app.

I'm using the `convertFileSrc` function to convert the local file URI to the one that Capacitor handles through its server.

Playing a small video file works fine, and playing a remote video works fine too.

## Expected Behavior

The video should play the same way it does when the video URL is remote.

## Sample Code or Sample Application Repo
```js
const { convertFileSrc } = require('@capacitor/core').Capacitor
const fileUri = convertFileSrc(uri)
this.player = videojs(this.$refs.video, {
  playbackRates: [0.25, 0.5, 1, 2, 4]
})
this.player.src(fileUri)
```

## Reproduction Steps

- Download a large video file
- Get its file URI with `Filesystem.getUri`
- Convert the URI with `convertFileSrc`
- Load the video into the player
- Play the video, it'll freeze the app

## Other Technical Details

`npm --version` output: 6.13.6

`node --version` output: 13.8.0

`pod --version` output (iOS issues only): 1.84

## Other Information

When the app freezes, XCode breaks on the CAPAssetHandler class, on the line where it says `urlSchemeTask.didReceive(data)` (LOC 69).
I assume this happens because the Capacitor server tries to load the entire file into memory, instead of streaming it.
* This issue doesn't happen on Android *

**Comment by jcesarmobile** [comment]
Sadly there is nothing we can do about it since the requests don't have range headers, I reported it to Apple a few months ago.
https://bugs.webkit.org/show_bug.cgi?id=203302

**Comment by lucasfernog** [comment]
@jcesarmobile that's interesting... do you know why it works on Cordova but not on Capacitor?

**Comment by jcesarmobile** [comment]
It depends on which cordova plugin you use, if using `cordova-plugin-ionic-webview` you'll have the same issue, if you use cordova-ios 6 without any plugins, you'll have the same issue too.
If you use `cordova-plugin-wkwebview-engine` there is no issue because it's served from file protocol

**Comment by gsfioravanti** [comment]
The issue is happening with .mp4 files.

How have others worked around this issue?

**Comment by jbgtmartin** [comment]
Yes I would be interested in knowing how you worked around the issue.
In my case the users download ~30 min videos, which weigh around 200MB, that they play locally using HTML5 video tag.

As explained [here](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/378#issuecomment-511609679), the issue is that WKWebView doesn't send Range header, so the video player loads the whole video into memory instead of only the beginning, leading to a crash for large video.

The only workarounds I see for now are :
- Play the videos from a remote URL (not ok for us because the videos need to work offline)
- Split the videos into smaller videos, and play them one after the other
- Use Ionic with Cordova and [cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview/) **v2** (current is v5) instead of Capacitor. More details [here](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/378#issuecomment-546252969) on why this stopped working after v2.

Any other ideas? I chose the third one but I'm really frustrated to not be able to use Capacitor just because of this...
