### ISSUE TITLE
bug: Camera API - Image duplicated to user device on `saveToGallery`

### ISSUE THREAD

**Issue by wooliet** [ionic-team/capacitor#2644]
# Bug Report

We use the default Camera behavior to allow the user to either select an existing image from their phone, or user their camera to take a new image.

We are also setting the `saveToGallery` option to "true" so that, if they take a photo, it will be saved to their device.

Unexpectedly, when the user selects an existing image from their phone, that image is duplicated to the device.

**This does not appear to happen on Android.**

## Capacitor Version
`npx cap doctor` output:
```
Latest Dependencies:

  @capacitor/cli: 1.5.1

  @capacitor/core: 1.5.1

  @capacitor/android: 1.5.1

  @capacitor/ios: 1.5.1

Installed Dependencies:

  @capacitor/cli 1.5.1

  @capacitor/core 1.5.1

  @capacitor/android 1.5.1

  @capacitor/ios 2.0.0-beta.1
```
## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

1. User wants to submit a photo
1. User presented with options "From Photos" or "Take Picture"
1. User selects "From Photos" and picks an image already on their device
1. The image is immediately duplicated on their device

## Expected Behavior

1. User selects "From Photos" and no duplicate is created
1. User selects "Take Picture" and image taken is copied to the device

## Other Technical Details

`pod --version` output (iOS issues only):  1.8.4

## Other Information

Previously reported here: https://github.com/ionic-team/capacitor/issues/2076#issuecomment-551574060

**Comment by jcesarmobile** [comment]
Save to gallery saves to gallery, that’s the expected behavior

**Comment by dlbass** [comment]
I am experiencing the same behaviour as wooliet describes, however I see this only happening on my iOS builds. The reason my group chose to use Capacitor is to maintain the same UX for all platforms, and a perk of that was very little code difference between platforms.

Since it is expected bahviour for the `saveToGallery` to save any image used through the Capacitor camera to my users' galleries, it seems that it should be working the same in all environments. Android users are not having the images they select from their galleries saved back to their gallery through our app, but iOS users are.

**Comment by jcesarmobile** [comment]
Then that's a bug on the Android implementation, please, report a separate issue

**Comment by jcesarmobile** [comment]
We talked internally about it and we are going to change the behavior
See https://github.com/ionic-team/capacitor/pull/2671
