### ISSUE TITLE
bug: Android app crashes during startup

### ISSUE THREAD

**Issue by dlehmhus** [ionic-team/capacitor#2652]
# Bug Report

## Capacitor Version
Installed Dependencies:
  @capacitor/ios not installed
  @capacitor/cli 1.5.2
  @capacitor/core 1.5.2
  @capacitor/android 1.5.2

## Affected Platform(s)

- [x ] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
During app startup, the app crashes once, starts again and works fine from thereon. You don't notice the app crashing, rather than the splash screen turns completely white for a moment and comes back before revealing the app.

## Expected Behavior
The app starts without crashing.

## Sample Code or Sample Application Repo
https://github.com/dlehmhus/capacitor-android-example

## Reproduction Steps

1. `npm i && npm run build && npx cap open android`
2. Start the App from Android Studio

## Other Technical Details

`npm`: 6.12.1
`node`: v12.13.1
`device`: Samsung SM-G950F
`Android`: 8.0

## Other Information
The error part of the stacktrace starts with
`Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>`
The whole stacktrace can be found here: https://github.com/dlehmhus/capacitor-android-example/blob/master/stacktrace.txt

**Comment by mcking49** [comment]
Also having the same issue, Splash screen also "flickers" (different issue, but could be related)

**Comment by jongbonga** [comment]
also experience crash with capacitor 2.0.0

**Comment by stripathix** [comment]
Remove the android folder and add it again. That fixes it for me. Also better update to the latest capacitor

**Comment by jcesarmobile** [comment]
I can't reproduce the crash, but I see those `OnUnhandledKeyEventListenerWrapper`.
That is a problem in Android X support libraries and has been fixed recently.
Update to Capacitor 2 following this guide https://capacitor.ionicframework.com/docs/android/updating#from-1-5-1-to-2-0-0
but update `androidxAppCompatVersion` to `1.3.0-alpha01` or `androidxCoreVersion` to `1.4.0-alpha01` instead of to the versions in that guide.
