### ISSUE TITLE
question: Update from PhoneGap

### ISSUE THREAD

**Issue by Maxou44** [ionic-team/capacitor#2664]
# Question

Hello here 😀

I'm trying to update a legacy app from PhoneGap/Cordova, if I switch to Capacitor when I will deploy the new app on the store, can the new "Capacitor" version have access to localStorage set from PhoneGap/Cordova version?

If no, what migration advices can you provide me?

Thanks for your answers, 😘
Maxime

**Comment by jcesarmobile** [comment]
Please, don't use github issues to ask questions, just to report issues.
For questions you can ask on the [forum](https://forum.ionicframework.com/), [slack](https://getcapacitor.herokuapp.com/) or[ stack overflow ](https://stackoverflow.com/) using capacitor tag.

But answering your question, it’s not directly accesible since the data is tied to the “url” (scheme + domain) and capacitor uses capacitor://localhost, while your current app probably uses file://.
But the data is still there and there are plugins that might be able to migrate the data.
