### ISSUE TITLE
Plugin com-badrit-base64 not compatible with iOS

### ISSUE THREAD

**Issue by Sh1n1x** [ionic-team/capacitor#2702]
I have see this post #2453 and i confirm that the plugin com-badrit-base64 isn't compatible with capacitor on iOS (seems to be working with Android but i've not tested now).

Here's the console log from Xcode:
```
[warn] - Native: tried calling Base64.encodeFile, but the Base64 plugin is not installed.
[warn] - Install the Base64 plugin: 'ionic cordova plugin add com-badrit-base64'
```

And when i run `ionic cap sync` after `npm install com-badrit-base64`, i can see on the log:
```Updating iOS native dependencies with "pod install" (may take several minutes) in 7.87s
  Found 7 incompatible Cordova plugins for ios, skipped install
    com-badrit-base64 (0.2.0)```

**Comment by jcesarmobile** [comment]
Can you provide a sample app using it?

**Comment by Sh1n1x** [comment]
> Can you provide a sample app using it?

Sure !

Here's the sample app: https://github.com/Sh1n1x/Capacitor-bug-Base64-plugin

Thank you @jcesarmobile

**Comment by jcesarmobile** [comment]
The main problem is the plugin is abandoned. It just uses a canvas to do the conversion, so you don't really need a plugin for that, the needed javascript code is here https://github.com/hazemhagrass/phonegap-base64/blob/master/www/Base64.js#L14-L28.

But if you still want to use the plugin, Capacitor considers it not compatible because it doesn't have an ios platform tag, so you can easily fix that by adding this to the plugin.xml
```
<platform name="ios">
</platform>
```
Also make sure it has a dependency to the file plugin since it relies on it and the 0.2.0 version doesn't include it, they have it in master branch, but never released it because it's abandoned. Should look like `<dependency id="cordova-plugin-device"/>`
