### ISSUE TITLE
bug: Browser plugin in iOS-popover presentation freezes app after dismiss

### ISSUE THREAD

**Issue by chriswep** [ionic-team/capacitor#2711]
Capacitor Version: 2.0.0

## Affected Platform(s)
- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
If opening an URL via the Browser plugin on iOS (13.4) with `presentationStyle: 'popover'`, the app freezes after dismiss of the Browser modal. 
The Safari remote inspector shows the opened webview and in can be inspected after dismissal. This indicates that something is not properly destroyed after dismiss.

`presentationStyle: 'fullscreen'` does not have this issue.

## Expected Behavior
Remove the Webview / Browser-modal completely after dismiss of the popover

**Comment by chriswep** [comment]
thanks @jcesarmobile that was quick!

as far as i see, you disabled the popover-style for everything but iPads? On iPhones i used this to achieve the iOS13 modal style. I manually copied your changed code without that restriction, and it works fine on iPhones.

**Comment by jcesarmobile** [comment]
In which devices does the popover works? I thought it was iPad only, doesn’t show different Style on my iPhone X

**Comment by chriswep** [comment]
on iPhone it opens an animated modal card (iOS13 style) instead of a fullscreen window

**Comment by jcesarmobile** [comment]
Ah, my device is on iOS 12.

**Comment by jcesarmobile** [comment]
Can you test this code with your change in a real iPhone?

```
async openBrowserPop() {
    await Browser.open({ url: 'https://www.google.com/', presentationStyle: 'popover' });
    setTimeout(() => {
      Browser.close();
    }, 5000);
  }
```
The Browser window should close itself after 5 seconds.

The point of the tmpWindow is because some modal presentations were frozing the javascript execution, so the close was never called.
If I let the popover on my iOS 12 iPhone it still gets frozen, and I don't have an iOS 13 iPhone (I could update, but then I can't go back on testing on iOS 12).
But maybe the iOS 13 popover doesn't freeze the javascript execution and we can allow the popover there.

**Comment by chriswep** [comment]
i don't see any freezing on a real iPhone iOS13. 
on iOS12 simulator it does freeze as soon as the browser opens.

**Comment by chriswep** [comment]
@jcesarmobile do you want a new issue for this (enabling popover on iOS13-iPhone)?

**Comment by mchambaud** [comment]
on iOS14 it crashes you **open + dismiss + open again**

works fine when using fullscreen
