### ISSUE TITLE
bug: In app browser squashes app when keyboard is used

### ISSUE THREAD

**Issue by oliverandersencox** [ionic-team/capacitor#2750]
Updated to the most recent Capacitor 2.0.1.

My application uses the in app browser for social authentication.

In order for the app to be accepted to the app store, the navigation during authentication must be within the app, and therefore I use the in app browser with either 'pop over' or 'fullscreen'. Before the update everything worked fine, however now, if I open the keyboard whilst the browser modal is up, or in fullscreen mode, the application is squashed up to make way for the keyboard.

However when redirected back to the app, the app height never readjusts and so the app is squashed at half height. 

Is there a way to resize it back or any further info as to why this is now happening?

`     await Browser.open({ url, presentationStyle: fullscreen ? 'fullscreen' : 'popover' });`

**Comment by jcesarmobile** [comment]
Please, don't delete the template when reporting issues, it's not the first time I tell you, but you keep ignoring me. The template is there for a reason and the lack of information makes it hard to reproduce. 
In this case I can't reproduce, so I'm going to close.
In the next issue you report, please, don't delete the template and provide a sample app that helps reproducing.

**Comment by dabaaaz** [comment]
We get the same issue there : [#2955 ](url)

Please @jcesarmobile re-open or one of them issues because the problem looks to be in Capacitor.

If you want I have a third video which explains it.
I've made a simple browser with WKWebView. Inside I called my code but everything is OK (without Capacitor) : [https://streamable.com/sglxzn](https://streamable.com/sglxzn)
