### ISSUE TITLE
feat: Server Side Rendering

### ISSUE THREAD

**Issue by rgolea** [ionic-team/capacitor#2758]
# Feature Request

## Describe the Feature Request

I really love the capacitor project but I find myself having to replace in angular/ionic all the plugins and the imports so it can adjust to server-side rendering (stuff like `window` or `window.localStorage`) are not supported on server-side. This is not an issue on devices but if it's a full PWA, I believe it would be awesome to have it.

## Platform Support Requested

- [ ] Android
- [ ] iOS
- [ ] Electron
- [x] Web

**Comment by jcesarmobile** [comment]
As far as I know, server side rendering is working (well, it's broken on latest version because of https://github.com/ionic-team/capacitor/issues/2850, but wasn't an issue when you created this issue and will be fixed in next release)

So if you have specific issues, report them in a separate issue providing a sample application.

**Comment by rgolea** [comment]
@jcesarmobile I didn't mean the part on Ionic. I meant capacitor web dependencies like `Storage`, etc that uses `window.localStorage`. Maybe just use `window-ssr` to make sure the api's don't give a null check error and that they at least return a null or an undefined?
