### ISSUE TITLE
bug: cordova plugin pods are not installed

### ISSUE THREAD

**Issue by ryaa** [ionic-team/capacitor#2772]
# Bug Report

I installed this plugin https://github.com/SonoIo/cordova-plugin-salesforce-snapins and getting the below error when trying to build. it seems the problem seems to be that the required pods have not been installed.

## Capacitor Version

`npx cap doctor` output:
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/cli 1.5.1

  @capacitor/ios 1.5.1

  @capacitor/core 1.5.1

  @capacitor/android 1.5.1

[success] Android looking great! 👌
  Found 4 Capacitor plugins for ios:
    cordova-plugin-android-fragmentactivity (0.0.6)
    cordova-plugin-cocoapod-support (1.6.2)
    cordova-plugin-salesforce-snapins (1.0.4)
    cordova.plugins.diagnostic (5.0.1)
[success] iOS looking great! 👌

## Affected Platform(s)

- [ ] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior

After the plugin is installed and i try to build in XCode i'm getting the below error
![Screenshot 2020-04-15 at 14 47 16](https://user-images.githubusercontent.com/3608222/79337026-70be5880-7f2d-11ea-87c5-20a4eecc05b5.png)

## Expected Behavior

The app should build and run successfully

## Reproduction Steps

1) create new ionic 5/angular/capacitor project and install this plugin  https://github.com/SonoIo/cordova-plugin-salesforce-snapins and try to build

## Other Technical Details

`npm --version` output:
6.14.4

`node --version` output:
v12.16.1

`pod --version` output (iOS issues only):
1.7.5

## Other Information

Here is the build error details
![Screenshot 2020-04-15 at 14 47 16](https://user-images.githubusercontent.com/3608222/79337253-d4e11c80-7f2d-11ea-8894-2e7230170374.png)

**Comment by ryaa** [comment]
The problem seems to be that this https://github.com/SonoIo/cordova-plugin-salesforce-snapins plugin depends on https://github.com/blakgeek/cordova-plugin-cocoapods-support to install the required pods and the latter cordova-plugin-cocoapods-support cordova plugin runs **after_prepare** hook to do its job and install the dependencies. Since capacitor does not support cordova hooks this is expected behaviour and not a capacitor problem.

I assume that this issue can be closed (if someone confirms the above). Thank you.

**Comment by jcesarmobile** [comment]
It's not because of the hooks, but because of it uses a custom syntax for pod dependencies that Capacitor doesn't understand.
Not sure why they use that plugin, cordova has supported CocoaPods for a long time, they should update to use the podspec tag
https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#podspec-ios

I've created a feature request issue to read the syntax that plugin uses https://github.com/ionic-team/capacitor/issues/2773
Also noticed that Capacitor doesn't support sources for pods, which that plugin would need. created this issue for that https://github.com/ionic-team/capacitor/issues/2774

going to close as incompatible plugin
