### ISSUE TITLE
bug: GPS Location not available issue 

### ISSUE THREAD

**Issue by JoshuvaGeorge03** [ionic-team/capacitor#2800]
# Bug Report

## Capacitor Version

`
Latest Dependencies:

  @capacitor/cli: 2.0.1

  @capacitor/core: 2.0.1

  @capacitor/android: 2.0.1

  @capacitor/electron: 2.0.1

  @capacitor/ios: 2.0.1

Installed Dependencies:

  @capacitor/electron not installed

  @capacitor/cli 2.0.1

  @capacitor/core 2.0.1

  @capacitor/android 2.0.1

  @capacitor/ios 2.0.1
`

## Affected Platform(s)

- [x] Android
- [x] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
When I get the location using Geolocation API, I am getting this below error.
`
Object
message: "location unavailable
`

## Expected Behavior
When I fetch for the location I want it to return location

## Sample Code or Sample Application Repo
`
 const locationInfo = await Geolocation.getCurrentPosition();
`

## Other Technical Details
`
Ionic:

   Ionic CLI                     : 6.1.0 (C:\Users\Joshuva\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.900.7
   @angular-devkit/schematics    : 9.1.1
   @angular/cli                  : 9.1.1
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.0.1
   @capacitor/core : 2.0.1

Utility:

   cordova-res                          : 0.11.0
   native-run (update available: 0.3.0) : 0.2.2

System:

   NodeJS : v12.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.7
   OS     : Windows 10

`

**Comment by jcesarmobile** [comment]
I can’t reproduce, make sure location is enabled in the device you tested.

**Comment by grallc** [comment]
I'm still having this issue. 
It's really weird, since it's only sometimes on some phones.
It works perfectly on my Xiaomi Mi9, but sometimes, when I open the application or unlock my phone with the app opened, it tells me "location unavailable" on my Xiaomi A2 Lite.

The geolocation is off course enabled and the application has the permission to access it, since it sometimes works.

```Ionic:

Ionic CLI : 5.14.16
Ionic Framework : @ionic/react 5.1.1

Capacitor:
@capacitor/core : 2.0.2

System:
NodeJS : v10.16.3
npm : 6.14.4
OS : OSX 10.15.5```

Do you have an idea how to fix ? My entire app is based on the geolocation so I need it working perfectly. 

Thanks !
