### ISSUE TITLE
docs: Importing CameraSource and available events to listen to are not documented

### ISSUE THREAD

**Issue by snow-drop** [ionic-team/capacitor#2826]
Good day!

I am new to Capacitor and is playing around with the Camera plugin. I think it would be helpful for first time users to know how to import `CameraSource` as it is not documented on how to import it. It took me half an hour to find an example source code showing how to import it. I guess the same is through with `CameraDirection`.

Another one is the the list of available events that a user could listen to. So far I can't find a documentation for the list of available events that Camera plugin offers. I also think this will be helpful for first time users and for other people who want to integrate this function to their existing apps.

**Comment by jcesarmobile** [comment]
The example uses `CameraResultType` and shows how to import it, then there is a link to the ionic camera sample app https://capacitor.ionicframework.com/docs/guides/ionic-framework-app/ that has a `CameraSource`.
But all the imports are the same, you just import them from `'@capacitor/core'`. I don't think there is a need to show how to import every exported property since they are used the same way.

About the events, camera doesn't have any.
