### ISSUE TITLE
feat: Custom splash screen for dark theme users

### ISSUE THREAD

**Issue by jabczyk** [ionic-team/capacitor#2947]
# Feature Request

## Describe the Feature Request

Capacitor should support two versions of the splash screen by default - light and dark. Proper variation should be shown based on the user's preferred color scheme.

## Platform Support Requested

- [X] Android
- [X] iOS
- [ ] Electron
- [ ] Web

## Describe Preferred Solution

Splash screen should be chosen based on the preferred color scheme by default and an additional method (like `SplashScreen.setTheme('light' | 'dark')` should be implemented to change it programmatically.

## Additional Context

Dark themes are gaining popularity and users expect them to be available in every app. Developers should be able to easily implement dark themes to every part of the app.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for👍  reactions to gauge interest.

**Comment by mhartington** [comment]
This should be supported by the native platforms. Xcode allows you to provide a launch image for both light/dark, light only, or dark only. 

All that is needed is for developers to provide launch images for the respected modes. Don't really think a new API is needed here since the system handles it automatically. 

![Screen Shot 2020-05-18 at 12 57 27 PM](https://user-images.githubusercontent.com/2835826/82239668-23a41c80-9907-11ea-8530-2effb15cba69.png)

**Comment by jabczyk** [comment]
Thanks for the useful info @mhartington! It's worth noting that it works on Android as well: https://stackoverflow.com/questions/13735675/change-drawable-based-on-theme

The only downside is it cannot be changed programmatically, so if the user's device theme is light but the in-app theme is set to dark, the user still sees a light splash screen.
Being able to control it better is not a necessary feature, but it's nice to have.
