### ISSUE TITLE
Framework not being found in Cordova plugin - Ionic React 

### ISSUE THREAD

**Issue by minenkod** [ionic-team/capacitor#3047]
Hi,

-I'm using React Ionic
-Using a Cordova Plugin that contains a frameworks

-Adding the framework with npm install ../my_framework && npx cap sync 

I get the following error: 

" Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ZapparEmbed", referenced from:
      objc-class-ref in ZapparPlugin.o
  "_OBJC_CLASS_$_ZapparEmbedOptions", referenced from:
      objc-class-ref in ZapparPlugin.o" 

The files are all there but still cannot locate it. I'm having no issues on Android and with Angular I have both IOS and Android working. The plugin is not the issue here. Something is happening where Capacitor cannot find my framework. I have tried to set my Search framework path to exactly where the framework is. Additionally ive tried to manually add my framework both on Pods and App workspace. 

I'm considering create a native bridge between both IOS native and javascript without the use of plugins. Where could I find documentation where this is done? I really want to avoid that route as there has to be a simpler solution to my problem described. 

Any suggestion will be appreciated

**Comment by jcesarmobile** [comment]
please, when creating bug reports don't delete the template, the requested information is important to help reproducing the issue.

it's not possible to reproduce with the provided information, please, if you create a new issue, provide all the information and a sample app since zappar plugin is not public, so I can't test it.
