### ISSUE TITLE
feat: Open Native App Permissions

### ISSUE THREAD

**Issue by hatsantos** [ionic-team/capacitor#3122]
### Description
A way in Capacitor to be able to open the app permissions. Maybe the Permissions plugin could handle the openning of the native app settings to setup the app permissions.

This will be very helpfull to guide de user to update de app permisisons settings if he wrongly removed the permissions concent or just want to change it. 

If this methos exist, We could provid in the APP UI a quick access to the permissions settings.

### Platform(s)
Android and iOS.

### Preferred Solution
I think the permission plugin would be a good place to have a generic method to open the native permissions settings page, something like: OpenNativePermissions() .

**Comment by bolivir** [comment]
Im missing this feature also, migration from the diagnostic cordova plugin where this feature is available.

**Comment by jcesarmobile** [comment]
Closing as won't do since the permission plugin no longer exists and this repository no longer has plugins.

Each plugin that needs permissions will need to implement this if interested or a new plugin will have to be created.

LocalNotifications plugin 6.x will have `changeExactNotificationSetting()` for opening the exact notifications settings screen that appear if using the exact notification permission.
