### ISSUE TITLE
Embedded Capacitor

### ISSUE THREAD

**Issue by imhoffd** [ionic-team/capacitor#3182]
Allow for the use case of embedding Capacitor inside native apps.
Allow for multiple instances of Capacitor in an app (not necessarily concurrently).

**Comment by fkirc** [comment]
I think that "Embedded Capacitor" already works today, but there are still some minor glitches like https://github.com/ionic-team/capacitor/pull/3280.
Nevertheless, it would be nice to have some additional documentation and tested sample code for embedded usage.

**Comment by dwieeb** [comment]
@fkirc Great to hear. Please follow Capacitor 3 development! We will be doing dev releases once development picks up a bit. Your feedback would be very valuable.

**Comment by JovanShandro** [comment]
Is there any plan to add more documentation into how to do this embedding? We are currently looking for possible ways to embed parts of a Capacitor app on a native application. I saw in #3280 that a class called BridgeFragment exists, but could not manage to find any example of how to use it, and also didn't manage to find a way of how to achieve this on Ios. Is this still a feature that is under development, or is it just lacking documentation?

**Comment by fkirc** [comment]
`BridgeFragment` is already working and you can embed it into a native Android app like any other fragment (e.g. inflate it from an XML layout).

However, there are still some rough edges because this is not yet an official feature. 
For example, `BridgeFragment` seems to have a bug that makes `capacitor.config.json` partially broken. This bug can be easily fixed with a one-line change, but my point is that you should not trust the current `BridgeFragment` implementation.
If you demand a highly customized configuration, then you might need to write your own BridgeFragment (which is doable because the relevant code is short and easy to read).

**Comment by fkirc** [comment]
For iOS: I managed to embed Capacitor into an existing native iOS app by embedding `CAPBridgeViewController.swift`.
In my case, I embedded `CAPBridgeViewController.swift` into an existing Storyboard via raw XML-editing in Xcode, but I am pretty sure that there are also other ways to do it.

**Comment by carlpoole** [comment]
Allow embedded capacitor to load a specific path on an instance of embedded capacitor as described here: https://github.com/ionic-team/capacitor/pull/3405.

**Comment by dwieeb** [comment]
For those following this issue, I removed the 3.0.0 milestone because it may be confusing. We are laying the foundation for "Embedded Capacitor" with the 3.0.0 release, but there will still be much work to do. Thanks for your patience!

**Comment by jthoms1** [comment]
Closing this enhancement request.
