### ISSUE TITLE
Upgrading XML parser in cli

### ISSUE THREAD

**Issue by amitguptagwl** [ionic-team/capacitor#3206]
### Description

As we're currently using xml2js, I wanted to request upgrading to [fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser) due to performance;

file size | fxp 3.0 validator (rps) | fxp 3.0 parser (rps) | xml2js 0.4.19 (rps)
-- | -- | -- | --
1.5k | 16581.06758 | 14032.09323 | 4615.930805
1.5m | 14918.47793 | 13.23366098 | 5.90682005
13m | 1.834479235 | 1.135582008 | -1
1.3k with CDATA | 30583.35319 | 43160.52342 | 8398.556349
1.3m with CDATA | 27.29266471 | 52.68877009 | 7.966000795
1.6k with cdata,prolog,doctype | 27690.26082 | 41433.98547 | 7872.399268
98m | 0.08473858148 | 0.2600104004 | -1

-1 indicates the error.

**Comment by dwieeb** [comment]
I doubt parsing XML is the bottleneck of the CLI's `copy` and `update` commands. It would be more useful if benchmarks were adjusted for distinct operations in Capacitor CLI commands so we can identify what to address for optimal performance. If CLI performance is important to you, I'd be happy to look at operation-based benchmarks and proposals or PRs for improvement.

**Comment by jcesarmobile** [comment]
Maybe if it could fix https://github.com/ionic-team/capacitor/issues/586 we could consider switching.

At the moment we use `xml2js` for reading cordova plugins `plugin.xml` file and convert it to a JSON object that we use in several places, and also to generate the `config.xml`.

I used `xml2js` because it was already installed when I implemented that functionality and did the job fine.

I've done a quick test of fast-xml-parser, and when converting the `plugin.xml` to JSON, in platform tags I can't get the name attribute. 
```
<platform name="ios">
</platform>
```
Also, a lot of other needed elements are empty.
I might not have used the proper options on the object generation, as I said, it was just a quick test, but doesn't look like it works as we need.

**Comment by amitguptagwl** [comment]
FXP comes with many options, if you set `ignoreAttributes: false` then you'll get

```js
{
    "platform": {
        "@_name": "ios"
    }
}
```

Of course, the prefix to an attribute name or group them under a single nested node can again be controlled by the options.
