### ISSUE TITLE
Support release builds from CLI

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#324]
We will need to do CI/Cloud builds for apps in Ionic, should we support running `xcodebuild`/`gradle` easily from the CLI?

```
npx cap build
```

**Comment by jcesarmobile** [comment]
Is the CI something we control? we can configure the CI to build the native project

**Comment by mlynch** [comment]
Yea, but just CI's in general, we could make it easier to build the app from the command line

**Comment by janpio** [comment]
_fastlane_ has very good build support for both Android and iOS.

**Comment by zarko-tg** [comment]
Major showstopper for us as we've almost never had to open/use any IDE, having a well functioning build/release setup/process via command line.

**Comment by ptitjes** [comment]
@zarko-tg You can do `(cd android/ && ./gradlew assembleRelease)` for Android.
See for instance:
- https://github.com/cabasvert/cabasvert/blob/master/packages/client/scripts/tools.js#L83
- https://github.com/cabasvert/cabasvert/blob/master/packages/client/scripts/tools.js#L127

You can do something like `xcodebuild -scheme App build` for iOS.
But I can't tell exactly as I didn't pay Apple's dime yet.

**Comment by wilsolutions** [comment]
Hi, I've tried the steps above for Android, it did generate the expected .apk file however if fails when I try to install in the device.
This is the error message that I got from logcat:
`com.google.android.packageinstaller/com.android.packageinstaller.InstallFailed (has extras)`

- iOS:
`xcodebuild -workspace App.xcworkspace -scheme App clean archive -configuration debug -sdk iphoneos -archivePath App.xcarchive`

It fails with:
`AppDelegate.swift:2:8: error: no such module 'Capacitor'`


Any thoughts about it?
tkx

**Comment by jcesarmobile** [comment]
Did you run it from `ios/App/` folder?

I just copy/pasted your command in one random Capacitor project and worked fine 

You can also try to run `pod install` from `ios/App/` first, but shouldn't be necessary as `npx cap update ios` already run it

**Comment by wilsolutions** [comment]
Hola @jcesarmobile, thank you for the feedback.
Yes, I did run from the `ios/App` folder.

From the `ios/App`:
1. `✗ pod install`
Ignoring nokogiri-1.8.4 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.4
Ignoring unf_ext-0.0.7.5 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.5
Analyzing dependencies
Fetching podspec for `Capacitor` from `../../node_modules/@capacitor/ios`
Fetching podspec for `CapacitorCordova` from `../../node_modules/@capacitor/ios`
Fetching podspec for `CordovaPlugins` from `../capacitor-cordova-ios-plugins`
Downloading dependencies
Using Capacitor (1.0.0-beta.7)
Using CapacitorCordova (1.0.0-beta.7)
Using CordovaPlugins (1.0.0-beta.11)
Using GCDWebServer (3.4.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 4 total pods installed.

2. `✗ xcodebuild -workspace App.xcworkspace -scheme App clean archive -configuration debug -sdk iphoneos -archivePath App.xcarchive`

AppDelegate.swift:2:8: error: no such module 'Capacitor'
import Capacitor
       ^
** ARCHIVE FAILED **
The following build commands failed:
    CompileSwift normal armv7 /Users/wils/_work/projects/prototype01/ios/App/App/AppDelegate.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    CompileSwift normal arm64 /Users/wils/_work/projects/prototype01/ios/App/App/AppDelegate.swift
(3 failures)

tkx

**Comment by wilsolutions** [comment]
It works!

I have just created a new project and it works!

So, looks likes some discrepancy in my previous project, after reading jcesarmobile message I decided to create a new project and voilà!

tkx

**Comment by Rodrigo54** [comment]
consider using @bazelbuild to compile for ios, android and electron
it would be better to centralize everything in a single tool instead of worrying about Gradle and CocoaPods

**Comment by Coly010** [comment]
+1 Bump

**Comment by robingenz** [comment]
Any updates?

**Comment by Heerschop** [comment]
I have created a pull request [#4403](https://github.com/ionic-team/ionic-cli/pull/4403) to make the open of the development IDE optional. This will help using `ionic capacitor` from the CLI, especially when you what to use the `--livereload` option. 

Currently, if you what to use livere load from the CLI. You can not use the `ionic capacitor run <platform> --livereload` command, because it will always start the corresponding IDE. So you have to write custom scripts that will update the `capacitor.config.json` file with the correct information needed for live reload to work. The pull request can make this use case simpler.

**Comment by Heerschop** [comment]
The  pull request [#4403](https://github.com/ionic-team/ionic-cli/pull/4403) has just been merged. Now you can use the `--no-open` option in the ionic cli version 6.7.0.

**Comment by Heerschop** [comment]
Created a pull request [#4417](https://github.com/ionic-team/ionic-cli/pull/4417)  for adding hooks and environment variables for the hook shell scripts.

Added two ionic capacitor [CLI Hooks](https://ionicframework.com/docs/cli/configuration#hooks)
- `ionic:capacitor:run` : executed before capacitor open is executed
- `ionic:capacitor:build` : executed before capacitor open is executed

Example of the generated environment variables
``` bash
IONIC_CLI_HOOK_CTX_NAME=capacitor:build
IONIC_CLI_HOOK_CTX_PLATFORM=android
IONIC_CLI_HOOK_CTX_PROJECT=app
IONIC_CLI_HOOK_CTX_VERBOSE=false
```
This pull request should simplify the usage of `ionic capacitor` from the CLI and in a CI/CD environment.

**Comment by Coly010** [comment]
> ```shell
> IONIC_CLI_HOOK_CTX_PROJECT=app
> ```

I'm guessing this will allow for multi-app workspaces support?

Also, when you say build, do you mean building the JS App, or the native binaries?

My concerns, if it's the latter, are around code signing for Android and provisioning profiles for iOS, as well as building debug or release versions of the native binary.

**Comment by Heerschop** [comment]
This change includes two additional [CLI hooks](https://ionicframework.com/docs/cli/configuration#hooks) for ionic. Is implemented the same way as the already four existing hooks.
The value of the `IONIC_CLI_HOOK_CTX_PROJECT` variable will change depending on the project selected. So yes it will support multi-app workspaces :-)

Example:
``` bash
➜  test-cli-app git:(master) ✗ ionic capacitor build android --project=myProject --prod 

Hook build-before.sh: scripts/build-before.sh
IONIC_CLI_HOOK_CTX_CONFIGURATION=production
IONIC_CLI_HOOK_CTX_CORDOVAASSETS=true
IONIC_CLI_HOOK_CTX_ENGINE=capacitor
IONIC_CLI_HOOK_CTX_NAME=build:before
IONIC_CLI_HOOK_CTX_PLATFORM=android
IONIC_CLI_HOOK_CTX_PROJECT=myProject
IONIC_CLI_HOOK_CTX_TYPE=angular
IONIC_CLI_HOOK_CTX_VERBOSE=false
```

**Comment by Heerschop** [comment]
The pull request [#4417](https://github.com/ionic-team/ionic-cli/pull/4417) has just been merged. As of version [6.9.0](https://www.npmjs.com/package/@ionic/cli) of the Ionic CLI you can use the new `ionic:capacitor:run:before` and `ionic:capacitor:build:before` hooks.

**Comment by pwespi** [comment]
The quasar framework (https://quasar.dev) supports Capacitor and they implemented building from the CLI. This is how they do it: https://github.com/quasarframework/quasar/blob/dev/app/lib/capacitor/index.js

Maybe it can be taken as an inspiration and be implemented in the Capacitor CLI as well?

**Comment by Coly010** [comment]
@pwespi very good find. I like it, even if this cannot be implemented into Capacitor itself, it's a good reference for anyone that needs to set up a build pipeline

**Comment by dwieeb** [comment]
Some thoughts on building from the CLI: https://github.com/ionic-team/capacitor/discussions/3224#discussioncomment-35214

**Comment by elvisgraho** [comment]
I dont get it. The docs suggest generating the Android project using capacitor. But when I want to build it, the docs suggest in using cordova, and the whole thing does't work!!!!!!!!

**Comment by jcesarmobile** [comment]
What docs are you referring to?
Capacitor docs don't tell you to use Cordova anywhere.

Capacitor doesn't support building from the CLI at the moment, you have to use gradle on Android or xcodebuild on iOS (or some multi platform tool such as fastlane)

**Comment by elvisgraho** [comment]
I was referring to Ionic doc's.
1. Android Dev Capacitor https://ionicframework.com/docs/developing/android
2. Android Build Prod Cordova: https://ionicframework.com/docs/cli/commands/cordova-build

**Comment by infacto** [comment]
Capacitor should primary build on CLI (e.g. Android SDK Tools). The current behavior is not CI friendly. Not even for humans. Why? 😢

**Comment by dwieeb** [comment]
Let's keep things constructive in accordance with our [Code of Conduct](https://github.com/ionic-team/capacitor/blob/main/CODE_OF_CONDUCT.md).

> Then what is it for?

Capacitor is first and foremost a cross-platform native runtime for web apps. The primary purpose is to provide a translation layer from web app to native platform. One of the philosophical [differences between Capacitor and Cordova](https://capacitorjs.com/docs/cordova#differences-between-capacitor-and-cordova) is that Capacitor doesn't try to abstract away the native platforms, it embraces them. The platforms in Capacitor projects are true native projects and considered source artifacts, not build artifacts. They're as much a part of your app as the JS you write.

You're encouraged to use Gradle for Android and `xcodebuild` for iOS in the command-line and CI environments because they're the official tools provided by Android and iOS. Third-party tools such as [Fastlane](https://fastlane.tools/) may make this easier. Fastlane has been around much longer than Capacitor and has 20+ members on its core team alone. It's better if Capacitor focuses on its unique strengths instead of reinventing the wheel.

Could we document this better? Absolutely. Capacitor is just getting started.

**Comment by Siedlerchr** [comment]
I understand your argument, but only partly, even if you say use xcodebuild or gradle, why don't use the Cordova approach and pass the parameters for building down to the nativettools ? 
Even java just passes the parameters down to the native build tools for packaging and signing apps with the jpackage tool.

**Comment by Panteleimon** [comment]
Greetings. Any update on this?

**Comment by Heerschop** [comment]
You can use this [Ionic Capacitor example project](https://github.com/Heerschop/cli-example-app) for build with Capacitor from the CLI. This project uses [ionic hooks](https://ionicframework.com/docs/cli/configuration#hooks) and [script-launcher](https://www.npmjs.com/package/script-launcher) for enabling this.

For Android, it should just work as long as you have [Android Studio](https://developer.android.com/studio/index.html#downloads) installed and setup. For Apple, you first have to make sure you have configured your [certificates](https://developer.apple.com/support/certificates/) and [provisioning profiles](https://developer.apple.com/support/certificates/) accordingly, and then create the `ios/App/export-store-options.plist` and `ios/App/export-debug-options.plist` files as explained in the [README](https://github.com/Heerschop/cli-example-app#use-cli-for-building-ios-apps).

I hope this will help people to get started with this.

**Comment by tmk1991** [comment]
@Heerschop  - where does the `build ios` or `build android` output the app binary? Those commands seem to merely build your ionic application and not the binary.

```Once the web assets and configuration are copied into your native project, you can build your app using the native IDE. Unfortunately, programmatically building the native project is not yet supported.```

https://ionicframework.com/docs/cli/commands/capacitor-build

@ptitjes  answer above is the correct CLI way to build a native binary.

**Comment by Sampath-Lokuge** [comment]
I think this is a MUST need feature now with Capacitor 3 CLI hence now we can open the app directly on our device without native tools. And the huge problem we have now is even though we'll build our app with `--prod` it doesn't reduce the bundle size when we use the Native tools.  This is a huge problem right now for us for testing. i.e. first impression is very important here from our clients.

**Comment by jcesarmobile** [comment]
Capacitor 4.4.0 included build command, closing
