### ISSUE TITLE
bug: cap must be online to serve?

### ISSUE THREAD

**Issue by TensorTom** [ionic-team/capacitor#3275]
`npx cap serve` appears to require an Internet connection to function. Is that right? Seems bad.

**@capacitor/cli: 2.3.0
@capacitor/core: 2.3.0**

**Comment by dwieeb** [comment]
It appears we use `npx` to download a utility for serving the app. Since serving an app isn't something unique to Capacitor, I think we are going to remove it for Capacitor 3 and recommend a well-tested alternative: `serve` (https://github.com/vercel/serve).

Instead of `npx cap serve`, do the following:

```
npm install -D serve
npx serve
```

**Comment by dwieeb** [comment]
Closing in favor of https://github.com/ionic-team/capacitor/issues/3276
