### ISSUE TITLE
Investigate multiple environment support

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#3303]
What can Capacitor do to better support multiple environments such as dev, staging, and prod?

Is this a tooling problem or a documentation problem?

ref: https://github.com/ionic-team/capacitor/discussions/3298

**Comment by jcesarmobile** [comment]
It depends on what do you need from the multiple environments, if it's just about the urls the app points to, then that should be a framework thing, not a Capacitor thing, whatever they build for the environment they build would be in the webDir folder and Capacitor will use that.

If they want different bundle identifier/app id, icons, splash, version, etc, then the proper way would be to do it as native projects do, adding a new app target on iOS and a new product flavor (build variant) on Android.

**Comment by phal0r** [comment]
> If they want different bundle identifier/app id, icons, splash, version, etc, then the proper way would be to do it as native projects do, adding a new app target on iOS and a new product flavor (build variant) on Android.

@jcesarmobile 
So you suggest to completely handle this in the native project setup and not to duplicate project files. Seems like the right approach to me, so it would maybe a good idea to link to a guide in the docs on how to accomplish this. I am currently facing this exact requirement as it comes in really handy to have separate staging and prod app identifier to install them side by side on a single device. 

Is building different targets/build variants supported by Appflow?

**Comment by dwieeb** [comment]
This issue was created in reference to [this discussion](https://github.com/ionic-team/capacitor/discussions/3298):

> To my understanding capacitor only supports 1 `capacitor.config.js` file per project at the moment. I think it would be good to allow us define multiple based on needs of our enviroments i.e. `{env}.capacitor.config.js`

This has been accomplished in https://github.com/ionic-team/capacitor/pull/3756 and will be shipped in Capacitor 3.

**Comment by jayenashar** [comment]
> > To my understanding capacitor only supports 1 `capacitor.config.js` file per project at the moment. I think it would be good to allow us define multiple based on needs of our enviroments i.e. `{env}.capacitor.config.js`
> 
> This has been accomplished in #3756 and will be shipped in Capacitor 3.

is there documentation on this?  i can find some docs on `capacitor.config.js` but not `{env}.capacitor.config.js`

**Comment by buschtoens** [comment]
@jayenashar I think the idea is to export different configs from a single `capacitor.config.{js,ts}` file. You could for instance look at `process.env` to dynamically generate the right config.

**Comment by BleddP** [comment]
I have a question that is somewhat along the same lines of this topic, but if it deserves its own thread, please let me know and I can open a new issue.

I am working on converting an PWA to a native app with Capacitor and all is working extremely well so far. 
However the PWA uses 3 different rest endpoints: 

- localhost --> `ourwebsite.test/api/v1/` (set up locally with virtual env) 
- staging --> `staging.ourwebsite.com /api/v1/`
- production --> `ourwebsite.com/api/v1/`

When publishing an android app and uploading the .aab file to google play, I have used the staging endpoint as the test endpoint obviously wouldn't work. However, if everything is approved, we cannot publish this version to production because it still uses the staging endpoint. 

I've read that the best way to manage this is to create two app ID's:
- com.ourapp.staging
- com.ourapp.production

But in capacitor.config.json, we can only add one addId.

Is there any way with Capacitor to manage multiple environments?
Or perhaps my question should be is there any way with Google Play and the App Store to check which environment you're currently in and point to the right endpoint dynamically?
