### ISSUE TITLE
Veracode Security Flaws

### ISSUE THREAD

**Issue by patelchetan79** [ionic-team/capacitor#3316]
Hi,  After i create the Android Apk file and scan in veracode. Veracode Found below flaws in file.

Improper Output Neutralization for Logs

com\getcapacitor\CapacitorFirebaseMessagingService.java Line 1
com\getcapacitor\Logger.java Line 56, 52, 48, 48

Exposure of Sensitive Information Through Sent Data
com\getcapacitor\Bridge.java Line 718, 714, 572, 536, 534, 25,24, 530, 528, 509, 505, 336, 323, 251, 243, 241

Insecure Temporary File
com\getcapacitor\plugin\camera\CameraUtils.java Line 25

Thanks

**Comment by carlpoole** [comment]
Hi thanks for reporting this! Is there a more descriptive report you are able to share that shows more info. such as the content of the lines of code where these flaws occur?

**Comment by carlpoole** [comment]
```
Improper Output Neutralization for Logs

com\getcapacitor\CapacitorFirebaseMessagingService.java Line 1
com\getcapacitor\Logger.java Line 56, 52, 48, 48
```

Our Logger is accepting log data from the app and outputting it to the Android logger. Generally this does not leave the device unless the app builder is using a third party tool to capture these remotely. App developers can mitigate this issue by escaping problematic characters if they like.

```
Exposure of Sensitive Information Through Sent Data
com\getcapacitor\Bridge.java Line 718, 714, 572, 536, 534, 25,24, 530, 528, 509, 505, 336, 323, 251, 243, 241
```

It's difficult to pinpoint which lines of code this issue is referring to while reviewing the Bridge class. If further information is available, please include in a reply.

```
Insecure Temporary File
com\getcapacitor\plugin\camera\CameraUtils.java Line 25
```

The Camera plugin saves images to the Pictures directory in storage and these files are open and generally accessible. I don't think this really applies.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙
