### ISSUE TITLE
feat: Generate/use plugins from RN/flutter ecosystem

### ISSUE THREAD

**Issue by no-1ne** [ionic-team/capacitor#3371]
### Feature Request
Hello folks there is a so much RN ecosystem which can be leveraged in capacitor ecosystem, if there a converter to generate a capacitor plugin from RN/flutter plugin or a way to use the plugin directly (without having to maintain another generated plugin)

### Description
It would be awesome if there is a converter or away to use react native/flutter  plugin to capacitor, kind of like the 2to3 tool provided by python team to convert python 2.* Code to python 3.*

If it works, it can be huge, really huge, being able to build upon RN/flutter ecosystem.

**Comment by timmyrosen** [comment]
This would be amazing!

I'm a long time ionic & capacitor user, and have recently started playing around with Flutter.

Being able to create my own capacitor plugins with Flutter and use them in my capacitor projects would be fantastic!

**Comment by jcesarmobile** [comment]
Closing as I don't think this is technically possible, with Cordova it was "easy" because the technologies are very similar, but react-native and flutter are totally different.
I would be glad if somebody proves I'm wrong and build the compat/converter, but we are not going to dedicate time into investigating, sorry.
