### ISSUE TITLE
Different bundle-ids for android and iOS

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/capacitor#340]
This is more of a question:
Whats the way to go when having different bundle-ids for android and iOS? Add capacitor with one bundle-id and then change it manually in either XCode or Android Studio? 
Will the CLI ever overwrite this config? Because if thats the case there should probably be `appIdAndroid` and `appIdIos` in `capacitor.config.json`.

**Comment by mlynch** [comment]
Yep just change it manually in Xcode/Android Studio. We won't modify it after the project is created.

Will keep an eye out for this question and possibly add it to the docs.

**Comment by chenzhiguang** [comment]
Hi, it this possible to consider this requirement again? Thanks!

**Comment by forgr-owner** [comment]
same for us each sync override it just allow us to have a specific one by platform section it's painfull

**Comment by theheuman** [comment]
To deal with this issue I created a bash script that replaces android/app/src/main/assets/capacitor.config.json with a file that has the correct bundle id. And then I created an npm command that runs that shell script after running ionic sync.

so the shell script looks like this:

```
rm android/app/src/main/assets/capacitor.config.json
cp build/resources/capacitor.config.json android/app/src/main/assets/capacitor.config.json
```

and the npm command looks like this.

```
"scripts": {
  ...
  "sync": "ionic cap sync && ./scripts/post-sync.sh"
  ...
}
```

and then I can just run

```
npm run sync
```

instead of the normal ionic command

**Comment by arielhasidim** [comment]
This is actually really really needed:
I have a complex hybrid iOS/android project that was migrated from Cordova. in `appId` (capacitor.config.json) I used iOS's bundle id.

After releasing Capacitor-migrated iOS build, I started with the android platform. After adding android platform, I configured [as the docs say](https://capacitorjs.com/docs/android/configuration), and kept with the proper adjustments to the plugins. Yet, strange bug with Facebook-plugin (the app crashed every launch with error "make sure to call FacebookSdk.sdkInitialize() first" even when `ClientToken` and `AppId` was properly in place)  made me go and check if there was any left-overs from iOS's `bundle id` in search and it had A LOT.

I tried to change the `package id` post-creation with "search-and-replace" or with [capacitor config.yaml file](https://github.com/ionic-team/capacitor-configure#usage), nothing worked.

FINALLY I JUST ERASED ANDROID PLATFORM AND RE-ADDED IT AFTER CHANGING `appId` IN CAPACITOR CONFIG TO THE ANDROID'S `bundle id` AND THE PROBLEM WAS SOLVED.
