### ISSUE TITLE
bug: IOS addEventListener does not deliver retained events after remove / re-add

### ISSUE THREAD

**Issue by blairjo** [ionic-team/capacitor#3509]
### Capacitor Version

```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.0

  @capacitor/core: 2.4.0

  @capacitor/android: 2.4.0

  @capacitor/electron: 2.4.0

  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/electron not installed


  @capacitor/cli 2.1.0

  @capacitor/android 2.3.0

  @capacitor/core 2.3.0

  @capacitor/ios 2.3.0

[success] Android looking great! �
[error] Xcode is not installed

```

### Platform(s)
IOS only

### Current Behavior

1. Add a listener for some event
2. Remove the Listener
3. Invoke notifyListeners with retainUntilConsumed enabled
4, Add listener once again
5. The retained event is not delivered

### Expected Behavior

The retained event should be delivered when addEventListener() is called. 
The problem is this code in CAPPlugin.m:

`if(!listenersForEvent) {
    listenersForEvent = [[NSMutableArray alloc] initWithObjects:listener, nil];
    [self.eventListeners setValue:listenersForEvent forKey:eventName];
    
    [self sendRetainedArgumentsForEvent:eventName];
  } else {
    [listenersForEvent addObject:listener];
  }`

it SHOULD be:

`if(listenersForEvent == nil || [listenersForEvent count] == 0) {
    listenersForEvent = [[NSMutableArray alloc] initWithObjects:listener, nil];
    [self.eventListeners setValue:listenersForEvent forKey:eventName];
    
    [self sendRetainedArgumentsForEvent:eventName];
  } else {
    [listenersForEvent addObject:listener];
  }`

The above is essentially what the android code is doing 

### Additional Context
The above fix is essentially what the android version is doing already in Plugin.java:

`
private void addEventListener(String eventName, PluginCall call) {
    List<PluginCall> listeners = eventListeners.get(eventName);
    if (listeners == null || listeners.isEmpty()) {
      listeners = new ArrayList<PluginCall>();
      eventListeners.put(eventName, listeners);

      // Must add the call before sending retained arguments
      listeners.add(call);

      sendRetainedArgumentsForEvent(eventName);
    } else {
      listeners.add(call);
    }
  }
`

**Comment by alessa-nd** [comment]
### Bug Report
Capacitor Version

npx cap doctor output:

Latest Dependencies:

_@capacitor/cli: 2.1.0

@capacitor/core: 2.1.0

@capacitor/android: 2.1.0

@capacitor/ios: 2.1.0_

Installed Dependencies:

  _@capacitor/cli: 3.2.5

  @capacitor/core: 3.2.5

  @capacitor/android: 3.2.5

  @capacitor/ios: 3.2.5_

Affected Platform(s)
 iOS

###  Current Behavior
With the app open in the background, I open a deeplink that successfully opens the app. However, once the app is running, the listener appUrlOpen is not called and I can't get the url.

If the app is closed and I open a deeplink. The app opens and getLaunchUrl() is called but the result is always empty, no matter what link I used to open it.

### Expected Behavior
If the app is open in the background and I open a deeplink, the listener appUrlOpen is called and allows me to get the url with which the app was open.

If the app is closed and I open a deeplink, getLaunchUrl() is called and gives the url with which the app was open.

### Sample Code or Sample Application Repo
    App.addListener('appUrlOpen', function (event: URLOpenListenerEvent) {
     
      const slug = event.url.split('.com').pop();

      if (slug) {
        router.push({
          path: slug,
        });
      }
    });

### Reproduction Steps
Open a deeplink on an iOS device on iOS 15.0 with the app running in the background and see if it prints the url.
Same steps but with the app closed.

### Other Technical Details
_npm --version output: 8.0.0

node --version output: v1418.0

pod --version output (iOS issues only): 1.11.2_

### Other Information
The feature works perfectly on Android, no problem

On iOS the url is successfully caught natively by the SceneDelegate on an iPhone 13 with iOS 15.0. I can print it in swift. But not by Capacitor. I've spent a few days on it to make sure it wasn't a problem with the iOS deeplink setup but everything seems to be working fine. That's why I'm suspecting Capacitor to mess something up.

I've tried other listeners to make sure it wasn't a global issue and appStateChange works fine, it really is a specific issue with URL related stuff on iOS

Thanks to anyone who wants to give a shot to this issue.
