### ISSUE TITLE
bug: package com.getcapacitor.android does not exist

### ISSUE THREAD

**Issue by archiemcquaid** [ionic-team/capacitor#3519]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.0
  @capacitor/core: 2.4.0
  @capacitor/android: 2.4.0
  @capacitor/electron: 2.4.0
  @capacitor/ios: 2.4.0

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.0
  @capacitor/core 2.4.0
  @capacitor/android 2.4.0
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

When trying to build android, I am getting the error `package com.getcapacitor.android does not exist`.

### Expected Behavior

No error when building.

### Other Technical Details

`npm --version` output: 6.14.8

`node --version` output: 14.9

`pod --version` output (iOS issues only):

### Additional Context

Build was working fine, when I tried to build for release, this error appeared. I now cannot build at all. GIT shows no changes.

**Comment by dominic-ks** [comment]
I'm getting this error right now after changing package name to my app's package name in manifest.xml...

@archiemcquaid assume you solved this, any info?

**Comment by archiemcquaid** [comment]
Hi @dominic-ks, my issue was I was global searching for `AndroidManifest.xml` and ended up changing the wrong one. It's the top one that you need to modify, under `/app/manifests/AndroidManifest.xml`.

![image](https://user-images.githubusercontent.com/16037240/98466770-8ba63200-21c9-11eb-8172-af1b6a06c898.png)

**Comment by dominic-ks** [comment]
Thanks for coming back with some info @archiemcquaid I'm pretty sure I am editing the correct file, though mine is under app > src > main > AndroidManifest.xml so a slightly different tree to yours. But pretty sure I've got the right file. 

I have just worked out what is causing my issue though, and that is that there were a number of files in my Android project referencing com.getcapacitor.android that were getting reported in the error messages and I've gone through and updated them to my package name and it's solved it for me. 

Though I haven't verified, I'm currently guessing that it's because I added android to my Ionic project before I updated the package name from the default and so the default had been propagated to various places. In future I'll make sure I do basic config before adding platforms...
