### ISSUE TITLE
feat: Add onConfigurationChanged() handling to the Android capacitor plugin infrastructure

### ISSUE THREAD

**Issue by shpasser** [ionic-team/capacitor#3535]
## Feature Request
Add onConfigurationChanged() handling to the Android capacitor plugin infrastructure

### Description
Sometimes it is appropriate to handle the Android's "onConfigurationChanged()" events in plugins.
As of now the infrastructure does not support the feature, so a plugin cannot react to 
the configuration change events on Android platform.

### Platform(s)
Android

### Preferred Solution
Add the following handler to Plugin.java and support it in the Capacitor (like handleOnStart()):
```
/**
   * Handle handleOnConfigurationChanged
   */
  protected void handleOnConfigurationChanged() {}
```

### Alternatives
None

### Additional Context
None

**Comment by shpasser** [comment]
Thanks a lot.

**Comment by trtbankdata** [comment]
Why is this closed when PR isn't merged? -nor passing checks?

**Comment by shpasser** [comment]
I am not responsible for testing. I just submitted a feature request and it seems that the commit is ok.

**Comment by wf9a5m75** [comment]
Oh, my.... Why the ionic team didn't implement `onConfigurationChange` from the first.

**Comment by dwieeb** [comment]
@wf9a5m75 Will you need this for your Google Maps plugin? We can add it to Capacitor 3.

**Comment by wf9a5m75** [comment]
@dwieeb Yes. For example, Android notify the change event to `onConfigurationChange()` when the user changes `light/dark mode`.

`window.matchMedia('(prefers-color-scheme: dark)').addEventListener()` doesn't work on Webview of Android because of the WebView bug.
Only the way to receive the change event is to implement `onConfigurationChange()`.

The next Google Maps plugin synchronizes `light/dark mode` with the system. That's why it's necessary.

**Comment by dwieeb** [comment]
@wf9a5m75 I have [a PR](https://github.com/ionic-team/capacitor/pull/3936) up for this and it should make it into 3.0.0-alpha.8.

**Comment by shpasser** [comment]
The actual reason I opened this feature request is that I need it for my ionic plugin. The second thought was that there is no reason why the other hooks are implemented and this one is not.
