### ISSUE TITLE
VisualViewport does not take keyboard into account

### ISSUE THREAD

**Issue by piotrblasiak** [ionic-team/capacitor#3730]
Using window.visualViewport we can detect the on screen keyboard in web apps, but this does not work in cordova or capacitor and we have to rely on native plugins.

**Comment by jcesarmobile** [comment]
please, when reporting issues, provide all the data required by the template

**Comment by piotrblasiak** [comment]
Sorry, here it is:

## Bug Report

### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 2.4.2
  @capacitor/core: 2.4.2
  @capacitor/android: 2.4.2
  @capacitor/electron: 2.4.2
  @capacitor/ios: 2.4.2

Installed Dependencies:

  @capacitor/cli 2.4.2
  @capacitor/core 2.4.2
  @capacitor/android 2.4.2
  @capacitor/ios 2.4.2
  @capacitor/electron not installed

[success] Android looking great! 👌
  Found 0 Capacitor plugins for ios:
[success] iOS looking great! 👌

```

### Platform(s)

iOS



### Current Behavior

window.visualViewport.height does not change when keyboard shows/hides if the keyboard plugin is set to resize: none. Also the "resize" event on the visualViewport is not triggered.



### Expected Behavior

The keyboard height should be subtracted from the height and the resize event should be triggered. This does work on exactly the same code when running from safari and not capacitor webview.



### Code Reproduction

https://github.com/attendium/vvtest



### Other Technical Details

`npm --version` output: 6.13.7

`node --version` output: v12.15.0

`pod --version` output (iOS issues only): 1.8.4

### Additional Context

It seems the ionic team is already aware of this somehow, as it is mentioned on https://ionicframework.com/blog/keyboard-improvements-for-ionic-apps/ ("While the Visual Viewport resize events typically do not fire in Capacitor and Cordova applications...")

**Comment by jcesarmobile** [comment]
This is a limitation on the keyboard plugins, not really a bug in Cordova/Capacitor.

But Ionic apps by default use `@capacitor/keyboard` on Capacitor apps or `cordova-plugin-ionic-keyboard` plugin in Cordova apps, so that's probably why that note is added in their docs.

If you remove those plugins, then the visualViewport will work. But you can't prevent the WebView resizing and at the same time have the visualViewport working, they are mutually exclusive, if there is no WebView resizing when the keyboard appears there is no visualViewport change related to the keyboard.

Since Capacitor 3 the plugins are separate packages, so now you have the possibility to uninstall the `@capacitor/keyboard` plugin if you want to rely in the `visualViewport`.
