### ISSUE TITLE
bug: iOS 14 new Photos picker permission is not handled correctly

### ISSUE THREAD

**Issue by ryaa** [ionic-team/capacitor#3841]
### Capacitor Version

```
   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2
```

### Current Behaviour
Pre-requisite
- create the ionic angular application with camera/image picker support as described here https://ionicframework.com/docs/angular/your-first-app
For the camera getPhoto method use the default CameraSource.Prompt - see https://capacitorjs.com/docs/apis/camera#camerasource

There ~~are two~~ one use case:
1) No permissions for photo has been granted
1.1) Change from all photo access to no photo access in Settings as described below
- Open the Settings app.
- Select Privacy | Photo | App.
- Select None under Allow Photos Access
1.2) open the app
1.3) start the camera and choose From Photos (to load a photo)
Note that the picker will be dismissed silently without showing any UI or message which might be confusing for the user
~~2) Limited subset of photos are allowed~~
~~2.1) Change from all photo access to Selected Photos access in Settings as described below~~
~~- Open the Settings app.~~
~~- Select Privacy | Photo | App.~~
~~- Select Selected Photos under Allow Photos Access but DON'T select any photos and tap Done (no photos should be allowed)~~
~~2.2) open the app~~
~~3.3) start the camera and choose From Photos (to load a photo)~~
~~Note that the picker will show all the photos (even though the user has not granted access to them) and allows to select and load the photo.~~

### Expected Behavior
For the use case #1 the app should show either empty picker or some message and NOT dismiss silently
~~For the use case #2 the app should show and allow to choose only the photos that the user has granted permission for.~~

### Code Reproduction
N/A

### Other Technical Details
Ionic:

   Ionic CLI                     : 6.10.1 (/Users/alexryltsov/.nvm/versions/node/v12.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 8.0.0
   @angular/cli                  : 9.1.9
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.18.1 (/Users/alexryltsov/.nvm/versions/node/v12.18.1/bin/node)
   npm    : 6.14.5
   OS     : macOS Catalina

`pod --version` output (iOS issues only):
1.9.1

### Additional Context
iOS 14 introduced new photo picker with enhanced permission management which the capacitor camera plugin does not seem to handle correctly

**Comment by ryaa** [comment]
Note about the use case 2 and the picker showing all the photos. This is by design and the picker shows the entire Photos Library and all photos and videos can be selected by the user. No matter what the users selects in the picker, the PHAssets you can access will not change.

See https://developer.apple.com/forums/thread/653414?answerId=619805022#619805022

**Comment by dwieeb** [comment]
@ryaa I believe this issue was fixed for Capacitor 3 in the [new camera plugin](https://github.com/ionic-team/capacitor-plugins/tree/main/camera).

**Comment by ryaa** [comment]
@dwieeb I will test it when I have a chance and provide my feedback. Thank you

**Comment by arnotixe** [comment]
Note, iOS now lets you not only select "Grant/Deny" but also choose what pictures to allow the app to access.
This setup is a chicken/egg problem for me, because my app saves photos to the gallery. If the user chooses "only selected pictures", he/she cannot possibly select the image because it isn't created yet…

The option "only selected pictures" is not shown here: https://github.com/ionic-team/capacitor-plugins/tree/main/camera#camerapermissionstate

Is there a way to check for/explicitly request "access to ALL photos"? I don't necessarily want to force the user - just to inform him that he needs to change the permissions to "all" for certain functions to work. Right now, the image IS saved to the app private storage space, but it isn't added to his gallery unless "all pictures" is selected.

Reading that last sentence aloud also makes me think there is a related bug to this (?) - should apps be able to Save TO the gallery without this "all" permission granted? My app does not need to read any photos from gallery at all - I only need to write them to app private storage and and add them to the gallery.

**Comment by pixelone** [comment]
@arnotixe -  Did you ever find a solution for this?  

Running into the same issue with the latest Camera plugin "@capacitor/camera": "^0.4.5",  and Capacitor 3 RC2.  

I also notice that when the photo gallery viewer pops up in IOS, it completely ignores photos you select "access" to.    If we can force full access that would be fine.

**Comment by arnotixe** [comment]
> @arnotixe - Did you ever find a solution for this?

No, I just tell the customers we need access to "all". My use case is not actually a problem with user selecting or not images though - I just want to SAVE to photos, don't care about reading them. I also need Full access to be able to save to photos.

(Technically, I save to the app's internal space and they are stored there even without access. But to share them to a Photo Library I need Full access or the user will not see my album. Unsure whether it is created and invisible, or if it just isn't created. I think probably the latter.)

In any case, I think your mention of no access even if you specify images to access also points to the same - that the new type of "per-image" permissions just aren't handled well by current code. Neither for reading nor writing.

Unsure if my  use case - writing - should work with just "some" files specified… Guess not or it would be a chicken/egg problem since you cannot select images that do not exist yet.

**Comment by jcesarmobile** [comment]
I've verified that the problem doesn't happen on Capacitor 3 and @capacitor/camera plugin

about knowing if the user selected the all or selected photos, checkPermissions can be used, will return limited if the user used the "selected photos"
