### ISSUE TITLE
bug: Cannot disable Splash screen for Android after configuring the "launchShowDuration" to 0

### ISSUE THREAD

**Issue by karm435** [ionic-team/capacitor#3843]
Here is the code from Bridge.java

```
public static void showOnLaunch(final BridgeActivity a, CapConfig config) {
    Integer duration = config.getInt(CONFIG_KEY_PREFIX + "launchShowDuration", DEFAULT_LAUNCH_SHOW_DURATION);
    Boolean autohide = config.getBoolean(CONFIG_KEY_PREFIX + "launchAutoHide", DEFAULT_AUTO_HIDE);

    if (duration == 0) {
      return;
    }

    show(a, duration, 0, DEFAULT_FADE_OUT_DURATION, autohide, null, true, config);
  }
```

However even after setting this to 0 in the capacitor.config does not work

```
"plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    }
  },
```

**Comment by danielehrhardt** [comment]
```
    <style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">
    </style>
```
styles.xml

**Comment by karm435** [comment]
That is a workaround. I was just trying to figure out what is the use of that code if that is not executed? or am I looking in the wrong place for the handling of splash screen configuration in Android Native project.

**Comment by jcesarmobile** [comment]
On Capacitor 3 the plugins have been moved out, so you won't have the Splash screen plugin anymore if you don't want.

But: 
On iOS first the launch storyboard is shown and then the Splash screen plugin
On Android first the activity background is shown and then the Splash screen plugin

So, even if you set the value to 0 or don't install the plugin, you'll still see the launch image.

danielehrhardt gave you a solution, that is to remove the background image from the activity theme, it will then show a grey background instead of the image, the background color can be configured, there are a few related issues about it.

**Comment by rashnk** [comment]
there is no such config mentioned in the doc https://capacitorjs.com/docs/config

**Comment by jcesarmobile** [comment]
Plugin specific configurations are documented on the plugins
https://capacitorjs.com/docs/apis/splash-screen#configuration
