### ISSUE TITLE
bug: Can't access savePluginCall in iOS plugin

### ISSUE THREAD

**Issue by barrcodes** [ionic-team/capacitor#4078]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 2.4.6
  @capacitor/core: 2.4.6
  @capacitor/android: 2.4.6
  @capacitor/electron: 2.4.6
  @capacitor/ios: 2.4.6

Installed Dependencies:

  @capacitor/cli 2.4.5
  @capacitor/core 2.4.5
  @capacitor/android 2.4.5
  @capacitor/ios 2.4.5
  @capacitor/electron not installed
```

### Platform(s)

iOS

### Current Behavior

On Android, when perfrorming async tasks, I can `saveCall(call)` and then access a saved call using `savedCall`.

On iOS, I can try to get a call with `let call = self.bridge.getSavedCall(callbackId!)`, but `self.bridge.savePluginCall(call)` is inaccessible due to protection level.

### Expected Behavior

I expect to be able to save and retrieve plugin calls in iOS

### Code Reproduction

No need, literally just create a new capacitor plugin project, and try to save / retrieve a call in iOS

### Other Technical Details

`npm --version` output:

```
npm: '6.14.4',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '36.1',
  icu: '66.1',
  llhttp: '2.0.4',
  modules: '83',
  napi: '6',
  nghttp2: '1.40.0',
  node: '14.2.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.37.0',
  v8: '8.1.307.31-node.33',
  zlib: '1.2.11'
```

`node --version` output: v14.2.0

`pod --version` output (iOS issues only): 1.8.4

**Comment by ikeith** [comment]
The difference in APIs is an issue that should be addressed. However, you are not expected to call `saveCall` or `savePluginCall` directly on the bridge. Instead, you should use `save()` on the plugin call itself, that is available across platforms.

**Comment by barrcodes** [comment]
@ikeith I see now that `CAPPluginCall` has a member `save()`, but if this is the logic we are to use, the docs need updated.

The Android documentation explicitly suggests using `saveCall(call);`: [Android docs](https://capacitorjs.com/docs/plugins/android)

The iOS documentation does not have any reference to saving for async plugins: [iOS docs](https://capacitorjs.com/docs/plugins/ios)

**Comment by barrcodes** [comment]
How does one retrieve a call that is saved in iOS? Using `call.Save()` with `self.bridge.getSavedCall(callbackId)` returns `nil`. On Android the plugin has a `savedCall` member

**Comment by ikeith** [comment]
So it looks like there are several issues at play here:

- The preferred way to save/retrieve a call is unclear and the platforms have conflicting APIs. We need to determine the one true pattern, implement it everywhere, and document the result. There's a new issue to track that work: https://github.com/ionic-team/capacitor/issues/4087
- Relatedly, some of this has already been changed for 3.0. Android's `getSavedCall` on the plugin [has been deprecated](https://github.com/ionic-team/capacitor/blob/e148e67c6061be35db361496444d5fa85544a068/android/capacitor/src/main/java/com/getcapacitor/Plugin.java#L62) because a) it duplicated behavior and b) it was only a single property and could get overwritten. 
- `getSavedCall` on the bridge in iOS may not be working correctly.

As to the last item, when are you calling `getSavedCall()`? `save()` on `CAPluginCall` sets a flag to store it later, but that doesn't actually happen until the plugin method returns. So it should work when it is called from an async method in the future but it won't work immediately after calling `save()`.

In the meantime, you can simply keep the call in a local property instead of relying on the built-in machinery. That's not ideal but it should work in most situations while things get sorted out.

**Comment by barrcodes** [comment]
I'm calling `getSavedCall` async from the camera callback. IMO it should be working, but it's not. At the moment, I'm just caching the call in my plugin class as a member, and clearing it when the plugin resolves or rejects the call. 

Not sure if this could cause life cycle event issues, but this appears to be how the capacitor 2.0 camera plugin does it:
line 41: `var call: CAPPluginCall?`
https://github.com/ionic-team/capacitor/blob/2.x/ios/Capacitor/Capacitor/Plugins/Camera.swift

**Comment by jcesarmobile** [comment]
in Capacitor 3 there are new APIs for saving/getting the calls, the docs are here https://capacitorjs.com/docs/v3/core-apis/saving-calls
