### ISSUE TITLE
feat: Implement App-Bound Domains to enable Service Workers in WKWebView on iOS14+

### ISSUE THREAD

**Issue by jgoux** [ionic-team/capacitor#4122]
### Description

Since iOS14, it's possible to make service workers works in WKWebView by providing a list of trusted domains (up to 10).
These domains then gain support for service workers, which is invaluable for us as we plan to use `server.url` in production to distribute our PWA on iOS.

Here are links describing the possibilities and features : 
- https://firt.dev/ios-14/#service-workers
- https://webkit.org/blog/10882/app-bound-domains/

### Platform(s)

- iOS

### Preferred Solution

I think being able to pass the domain list with capacitor's config file would be enough. Then capacitor could patch the `Info.plist` file with the domains, and build the WKWebView using the snippet provided in the first post I shared above : 
```swift
let configuration = WKWebViewConfiguration()
configuration.limitsNavigationsToAppBoundDomains = true
// Create a WebView with this configuration
```

### Alternatives

As of today I don't think there is any alternative to support service workers in WKWebView

**Comment by ikeith** [comment]
Patching the `Info.plist` file to keep it in sync with the capacitor config goes against the spirit of capacitor, which tries to leave the native projects alone after creation so that you are free to modify it as you see fit.

But, enabling app bound domains is totally possible in [Capacitor 3.0](https://capacitorjs.com/blog/announcing-capacitor-3-0-beta). If you add the domains to the `Info.plist` and subclass `CAPBridgeViewController`, you can then override [`webViewConfiguration(for:)`](https://github.com/ionic-team/capacitor/blob/bd59fa3637ec32280864cee4d649267274109e5a/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L101) to modify the configuration before the web view gets created.

It should be noted, however, that shipping a `server.url` configuration to the App Store is not advised.

**Comment by jgoux** [comment]
Thanks for the info @ikeith !

If I want to subclass `CAPBridgeViewController`, where do the subclass file would live? Does it have to be part of a Plugin?

Also for the `server.url`, we know that's not advised but we'll take the risk as it's the easiest path in our case. If we fail the App Store validation then we'll reconsider.

**Comment by ikeith** [comment]
@jgoux The subclass would not be part of a plugin but belong to the containing native app. So it would live alongside `AppDelegate`, `Info.plist`, etc.

**Comment by jcesarmobile** [comment]
we are adding `limitsNavigationsToAppBoundDomains` configuration option from the capacitor configuration file, see https://github.com/ionic-team/capacitor/pull/4789

**Comment by webuniverseio** [comment]
@ikeith you mentioned that `server.url` in production is not advised, why is that? With live webview & service workers you're solving multiple problems - you get proper https:// protocol which avoids problems with recaptcha and google analytics which don't work out of the box with non standard protocols. You avoid issues with any 3rd party services which use `//domain.com/path` urls. Various 3rd party url parsers don't break or act weird. You get cookie support which may be an impossible issue to solve for 3rd party. After first load app can work offline due to Service Workers support.

**Comment by webuniverseio** [comment]
@jgoux would it be possible for you to share your experience with live `server.url` and AppStore release? I definitely know of some apps which have live webviews and are successful at it

**Comment by thomasvidas** [comment]
FYI, Ian no longer works at Ionic so he probably won't answer 😄. To answer your question, here's why we do not advise using a live `server.url`:

- Capacitor apps lose the secure context for several web apis. In the [config docs](https://capacitorjs.com/docs/config) we list a few if you scroll down to the `server.url` option.
- Apple has rejected apps that point to a live URL. Apple's (and Google's) app review process is pretty opaque so it's hard to know exactly why they may reject one app that does this and approve another app. But in general, Apple is pretty clear that if your application is just an existing version of a website bundled in an app, they may reject it.
- It is bad UX to point to an external server since if a user does not have internet access there is no functionality. By pointing to a localhost, the files are on the device. Meaning that even if your user has no internet access, the app is still functional.
