### ISSUE TITLE
feat: add a getMethod() to Bridge instance

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/capacitor#4175]
### Description

We currently have a public `getMethods()` which returns all of the methods on a PluginHandle, but would also like to add one more convenience method of `getMethod(name)`, since this is what we're actually running from other plugins wanting to call a method.

### Platform(s)
android
ios

### Preferred Solution

Something similar to:

```
    Method getMethod(PluginHandle pluginHandle, String name) {
        if (pluginHandle != null) {
            Collection<PluginMethodHandle> methods = pluginHandle.getMethods();
            for (PluginMethodHandle methodHandle : methods) {
                if (methodHandle.getName() == name) {
                    return methodHandle.getMethod();
                }
            }
        }
        return null;
    }
```

### Alternatives

Easy way for one plugin to call methods on another plugin.

### Additional Context

Useful for communication between separate plugin instances, but designed to work together.

**Comment by adamdbradley** [comment]
Related https://github.com/ionic-team/capacitor/issues/4174

**Comment by jcesarmobile** [comment]
getMethods is not really intended for plugins using other plugins.
In Capacitor 3 we refactored most plugins to have an implementation class plugins can use instead of using the plugin class.
Also, if needed, plugins can get other plugins by using `bridge.getPlugin("pluginName");`, that will give access to the native plugin class and will allow to use any method without relying on reflection, so I think that's preferred than using reflection.
