### ISSUE TITLE
bug:  error: package com.getcapacitor.annotation does not exist import com.getcapacitor.annotation.CapacitorPlugin;

### ISSUE THREAD

**Issue by stalker3343** [ionic-team/capacitor#4338]
## Bug Report
After installing the BrowserPlugin and Clipboard plugins during the build, I get an error
```
node_modules\@capacitor\browser\android\src\main\java\com\capacitorjs\plugins\browser\BrowserPlugin.java:8
error: package com.getcapacitor.annotation does not exist 
import com.getcapacitor.annotation.CapacitorPlugin;
```
in both plugins. 

In addition, the WebColor is not defined in the BrowserPlugin plugin.
import com.getcapacitor.util.WebColor;

### Capacitor Version
```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/electron not installed

[success] Android looking great! 👌
```

### Platform(s)
- android

### Current Behavior
node_modules\@capacitor\browser\android\src\main\java\com\capacitorjs\plugins\browser\BrowserPlugin.java:8: error: package com.getcapacitor.annotation does not exist
import com.getcapacitor.annotation.CapacitorPlugin;

![изображение](https://user-images.githubusercontent.com/42894422/111076027-a08a2d80-84fb-11eb-9a4b-e33b27973661.png)

### Expected Behavior
After I click build in android the project should be built

### Code Reproduction
This is the full code of my app:
https://github.com/stalker3343/ionic-pwa-app

### Other Technical Details
`npm --version` output: 6.14.8

`node --version` output: v15.8.0

### Additional Context

https://github.com/ionic-team/capacitor/issues/4168 - i have last version of android
https://github.com/ionic-team/capacitor/issues/1937 - try npx cap update, but it don't help

**Comment by stalker3343** [comment]
I find [solution](https://forum.ionicframework.com/t/geolocation-plugin-gives-errors-when-building-an-apk-with-gradle-using-capacitor-3-beta-3/205559) on forum.  I update @capacitor/android to @capacitor/android@3.0.0-rc.0. And it fix problem with `package com.getcapacitor.annotation does not exist `. But i use  @capacitor/core 2.4.7 why i need install android@3.0.0-rc.0 ?

After update  @capacitor/browser and  @ionic-native/barcode-scanner work fine. But @capacitor/clipboard don't work.

**Comment by stalker3343** [comment]
i fix problem when see msg:
`This repository contains the official Capacitor plugins maintained by the Capacitor team.`
in plugins [repository](https://github.com/ionic-team/capacitor-plugins).

I update @capacitor/core": "^3.0.0-rc.0" and @capacitor/cli": "^3.0.0-rc.0. Fix import plugins, and all work fine.

**Comment by marwenhinnaouii** [comment]
Any Solution
![image](https://user-images.githubusercontent.com/109084475/178808713-5315410f-853d-4f7f-9b13-bbdceb4eee3f.png)

**Comment by jcesarmobile** [comment]
CapacitorPlugin annotation is only available in Capacitor 3, so if you are in Capacitor 2, the only solution is to update to Capacitor 3.

If you don't want to update to Capacitor 3, uninstall @capacitor/device plugin, that's a Capacitor 3 plugin, Capacitor 2 had all the plugins included.

**Comment by martin-braun** [comment]
`npm install @capacitor/clipboard@0.1.1` if you cannot upgrade to Capacitor 3. I had to do some trial and error. Better documentation or proper versioning would've been welcome, but it seems this is planned, as it's skipped to version 4 for Capacitor 4 rightfully.

Since I only need to copy test, I don't know if there are any bugs in such legacy version. Upgrading Capacitor is surely the better move, if you can do that.

**Comment by jcesarmobile** [comment]
None of the `@capacitor/xxx` plugins is compatible with Capacitor 2, Capacitor 2 have all the plugins bundled with it, you don't have to install any of the `@capacitor/` and if you install them you'll face problems because all of them are for Capacitor 3.

**Comment by martin-braun** [comment]
@jcesarmobile So how to use the clipboard in Capacitor 2, please?

**Comment by danielsogl** [comment]
> @jcesarmobile So how to use the clipboard in Capacitor 2, please?

How about reading the docs? RTFM: https://capacitorjs.com/docs/v2/apis/clipboard

**Comment by martin-braun** [comment]
@danielsogl Thanks, I have read the docs, just the wrong once, because: 

<img width="296" alt="Screen Shot 2022-07-23 at 11 40 02 AM" src="https://user-images.githubusercontent.com/24259245/180599923-980dc5da-2348-401f-809e-bd5c5c8064b8.png">

A dropdown that was so tiny and I missed it. Searching for ["capacitor 2 clipboard"](https://www.google.com/search?q=capacitor+2+clipboard) or ["capacitor v2 clipboard"](https://www.google.com/search?q=capacitor+v2+clipboard) at Google will show up the link to v3 spec as well.

How about fixing accessibility or indexing of your docs? It's not that I didn't try to find proper guidance before asking.
