### ISSUE TITLE
feat: Detect incoming call status when app is running in background

### ISSUE THREAD

**Issue by 313hemant313** [ionic-team/capacitor#4410]
### Description
How to detect incoming call and call has ended if the ionic app is running in background ?

Currently in my music app if user picks up the incoming call, music doesn't pause or stops.

Please help me resolve this issue.

Had no luck here: #3992 or #2282

**Comment by jcesarmobile** [comment]
Closing due to the lack of interest by other users and because I don't think this is a feature that should be part of Capacitor core but a separate plugin.

Since the reporter created a plugin, if anybody is interested can use that plugin
https://github.com/313hemant313/capacitor-plugin-incoming-call
