### ISSUE TITLE
Look into save browser url whitelist for Android

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#449]
<img width="938" alt="screen shot 2018-04-10 at 8 26 56 pm" src="https://user-images.githubusercontent.com/11214/38591693-9453af1c-3cfd-11e8-9236-3f2e981c0f73.png">

Might have perf implications

**Comment by jcesarmobile** [comment]
We have sort of a whitelist for navigation in shouldOverrideUrlLoading, shouldInterceptRequest is for resources. We can also whitelist those if we want, but I think users should use the Content-Security-Policy tag if they want to restrict connections instead of us doing it with a native whitelist. Going to close for now.
