### ISSUE TITLE
Permission query on geolocation on Android returns denied

### ISSUE THREAD

**Issue by karen1au** [ionic-team/capacitor#4556]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/electron not installed

```

### Platform(s)

Android

### Current Behavior

I'm using capacitor plugin for background geolocation (@capacitor-community/background-geolocation v0.3 for capacitor v2) to prompt and watch for background location, and using Capacitor Permissions api to query geolocation permission.
On Android, if users choose `only this time` on the initial permission prompt, query for geolocation permission returns and remains `granted` unless users change it manually in setting, however if user changes permission to `ask everytime` from setting after the initial popup, permission query returns and remains `denied`.

### Expected Behavior

I do noticed there's no prompt state on Android, it always starts with `deny`, but I think the `only this time` option prompt and `ask everytime` option in setting should behave similarly?

### Other Technical Details

`npm --version` output: 6.14.4

`node --version` output: 14.15.1

`capacitor-community/background-geolocation` : 0.3

### Additional Context

Thanks in advance for the help!

**Comment by jcesarmobile** [comment]
Permissions plugin has been removed from Capacitor 3, so this won't be fixed on Capacitor 2.

**Comment by diesieben07** [comment]
This is still an Issue in Capacitor 3.
https://github.com/ionic-team/capacitor/blob/17a73ff60b3e0e1807db3a2349b83ca62d7fb83b/android/capacitor/src/main/java/com/getcapacitor/Bridge.java#L899-L905
This use of the method `shouldShowRequestPermissionRationale` is _incorrect_. Just because this method returns false does not mean the permission was denied forever, it just means that you should not show a rationale before asking again.
This becomes apparent on Android 11, where `shouldShowRequestPermissionRationale` can return false even though the permission is not permanently denied. This happens when the permission is set to "Ask every time".
