### ISSUE TITLE
Device plugin on PWA

### ISSUE THREAD

**Issue by amrayoub** [ionic-team/capacitor#458]
Hi ,
I'm using Device plugin on PWA application ( angular 5 and Capacitor ) , when I build the app android or IOS , the device plugin works great and returns all the info about the device.
but when I build it on PWA and access the local host from chrome on mobile ,
 that's what i get
{
    "__zone_symbol__state": true,
    "__zone_symbol__value": {
        "model": "web",
        "platform": "web",
        "appVersion": "",
        "osVersion": "",
        "manufacturer": "",
        "isVirtual": false,
        "batteryLevel": 0.23,
        "isCharging": true,
        "uuid": "680cf9d1-60f9-421a-8f46-b52a2848c9e8"
    }
}

as you can see , the osVersion and "manufacturer are empty and diskFree isn't available   , also why the platform is web when I run it on chrome from mobile ??

Thanks

**Comment by amrayoub** [comment]
I used `await Device.getInfo()` along with `async` .
the plugin works great when I build and run for Android and IOS . it shows all the fields.
but when i build  PWA and run the app on chrome android .
it shows many empty fields along with ""platform": "web", even though I run the app from android chrome browser

**Comment by IT-MikeS** [comment]
I don't think that information is exposed to a PWA is it? I could be wrong, @mlynch will most likely know.

**Comment by John-Luke** [comment]
The informations: `model`, `manufacturer` and `osVersion` can be get using the userAgent from the browser

**Comment by amrayoub** [comment]
@John-Luke  Great , I hope ionic Team can integrate it in Device Plugin

**Comment by jcesarmobile** [comment]
We have added model, osVersion and manufacturer to latest version.

Manufacturer returns navigator.vendor, which for Chrome in Android is "Google Inc." and not the phone manufacturer, the phone manufacturer is not exposed to the navigator object.

platform will return "pwa", as Capacitor available platforms are "android", "ios", "electron" and "pwa"

diskFree and some other things provided by the native implementations are not available on PWAs because they are not accessible, that's the point of iOS and Android platforms, to get things that are not possible on the web.

Closing the issue.

**Comment by amrayoub** [comment]
@jcesarmobile 
Hi , have you checked that  https://deviceatlas.com/blog/list-of-user-agent-strings

I think mode and manufacturer is exposed to PWA

**Comment by jcesarmobile** [comment]
Yeah, I checked that. I don't see the manufacturer, just models.
In example `SAMSUNG SM-T550` is the model, other samsung devices just have the SM-XXXX part, `HTC One X10`/`HTC One M9` are models too, and same for `LG-V410/V41020c`. Those are the only ones with the vendor name on the user agent, but the vendor name is just part of the model, not a different field you can get.
