### ISSUE TITLE
bug: ionic-angular Platform resume event not firing anymore after upgrading to capacitor 3

### ISSUE THREAD

**Issue by hongfeiyang** [ionic-team/capacitor#4623]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 2.4.5
  @capacitor/ios: 3.0.0

[success] iOS looking great! 👌```

### Platform(s)
<!--
List the platforms that this bug affects.
-->



### Current Behavior
<!--
Describe how the bug manifests. Be specific.
-->

platform.resume does not fire after upgrading to capacitor 3, was working in 2.4.5

on iOS 14.5.1


### Expected Behavior
<!--
Describe what the behavior should be.
-->

resume event fire as usual. I don't want to use App.addListener('appStateChange' ...

### Code Reproduction
<!--
To isolate the cause of the problem, we ask you to provide a minimal sample application that demonstrates the issue.
For full instructions, see: https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction
-->



### Other Technical Details
<!--
Please provide the following information with your request and any other relevant technical details (versions of IDEs, local environment info, plugin information or links, etc).
-->

`npm --version` output:

`node --version` output:

`pod --version` output (iOS issues only):

### Additional Context
<!--
List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, etc.
-->

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by kevin-objectstudio** [comment]
I am also experiencing this issue. I added a listener for "appStateChange", as a means to work around the resume event not firing, however, "appStateChange" also triggers during biometric prompts, which creates a repetitive sequence and a poor experience for the user. 

The documentation provided here: https://capacitorjs.com/docs/apis/app, states this event will fire when the app goes into background / foreground, providing a boolean to determine this state change. I've tested with geolocation permissions, which doesn't trigger the appStateChange event., however biometrics seems to be different, specifically tested with face id, that triggers this event. 

Is there another way of determining what triggered this event, instead of just a boolean value?

**Comment by toxaq** [comment]
This was a problem on iOs in v2, I reported it: https://github.com/ionic-team/capacitor/pull/4454 

I don't know if it's actually made it into 3, I just find this whole ecosystem very flakey and constantly moving. Quick sand development.

**Comment by PhilippRoessner** [comment]
same here, this is not working on android. appStateChange doesn't fire as well

**Comment by hongfeiyang** [comment]
> same here, this is not working on android. appStateChange doesn't fire as well

I ended up developing another app with flutter, at least the lifecycle events are all good
