### ISSUE TITLE
feat: add capacitor.config.json to project gitignore files

### ISSUE THREAD

**Issue by bdirito** [ionic-team/capacitor#4626]
Projects do not ignore the `capacitor.config.json` as in their project directory. For example in android there is a `${PROJECTROOT}/android/app/src/main/assets/capacitor.config.json` which as far as tell is copied over from `${PROJECTROOT}/capacitor.config.json` as part of the `cap sync android` process.

If this is truly just copied over as part of the build process then presumably it would be better to add `capacitor.config.json` to the default project gitignore (`android/.gitignore`) in the same way that we also ignore things such as the copied web assets `app/src/main/assets/public`.

**Comment by gprossliner** [comment]
Hi! Just had the same issue!

> which as far as tell is copied over from...

If you are using a `capacitor.config.json` file then the output file in `${PROJECTROOT}/android/app/src/main/assets/capacitor.config.json` will be identical.

I an using an TypeScript config file `capacitor.config.ts`, like documented here: https://capacitorjs.com/docs/config#example
This allows me to use conditional configuration (basically enable server for dev). The output file will be the result of the execution of the .ts configuration file, so it is always `capacitor.config.json`.

Regardless if you use a .ts or .json configuration file. In my opinion this should be ignored by default. In my case it's even more disturbing, because you have a git change whenever you run a sequence of npm scripts.

I deleted the file and added a gitignore by myself:

```sh
rm android/app/src/main/assets/capacitor.config.json
echo "capacitor.config.json" >> android/app/src/main/assets/.gitignore
git add .
```

I'm unclear if this should not be classified as a bug.

**Comment by piotr-cz** [comment]
For the ios platform, path to generated file is `/ios/App/App/capacitor.config.json`
