### ISSUE TITLE
Is `cordova-plugin-blinkup` compatible with Capacitor? / `'BlinkUp/BlinkUp.h' file not found`

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/capacitor#4741]
Is the [cordova-plugin-blinkup](https://github.com/SensorShare/cordova-plugin-blinkup) compatible with Capacitor? I'm migrating a Cordova project to Capacitor and this plugin makes Xcode build fail because of `'BlinkUp/BlinkUp.h' file not found`:
<img width="1552" alt="Screen Shot 2021-06-18 at 14 19 15" src="https://user-images.githubusercontent.com/1189149/122579762-c536f980-d044-11eb-842c-b85757e9cc71.png">
I've created a repository with all the instructions: https://github.com/nunoarruda/capacitor-blinkup

**Comment by jcesarmobile** [comment]
You say it works on Cordova, but it doesn't really work if you don't do some manual steps, that's something a Cordova plugin should never ask the user to do because on Cordova the user projects are build artifacts.

What the plugin should do is to copy the `BlinkUp.framework` file inside `src/ios/` folder and add a framework tag in their `plugin.xml` like this `<framework src="src/ios/BlinkUp.framework" custom="true" />`, that way the SDK will be added by Cordova/Capacitor automatically without any manual changes on the projects.

Since it's a very out of date plugin, I doubt they will make such change, so you should fork the plugin and make those changes yourself and use your fork.
