### ISSUE TITLE
Gradle install fails, looking for the Android SDK in missing user folder

### ISSUE THREAD

**Issue by sdkester** [ionic-team/capacitor#484]
**Environment**

macOS 10.13.4  
node v8.9.3

**Issue**

I just installed the JDK v10.0.1. and Gradle was attempting to install after running `npx @capacitor/cli create`. The process ended with this error output. 

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> The SDK directory '/Users/max/Library/Android/sdk' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s

```

I looks like an [Android SDK folder setting](https://github.com/ionic-team/capacitor/search?utf8=%E2%9C%93&q=%2FUsers%2Fmax%2FLibrary%2FAndroid%2Fsdk&type=) is still hardcoded to @mlynch

**Comment by sdkester** [comment]
Oops, I see now that Capacitor wants JDK 8, not the latest. I'll see if that skips over the hardcoded values.

**Comment by jcesarmobile** [comment]
Did you install the Android SDK in a custom folder instead of `/Users/username/Library/Android/sdk`? 
add command (run on create) will check that folder and if it exists it will replace Max path with yours, but if it doesn't exist then it does nothing, and uses the default one. 
@mlynch Maybe we should delete the default one?

I don't think this is related to the java version, but still, as far as I know, Android development requires java 8. But by installing Android Studio, it should take care of everything, I did it recently in a new computer and everything worked

**Comment by sdkester** [comment]
@jcesarmobile I hadn't yet installed Android Studio. Android isn't one of my targets, so I was just trying to do the minimum to coax the create process through to the end. I wasn't sure if the Android failures were keeping anything else from completing. 

<later>

I installed the studio app and `create` is now completing without error. Sorry for the false alarm.

**Comment by jcesarmobile** [comment]
Ah, then it's related to this issue https://github.com/ionic-team/capacitor/issues/480

I think we shouldn't add ios and android when calling `create` and let the user add them later as we do with `init`

**Comment by sdkester** [comment]
Yes. Coming from cordova, I was expecting something along the lines of `npx cap add platform ios`

**Comment by jcesarmobile** [comment]
Yeah, we have `npx cap add ios`, `npx cap add android` and `npx cap add electron`, but create command was adding ios and android to the newly created project.
I've changed it to not add them and just log how to do it in case you are interested (as init command does)
