### ISSUE TITLE
Allow setting of hostname via code

### ISSUE THREAD

**Issue by NKZ15** [ionic-team/capacitor#4871]
I have the same issue as [https://github.com/ionic-team/capacitor/issues/3106](url) and I can't find a way to fix it with Capacitor 3.
Does anyone know how you can change configuration values in runtime? My usecase is exactly like @crixx .
@imhoffd  you had mentioned capacitor 3 will have this option available. Could you please guide me on how to change hostname with code? Thanks!

**Comment by NKZ15** [comment]
Thank you @thomasvidas for getting back to me quickly :) ! We have set the host name in our capacitor.config file so iOS doesn't block our API calls.  When we want to make a QA build we have to set our host name like example.qa and when we want to make a production build we set it like example.com. We want to be able to have one build and switch the environment within that build. for example we can have a drop down for the user to choose the environment. Since we 4 different environments we really need this feature. In issue# 3106 Dan had mentioned that with capacitor 3 we should be able to do so. but Unfortunately we had no luck achieving this. Can you help us understand what needs to be done?

**Comment by thomasvidas** [comment]
Gotcha, this is possible; but not exactly easy at the moment; hence the Portals product I am shilling since that would make it much easier 😄 

There are a couple ways you could do this...
- Create 4 separate `MyBridge` classes that all extend the `Bridge` class in Android and iOS. Then from there you tie them to an existing Activity or View and override the `getHostname()` functions to return based on whichever environment you are currently working in.
- Create a single `MyBridge` class that extends the `Bridge` class in Android and iOS and handle the reloading the whole app when the environment changes. It would probably work but be a little hacky, and would not be a good experience.
- Wait for the Ionic Portals project to come out and see if that fits your needs by adding separate "portals" for each of your environments.

IMO none of these are good solutions for most people since it involves a lot of native code writing, which defeats the purpose of Capacitor. It _is_ possible but we don't have good documentation right now on how to do that due to how niche this use case is. For examples of override the Bridge you can check out [BridgeActivity.java](https://github.com/ionic-team/capacitor/blob/bae0f3d2cee84978636d0f589bc7e2f745671baf/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java) and [CAPBridgeViewController.swift](https://github.com/ionic-team/capacitor/blob/2b7016f3b4d62fd8c9d03fde2745b3d515bf08b2/ios/Capacitor/Capacitor/CAPBridgeViewController.swift)

However, I think the best solution would be to have multiple environments via npm and then update your config object to read in environment variables (which is an improvement with Capacitor 3 as well!)

You can set up your `package.json` file to set some environment variables to run when running `npm run <command>`
```json
// package.json
...
"scripts": {
  "sync:qa": "ENVIRONMENT=qa npx cap sync",
  "sync:dev": "ENVIRONMENT=dev npx cap sync",
  "sync:prod": "ENVIRONMENT=prod npx cap sync",
}
...
```

Then in the capacitor config, you can read in the environment variable and set your hostname and app names dynamically when you sync doing something like this.

```typescript
// capacitor.config.ts
import { CapacitorConfig } from '@capacitor/cli';

let myHostname: string = "";
switch(process.env.ENVIRONMENT) {
  case "qa": myHostname= "example.qa"; break;
  case "dev": myHostname= "example.dev"; break
  case "prod": myHostname= "example.com"; break;
}

const config: CapacitorConfig = {
  appId: `com.example.${process.env.ENVIRONMENT}`,
  appName: `My App Name (${process.env.ENVIRONMENT})`,
  server: {
    hostname: myHostname,
  },
  ...
};

export default config;
```

So hopefully this is a better dev experience by letting you run `npm run sync:qa` and `npm run sync:prod` rather than trying to manage a new Capacitor bridge for every environment.

**Comment by crixx** [comment]
@thomasvidas me and @NKZ15 don't want to specify the ENV on build time, rather on execution time.

From a user perspective, it should be like this:
1. user installs the app which is build in a "not-production" mode
2. user select the env in the settings (user preferences) of the app
3. user opens the app, which then connects to the configured env from the settings

For production users, in the "production"-built version of the app, the settings are hidden and the production environment is configured as default.

> - Create 4 separate MyBridge classes that all extend the Bridge class in Android and iOS. Then from there you tie them to an existing Activity or View and override the getHostname() functions to return based on whichever environment you are currently working in.
> - Create a single MyBridge class that extends the Bridge class in Android and iOS and handle the reloading the whole app when the environment changes. It would probably work but be a little hacky, and would not be a good experience.

These two options are basically what we would like to do, but if you give a closer look at the bridge implementations, you see that there is no way to override or extend those to configure the host address before the webview loads. Or at least I think so. If there is a way, please elaborate more on this i.e where to override it and what…

**Comment by jcesarmobile** [comment]
The hostname is set on bridge creation, so it won't be possible to change it programmatically in Capacitor after the bridge is created.
It can be set programmatically before the bridge gets created, but that doesn't look like what you want.
Capacitor will only have a WebView and its configuration can't be changed at runtime.

What you want should be possible with Portals, as you should be able to create new bridge/WebView with the new hostname values.

**Comment by crixx** [comment]
> It can be set programmatically before the bridge gets created
How?
