### ISSUE TITLE
bug:  Path when loading assets adds <AppName> which results in failure to load assets

### ISSUE THREAD

**Issue by cgado12** [ionic-team/capacitor#4874]
### Capacitor Version

<img width="220" alt="Screen Shot 2021-07-28 at 1 39 10 PM" src="https://user-images.githubusercontent.com/5099827/127588329-418d83e5-20aa-408b-a439-716fa436d8ae.png">

### Platform(s)

* Android
* IOS

### Current Behavior

I have a react/typescript application where I am adding capacitor and pointing to the build directory to create android and ios versions of the app. When opening the apps in their respective editors and then running the apps - after the splash screen there is only a white screen. 
Logcat/the debugger shows the following issues: 
<img width="819" alt="Screen Shot 2021-07-28 at 1 12 07 PM" src="https://user-images.githubusercontent.com/5099827/127588594-1b16054e-1581-46cb-9092-a172d72aa8de.png">

### Expected Behavior

Assets should have loaded normally and there should not be the apps name in the url printed above. the URL should point to `localhost/public/static`.... , unless the goal is for cap to generate the <appname> folder to put static assets in.
Additionally the android/ios emulator should have shown my application.

I have gotten things working by updating the following code within `WebViewLocalServer.js` around line 481 in android.
It would be here: https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java#L479
<img width="467" alt="Screen Shot 2021-07-28 at 1 12 40 PM" src="https://user-images.githubusercontent.com/5099827/127588871-97172268-95e1-43a2-8d41-ca628dc9d924.png">
NOTE: my apps name is "Twenty48" 

### Code Reproduction

* Create a react/typescript app with create-react-app.
* run `npm run build`
* install capacitor/cor cli and android
* run `npx cap init` and use the default entries
* run `npx cap add android`
* run `npx cap run android` OR `npx cap open androd` and run the app

### Other Technical Details

`npm --version` output:
* 6.14.13
`node --version` output:
* v14.17.3
`pod --version` output (iOS issues only):
* 1.10.1

**Comment by thomasvidas** [comment]
This is a feature, it is to "namespace" your app in a way should some other app on the device be running a similar way. You can specify what url to load from via the [Capacitor Config](https://capacitorjs.com/docs/config). Specifically the `server.url` variable and setting that to just http://localhost/public/static.

Also in your reproduction, you do not specify to sync the web assets. This places the files from your build into the location that Capacitor expects them to be in the native project so that you don't have to set `server.url`

**Comment by thomasvidas** [comment]
I am mistaken! I was mixing up another project/feature we are working on. Can you provide a sample app that reproduces this issue?

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by cgado12** [comment]
@thomasvidas Apologies for the delay and no problem! I appreciate your response to the issue and the work you do.  :) 
However, I have stumbled onto the culprit of my issue and it seems it was the `"homepage"` field within my package.json.  I am starting to suspect that the issue is a lack of my understanding of the homepage field, as well as how capacitor reacts to that field within a package.json.

I have created a test repo here: [testRepo](https://github.com/cgado12/test-cap/blob/master/package.json#L4) ; where you can run `npm install && npm run build && npx cap sync`.  This will result in error due to the homepage field in the package.json.   
Remove the "homepage" field in the package.json and everything runs fine.  If deeper instruction is needed, pls lmk.

**Comment by jcesarmobile** [comment]
Yeah, the homepage field makes url relative to a non existen folder and that causes the issue with Capacitor because Capacitor expect the files to be on the root and folders to exist.
By setting the homepage, react is prepending /Twenty48/ to every css, js, img, etc. link/src/href and that breaks the app because the Twenty48 doesn't really exist.

https://create-react-app.dev/docs/deployment/#building-for-relative-paths
