### ISSUE TITLE
bug: When I upgrade v2 to v3 ios popup a bottom sheet with no meaning

### ISSUE THREAD

**Issue by GHChrisSu** [ionic-team/capacitor#4898]
## Bug Report
When I upgrade v2 to v3, ios show bottom sheet it was not happened in android platform
Might be some setting about browser, and it's view is not in inspector of safari

### Capacitor Version
v3.1.2

### Platform(s)
ios

### Current Behavior

![Lark20210806-133846](https://user-images.githubusercontent.com/13779988/128456787-fb26fccd-a678-4323-8f8c-82f6b0d86f60.png)

### Expected Behavior
without bottom sheet

`npm --version` output:
7.7.6
`node --version` output:
v15.13.0
`pod --version` output (iOS issues only):
1.10.1

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by salohcin714** [comment]
I have experienced this before and seems like a bug with the iOS simulator. It is having issue displaying software keyboard. I usually can fix this by going to Simulator > I/O > Keyboard and toggling off and on Connect a Hardware Keyboard. The simulator is expecting you to use your computer's keyboard instead of the device keyboard.

**Comment by jcesarmobile** [comment]
Thanks for the input

Yeah, looks like that's just the keyboard accessory input bar that appears when the you focos an input and since it expects a HW keyboard it doesn't show the full keyboard but just the bar.

In Capacitor 2, since all plugins were included, the keyboard plugin removes that bar by default, now with Capacitor 3 users have to manually install @capacitor/keyboard package if they want to hide the bar or use any other of the keyboard methods or events.
