### ISSUE TITLE
Lack of clarity about what should be pushed to github repository.

### ISSUE THREAD

**Issue by wtrocki** [ionic-team/capacitor#501]
Hi

I have been playing with capacitor for a while and I think that it's best to add info to documentation to clarify what resources created by cli should be pushed back to repository. For example:

```All generated platform source code could be ignored when pushing changes to repository. If you intend to change or add any code to native platforms then android/ios folders should be published.```

Can I assume that this statement is true?

For example for Apache Cordova plugins and platforms folder should not be pushed to repository. While this seems trivial issue it could help with better adaptation of the framework.

**Comment by mlynch** [comment]
You can ignore the native project, but Capacitor never modifies your actual native project, and you won't need to blow out the platform folders and recreate them. As for your last sentence, the approach we take makes it much easier to track native changes, since the tooling isn't modifying it for you.
