### ISSUE TITLE
bug: Setting the iOS Scheme in Config Prevents Deploying - Upgrading to Capacitor 3

### ISSUE THREAD

**Issue by allidoisace** [ionic-team/capacitor#5131]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.2.4
  @capacitor/core: 3.2.4
  @capacitor/ios: 3.2.4

[success] iOS looking great! 👌
```

### Platform(s)

Building for iOS on Macbook.

### Current Behavior

Setting the `capacitor.config.ts` to include the `scheme` name causes this issue. If I do not use the `scheme` it fails to find a `scheme = App`. I have upgraded from Capacitor 2, so there is something different which is causing this problem.

### Expected Behavior

Should finish building/deploying and open Xcode.

### Code Reproduction

```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.myapp.myapp',
  appName: 'myapp',
  webDir: 'build',
  plugins: {
    SplashScreen: {
      launchShowDuration: 0,
    },
  },
  ios: {
    scheme: 'MyApp',
  },
};

export default config;
```

### Other Technical Details

`npm --version` output: 7.21.1

`node --version` output: v16.9.1

`pod --version` output (iOS issues only): 1.11.2

### Additional Context

https://github.com/ionic-team/capacitor/pull/4073
This change sets:
```
const appName = `${config.ios.scheme}.app`;
```
where the assumption is that the generated Build name for the app is the same as the scheme that was set. I don't know if this is really correct, since I am coming from Capacitor 2 and I cannot build and deploy my app using the config change for scheme. If I don't use the scheme change, `xcodebuild` fails. 

The output in my `Build/Products/Debug-iphoneos/` is `App.app`. Not quite sure how to change this or why this worked before.

**Comment by allidoisace** [comment]
This forces the `scheme` name to be the same as the `target` name. I don't know if this should be a thing or not.

**Comment by jcesarmobile** [comment]
The scheme is used for run command, capacitor 2 didn’t have a run command nor the scheme setting. Can you provide a sample app?

**Comment by jcesarmobile** [comment]
When you create a target it also creates a scheme, if you rename the target the scheme is also renamed.
What is not supported is to have more schemes than targets or renaming the scheme but not the target because the scheme and the target names must match.

Again, this is only used for run command that was added as an alternative way of running the apps from the CLI while in development and we allow to configure the scheme in case the user renames the target, but run command doesn't want to cover all possible cases, for more complex scenarios you can always run from Xcode.
