### ISSUE TITLE
bug: onesignal - The 'Pods-App' target has transitive dependencies that include

### ISSUE THREAD

**Issue by nowrap** [ionic-team/capacitor#5142]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/android: 3.2.5
  @capacitor/ios: 3.2.5

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.2.5
  @capacitor/core: 3.2.5
  @capacitor/ios: 3.2.5

[success] iOS looking great! 👌
```

### Platform(s)

ios

### Current Behavior

A `npx cap sync` creates this error:
> [!] The 'Pods-App' target has transitive dependencies that include
statically linked binaries:
(/mobileapp/ios/App/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework)

This is related to:
https://github.com/ionic-team/capacitor/pull/5099
https://github.com/ionic-team/capacitor/issues/5137

A downgrade to @capacitor/cli version 3.2.4 solves this issue

### Expected Behavior

That the sync runs without error

### Code Reproduction

Assuming cocoapods are installed and synced:

```
ionic start myApp tabs --type vue

cd myApp
npm install @capacitor/ios
npx cap add ios

npm install onesignal-cordova-plugin@2

npm run build
npx cap sync
```

### Other Technical Details

`npm --version` output: 8.1.0

`node --version` output: v14.18.1

`pod --version` output (iOS issues only): 1.11.2

macOS: 11.6

xcode: 13.0

**Comment by jcesarmobile** [comment]
I can reproduce now, I was installing version 3 and the issue is not reproducible there.
We can't really filter per plugin version, so I'll just add it anyway despite it's not needed for version 3.

**Comment by nunoarruda** [comment]
This problem is back, at least for me, after upgrading `@capacitor/cli` from v3.3.0 to v3.3.2:

<img width="1420" alt="Screenshot 2021-11-22 at 13 55 16" src="https://user-images.githubusercontent.com/1189149/142883173-75f06dda-8ac0-4cbc-96ad-1ee1c15de4b9.png">

Git shows me that the CLI is trying to delete the following line in the Podfile:

<img width="841" alt="Screenshot 2021-11-22 at 13 57 23" src="https://user-images.githubusercontent.com/1189149/142883503-785183d0-90cf-4954-8a71-18a418880410.png">

**Comment by jcesarmobile** [comment]
Please, when you find a bug, report an issue, don't comment on closed issues because they are not monitored, I usually unsubscribe after closing the issues.

In 3.3.2 we made the CLI to autodetect plugins that needs a static framework if they have `use-frameworks="true"` in the pods tag, and since [OneSignal plugin had it](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/main/plugin.xml#L79), I removed it from the list.
But turns out version 2 didn't use the pods tag, so we'll need to put it back in the list.

Anyway, since 3.3.0 you can add any plugin you want to the static list from the capacitor config file without waiting for us to add it, you don't need to downgrade. Use the staticPlugins array inside the cordova object https://capacitorjs.com/docs/config
