### ISSUE TITLE
bug: Android - Cant download files into Directory.Documents

### ISSUE THREAD

**Issue by elvisgraho** [ionic-team/capacitor#5218]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 3.3.1
  @capacitor/core: 3.3.1
  @capacitor/android: 3.3.1
  @capacitor/ios: 3.3.1

Installed Dependencies:

  @capacitor/core: 3.3.0
  @capacitor/cli: 3.3.0
  @capacitor/ios: 3.3.0
  @capacitor/android: 3.3.0
```

### Platform(s)
Android 11

### Current Behavior
Cant download and save files into Directory.Documents directory. 'open failed: EACCES (Permission denied'

### Expected Behavior
To work without errors

### Other Technical Details
Emulators work just fine, the live device throws error. Changed to Directory.Data and everything works fine.

People who use Capacitor should not know that this doesn't work on that or other device. If something does not work on all devices, why have it at all?

**Comment by jcesarmobile** [comment]
> People who use Capacitor should not know that this doesn't work on that or other device.
They should if they read the docs:
https://capacitorjs.com/docs/apis/filesystem#android
> Note that Directory.Documents and Directory.ExternalStorage are only available on Android 9 or older.
https://capacitorjs.com/docs/apis/filesystem#enums

> The Documents directory On iOS it’s the app’s documents directory. Use this directory to store user-generated content. On Android it’s the Public Documents folder, so it’s accessible from other apps. **It’s not accesible on Android 10 unless the app enables legacy External Storage by adding android:requestLegacyExternalStorage="true" in the application tag in the AndroidManifest.xml. It’s not accesible on Android 11 or newer.**

> If something does not work on all devices, why have it at all?

Because Capacitor was created 4 years ago when Android 10 was not out yet and that limitation didn't exist. Same thing as if a new feature comes out and people need it, such as channels on notifications, we add support for it despite it only works on Android 26+ and we still support Android 21+. It's not our fault that Android have that massive fragmentation and add those kind of policies on each Android update.

**Comment by elvisgraho** [comment]
Ok thanx my fault
