### ISSUE TITLE
Android Studio - Library projects cannot set applicationId

### ISSUE THREAD

**Issue by smelzer** [ionic-team/capacitor#531]
I tried to add Android support to a Capacitor app that is working in with iOS and am getting a build error after adding Android and opening Android Studio.

I run 'npx cap add android' and then 'npx cap open android'.  I get the following error during the gradle build process:
`Library projects cannot set applicationId. applicationId is set to 'capacitor.android.plugins' in default config.`
from the `../node_modules/@capacitor/cli/assets/capacitor-android-plugins/build.gradle` file.

When I look at the file there is no direct reference to an applicationId, although I do understand much of the build is dynamic.  I see a reference to the applicationId set in common.ts:
`
// Update the applicationId in build.gradle
let gradleContent = await readFileAsync(buildGradlePath, 'utf8');
gradleContent = gradleContent.replace(/applicationId "[^"]+"/, `applicationId "${appId}"`);
`
but this appears to be for App/build.gradle and not capacitor-android-plugins/build.gradle.

My app is using the PhonegapPluginPush and the CordovaPluginTelerikImagepicker plugins.  I am using the latest CLI, alpha-37 and Android Studio 3.1.2.

Any thoughts of why this error is showing?

Thanks,
Steve

**Comment by ttibau** [comment]
I've same problem, do you fixed it?

**Comment by jcesarmobile** [comment]
The problem is the phonegap-plugin-push, it has a gradle file that sets applicationId. That doesn't cause problems on Cordova because the plugin's code is on the same project as the app, but we put it in a different project (Library project) and causes the problem.
I've send a PR to the push plugin because the code for setting the applicationId is no longer needed.

As workaround you can edit the `node_modules/phonegap-plugin-push/push.gradle` and remove the `applicationId = doExtractStringFromManifest("package")`

**Comment by vokamut** [comment]
My fix: https://github.com/ionic-team/capacitor/issues/2511#issuecomment-1290020640
