### ISSUE TITLE
feat: Enable pwa elements in mobile

### ISSUE THREAD

**Issue by JSilva6** [ionic-team/capacitor#5341]
### Description
For a long time, my app had problems with the Cordova Camera Plugin, where in many devices, it would simply reset the app when put in background for various reasons. I have been looking into alternatives, until I migrated into capacitor, just to figure out that the PWA Camera that wont put the app in the background to sleep and potentially die wont work in the mobile.

Why wouldnt capacitor simply allow to disable native features for specific plugins? If I wanted to use the PWA shell to wake the camera in HTML up instead of opening the default phone camera, that would solve the entire problem.

### Platform(s)
Every. Single. One.

### Preferred Solution
Just add an option to disable native operations for some plugins.

**Comment by jcesarmobile** [comment]
Thanks, but we are not removing the native implementation of the camera plugin because the web implementation lacks of some of the features.
You can use PWA elements directly if you want instead of using the camera plugin.

Also, have in mind that on iOS getUserMedia was implemented on iOS 14.4 for WKWebView (if I recall correctly), so on iOs 12-14.3 it won't work, and even on 14.4 had some issues, so I wouldn't use it unless the device is on iOS 15.
