### ISSUE TITLE
feat: update gradle

### ISSUE THREAD

**Issue by nakrout** [ionic-team/capacitor#5342]
## Feature Request
Update gradle 

### Description
Update gradle to newer version. Current version is 4.2.1

### Platform(s)
Android

### Preferred Solution
Upgrade gradle from 4.2.x to 7.0.x

### Alternatives
n/a

**Comment by jcesarmobile** [comment]
Thanks for the issue. This is already planned for Capacitor 4.
We can't do major dependency updates as a minor or patch release because they usually introduce breaking changes, so it needs to wait for Capacitor 4.
Users can update to the version they wish, Android Studio usually prompts to use latest when a new version comes out, but on their own risk as some things might break.
