### ISSUE TITLE
bug: Gradle wrong version in android-template

### ISSUE THREAD

**Issue by riderx** [ionic-team/capacitor#5371]
### Capacitor Version
As recomended here : https://capacitorjs.com/docs/updating/3-0#update-gradle-to-70
Gradle should be in version 7 in all capacitor 3 project but when create a fresh android  it's not the case it's 4.2.1
like here  https://github.com/riderx/capacitor/blob/main/android-template/build.gradle

### Platform(s)
Android

### Current Behavior
Create android platform init project with gradle 4.2.1

### Expected Behavior
Create android platform  should init project with gradle 7.0.4

**Comment by jcesarmobile** [comment]
Gradle plugin and gradle wrapper are different things, when we launched capacitor 3, 4.2.1 was latest version of gradle plugin, so that’s the version we used. Gradle wrapper was 7 and that’s what the docs talk about when they say you have to update to version 7. We can’t do a major version bump as a patch or minor release because it can produce breaking changes.
Updating gradle plugin and gradle wrapper is a planned task for capacitor 4 release.

**Comment by riderx** [comment]
@jcesarmobile thanks for the feedback, i didn't know the difference.
