### ISSUE TITLE
bug: App > Public source code isn't detected whenever server url is removed from capacitor.config.json

### ISSUE THREAD

**Issue by eudzb** [ionic-team/capacitor#5403]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.4.0
  @capacitor/core: 3.4.0
  @capacitor/ios: 3.4.0

[success] iOS looking great! 👌
```

### Platform(s)

- [x] iOS
- [ ]  Android
- [ ]  Electron
- [ ] Web

### Current Behavior

We have a PWA app developed with Angular 9. We're using capacitor mainly to be able to use features like push notifications and to be published in the AppStore. We encounter an issue whenever we’re trying to run our app on an iOS device. The screens loads but the environment url is not our server url but is instead "capacitor://localhost". It means none of our api (urls) works. On the other hand we are able to run our app whenever we are using server { url: … }. But for a better practice we would like to be rid of server { url:… }. What is the best approach when facing this issue?

### Expected Behavior

It should work even without using server { url }. The main public source should be used instead of the remote folder.

```
npm --version output: 6.14.7

node --version output: v12.14.0

pod --version output (iOS issues only): 1.11.2
```

**Comment by jcesarmobile** [comment]
if you load from the local assets the url has to be capacitor://localhost, you can change the scheme and hostname if you want, but you can't use http/https because it's not allowed by Apple as WKWebView handles those and expect them to be an external server.
If you use server.url then it will use the remote assets instead of the local assets, because as I said, that's handled by the WKWebView directly and we can't intercept it to load the local assets.
