### ISSUE TITLE
ionic 6 capacitor 3 onesignal 3.0.1 ERROR – "plugin_not_installed"

### ISSUE THREAD

**Issue by zubinraja** [ionic-team/capacitor#5417]
Followed onesignal plugin documentation and OneSignal SDK documentation to implement push notification with onesignal.
But while running app getting  "plugin_not_installed" error as below.
Documentations link:
ionic: https://ionicframework.com/docs/native/onesignal
onesignal: https://documentation.onesignal.com/docs/ionic-sdk-setup

Warning asks to install Cordova Plugin inside capacitor!

Screenshot of error 
![Screen Shot 2022-02-08 at 11 28 52 PM](https://user-images.githubusercontent.com/21122914/153047863-8cfd51b5-e61f-4272-80ca-d181debf01c3.png)

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by zubinraja** [comment]
Hello,

below is public git repo that demonstrates the error.
https://github.com/zubinraja/CapacitorOnesignalTest

Thanks!
Zubin

**Comment by jcesarmobile** [comment]
The bug is in the `@awesome-cordova-plugins/onesignal`, not in Capacitor. The onesignal plugin did a major update back in August with [a few breaking changes](https://documentation.onesignal.com/docs/mobile-2020-api-migration-guide) and the types have not been updated accordingly yet, but the error message is misleading.
It was [reported](https://github.com/danielsogl/awesome-cordova-plugins/issues/3722), but the issue was closed because of inactivity.

The plugin has its own types now, so you can probably use them instead of `@awesome-cordova-plugins/onesignal`, you can check [their docs](https://documentation.onesignal.com/docs/ionic-sdk-setup).

**Comment by markCornejo** [comment]
I am adding below code in Angular/Ionic 6:

import OneSignal from 'onesignal-cordova-plugin';
...
...
configurateInit(){

    OneSignal.setAppId("xxxxxx-xxx-xxxxxx");
    
    // get data when opening notification
    OneSignal.setNotificationOpenedHandler((data) => {

    });

    // Prompts the user for notification permissions.
    OneSignal.promptForPushNotificationsWithUserResponse(function(accepted) {
       
    });

    // set device data when loading app
    OneSignal.getDeviceState((data) => {
     
    });
  }

**Comment by INARTECHSA** [comment]
@markCornejo with the code you provided, building in xCode it gives me this error:

![error](https://user-images.githubusercontent.com/105000467/188863737-bc0c05f6-21f7-4df0-9f84-4abb1f2bd198.png)
