### ISSUE TITLE
Plugin native event system

### ISSUE THREAD

**Issue by mlynch** [ionic-team/capacitor#55]
One difference between Capacitor and Cordova is that Cordova copies your source files directly next to your app source files. This makes it possible for plugins to do things, like, extend `AppDelegate`. We don't allow that as plugins are provided through linked frameworks that don't have access to app source. 

To work around this, we should think about an abstracted native event handling system that makes it easy for a plugin to handle an AppDelegate method without having to do any extensions or anything.

**Comment by mlynch** [comment]
Similarly, figure out a custom app delegate. Facebook does theirs like this:

https://github.com/facebook/facebook-sdk-swift/blob/82d4f4bc4226bd9d0494a604cb2f39632f6a0b57/Sources/Core/Common/SDKApplicationDelegate.swift
https://github.com/facebook/facebook-sdk-swift/blob/master/Samples/Catalog/Sources/AppDelegate.swift

**Comment by mlynch** [comment]
Added the delegate in 80197c77425957ab834f43a2f50df497b65dc04e

**Comment by jcesarmobile** [comment]
A lot of AppDelegate events emit a notification, see the Notifications section of https://developer.apple.com/documentation/uikit/uiapplication.

So plugins can subscribe to them in load method.

For the ones not available we should do it ourselves in the class you created

**Comment by jcesarmobile** [comment]
Going to close as we propagate some of the AppDelegate methods and others are emitted by iOS itself in notification center.
If we need any other in particular better create a separate issue.

**Comment by RoopeHakulinen** [comment]
Hey @jcesarmobile & @mlynch 

If I understand the consequences of this correctly, it means that Cordova plugins that require AppDelegate access won't work at all with Capacitor. I cannot see any way to make this happen with even development done on the plugin's code itself. Could you please confirm this so I can spare my time instead of trying to make the plugin compatible with Capacitor?

I'm just implementing iOS support (as v13 adds the NFC functionality) for [cordova-plugin-mifare-ultralight](https://github.com/RoopeHakulinen/cordova-plugin-mifare-ultralight) and would like it to work with the Capacitor too as the latest apps of ours are using it instead of Cordova.
