### ISSUE TITLE
feat: Auto select the device if only one is in the list.

### ISSUE THREAD

**Issue by twoco** [ionic-team/capacitor#5539]
Great that Capacitor now runs via CLI. Thanks. I'm new to Capacitor, coming from Cordova. But it looks promising. To the issue:

This command: 
`ionic capacitor run android` ([docs](https://ionicframework.com/docs/cli/commands/capacitor-run))
forces me to select a device. Even if only one device exists.

I know the `--target` arg. But I don't want to specify the ID. Just pick the only one existing device from list.
If `deviceList.length === 1` then automatically select this one. This can be an additional arg like `--target-auto`.

**Comment by darkguy2008** [comment]
+1 to this. Considering how the Ionic team has been pushing us to use Capacitor instead of Cordova, selling it as the next-best-thing™️, it's staggering to see an essential feature like this non-existant as of yet.

**Comment by Sulorb** [comment]
+1, I'd like to save this half second each time i want to run the app.

In fact it's way more than half second because I used to do something else when I ran Cordova on device knowing it takes time to compile, but starting on Capacitor from today I realize only after that it wasn't compiling because I didn't press enter to choose the device.

**Comment by van9petryk** [comment]
+1

**Comment by jcesarmobile** [comment]
This is already part of Capacitor CLI, but you are using the Ionic CLI to run, so you should report it there https://github.com/ionic-team/ionic-cli

**Comment by Sulorb** [comment]
Found a solution: just double tap ENTER and it will automatically choose the first device.
