### ISSUE TITLE
bug: FileSystem cannot append when no encoding is selected

### ISSUE THREAD

**Issue by muuvmuuv** [ionic-team/capacitor#5541]
## Bug Report

When appending to a file where no encoding is selected, in web I get no errors due to it fallbacks to UTF-8, but in iOS and Android I get an error due to base64 encoding "Unable to append file". Data that is appended does seem to be correctly encoded.

### Capacitor Version

```

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3
  @capacitor/core: 3.4.3
```

### Current Behavior

It throws on native with "Unable to append".

### Expected Behavior

Append string to base64 data.

### Code Reproduction

https://github.com/muuvmuuv/issue-5541

```ts
await Filesystem.appendFile({
        path: this.path,
        directory: Directory.Data,
        data: "data" + "\n",
})
```

### Other Technical Details

`npm --version` output: latest

`node --version` output: 17

`pod --version` output (iOS issues only): 1.11.3

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by muuvmuuv** [comment]
@jcesarmobile I have added a repl :) I always create the issue first with minimum repl to get the issue ID

**Comment by jcesarmobile** [comment]
This is the expected behavior, if no encoding is provided it will try to write as base64, but the string should be encoded as base64 beforehand, the plugin will not do any encoding for you nor fallback to UTF-8.
It works on web because the writing is done the same way for encoded and not encoded strings, but if they are encoded it will fail on subsequent appends (will report a separate issue for that)

> The encoding to write the file in. If not provided, data is written as base64 encoded. Pass Encoding.UTF8 to write data as string

https://capacitorjs.com/docs/apis/filesystem#appendfileoptions

So if you want to write strings you should pass the encoding, if you want to write base64 you should pass base64 string and no encoding.
