### ISSUE TITLE
feat: load plugin classes in `BridgeFragment` 

### ISSUE THREAD

**Issue by wokkaflokka** [ionic-team/capacitor#5564]
### Description

`BridgeActivity` calls `loadPluginClasses()` in `onStart` and registers/loads the plugins it [finds](https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java#L100-L110).

`BridgeFragment` does not provide this behavior. BridgeFragment can be subclassed to add this functionality, but it would be preferable if this were in the base implementation.

### Platform(s)
Android

### Preferred Solution
Update the `load` method in `BaseFragment` to load plugins using the same technique as `BridgeActivity`.

### Alternatives
Sub-classing.

**Comment by jcesarmobile** [comment]
This is on purpose, while a regular Capacitor app, which only has a `BridgeActivity` should make all plugins available to the app, when using `BridgeFragment` you might want to make available only certain plugins depending on the fragment, since you can have several `BridgeFragment`s with different code that would be using different plugins.
