### ISSUE TITLE
feat: allow applications to set a higher min SDK version number

### ISSUE THREAD

**Issue by adnbrownie** [ionic-team/capacitor#5569]
### Description
This request is related to the last comment in [issue 4865](https://github.com/ionic-team/capacitor/issues/4865): currently, it is not possible to set the Android `minSdkVersion` to something higher than API version 23. While Capacitor supports older versions just fine, there might be other reasons for an application to choose to support only newer versions of Android.

### Platform(s)
Android

### Preferred Solution
Disable the linting rule for obsolete SDK checks altogether using `disable 'ObsoleteSdkInt'` in https://github.com/ionic-team/capacitor/blob/main/android/capacitor/build.gradle#L44

### Alternatives
Alternatively there'd be the option to add issues stemming from the SDK version checks to the lint-baseline.xml file. This would mean that if new SDK version checks are introduced at a later point in time, they need to be added to the lint-baseline.xml file as well.

### Additional Context
- [issue 4865](https://github.com/ionic-team/capacitor/issues/4865)
- https://developer.android.com/studio/write/lint#pref
- https://developer.android.com/studio/write/lint#snapshot

**Comment by jcesarmobile** [comment]
I've tried setting the `minSdkVersion` to 29 and I can still build, can you provide a sample app and steps to reproduce?

**Comment by adnbrownie** [comment]
Hi @jcesarmobile, thanks for looking into this and sorry for the late reply, I was on vacation. I will try to provide a sample app to reproduce the issue towards the end of this week.

**Comment by wokkaflokka** [comment]
The feature requested by the title of this issue is already supported, I believe. My application sets a minimum SDK of API 26 and is building constantly under CI/CD with no issues. 

It's possible to change the minimum SDK version by assigning `minSdkVersion` to the version you desire. Also, given that capacitor apps are native apps, one could always completely override the default build configuration and set the min SDK version a different way. The minimum SDK version of an Android application is defined by the application itself, not by its dependencies.

**Comment by jcesarmobile** [comment]
Closing as there was no response and I can't reproduce.
Also, as wokkaflokka said, you can always set the minSDK for the app only instead of changing the `minSdkVersion` in variables.gradle and that would only affect the app, but not the modules (such as @capacitor/android and the plugins).
