### ISSUE TITLE
bug: Execution failed for task ':app:processDebugMainManifest'.

### ISSUE THREAD

**Issue by francoism90** [ionic-team/capacitor#5702]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0

[success] Android looking great! 👌
```

### Platform(s)
Arch Linux

### Current Behavior
```
Execution failed for task ':app:processDebugMainManifest'.
        > Manifest merger failed : Apps targeting Android 12 and higher are
        required to specify an explicit value for `android:exported` when the
        corresponding component has an intent filter defined. See
        https://developer.android.com/guide/topics/manifest/activity-element#exported
        for details.
```

### Expected Behavior
Just build

### Other Technical Details

`npm --version` output: 8.5.5

`node --version` output: v18.3.0

`pod --version` output (iOS issues only):

### Additional Context
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
OpenJDK 64-Bit Server VM (build 11.0.12+0-b1504.28-7817840, mixed mode)

**Comment by francoism90** [comment]
https://stackoverflow.com/questions/67412084/android-studio-error-manifest-merger-failed-apps-targeting-android-12

Should Capacitor create this by default or is this an user setting?

**Comment by jcesarmobile** [comment]
Capacitor 3 officially supports to target SDK 30, if you want to use 31-32 you should wait for Capacitor 4, will be released soon, we released the first beta last Friday and a few alphas before that.
When you run `npx cap add android` using the beta it already adds the exported, but for existing apps users will have to add that part manually since Capacitor never modify user apps, we will document that on the capacitor 3 to 4 upgrade guide.

**Comment by francoism90** [comment]
@jcesarmobile Thanks for your detailed answer! I'll test Capacitor 4  as I'm indeed seem to target 31-32. :)
