### ISSUE TITLE
bug: Capacitor 4 shows an incorrect default splash screen

### ISSUE THREAD

**Issue by m3thom** [ionic-team/capacitor#5813]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/ios: 4.0.1
  @capacitor/android: 4.0.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

`Android`

### Current Behavior

Please see the top-left corner in the below picture.
![Screenshot_2022-08-01-17-58-55-15_8e8dd22025896c1d7c28dde44f899fc8](https://user-images.githubusercontent.com/39703347/182134098-3ad20f28-ff56-42c7-ac9c-f42dfe5188a0.jpg)

### Expected Behavior

The splash screen should correctly show similarly the project that creates with Capacitor 3.

### Code Reproduction

Here is the repo https://github.com/m3thom/ionic-splash-screen

### Other Technical Details

`npm --version` output: 8.3.0

`node --version` output: v14.17.0

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
You mean that it shows your app name on the top left?
I can't reproduce that.
In which device and Android version are you testing?

**Comment by m3thom** [comment]
> You mean that it shows your app name on the top left? I can't reproduce that. In which device and Android version are you testing?

I'm testing on my physical device which is the OnePlus 8 pro with Android version 12.

**Comment by jcesarmobile** [comment]
Can you also answer the other question?
> You mean that it shows your app name on the top left?

**Comment by m3thom** [comment]
> Can you also answer the other question?
> > You mean that it shows your app name on the top left?
> 

Oh, sorry, yes it is.

**Comment by jcesarmobile** [comment]
I can't reproduce on my Android 12 device (pixel 6), in Android 12 should show the app round icon, not the splash image that it used to show in Capacitor, that's the new [Android 12 Splash Screen](https://developer.android.com/guide/topics/ui/splash-screen) OS behaviour.

I've tested in several models with Android 12 and in Pixel models is works as expected, but on Samsung it's not working as expected (the behaviour is still different than yours, but not what is expected). I understand that as a bug on the devices, not in Capacitor, phone vendors installing Android 12 on their devices should be respecting the new Android 12 Splash Screen API instead of doing their custom things and looks like that's what One Plus is also doing.

You can try changing ` <style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">` back to `<style name="AppTheme.NoActionBarLaunch" parent="AppTheme.NoActionBar">`, but I doubt it will change anything.

You can also try removing `<item name="android:background">@drawable/splash</item>` and playing with other values like the explained on the [Android 12 Splash Screen API page ](https://developer.android.com/guide/topics/ui/splash-screen#set-theme)and see if One Plus respect those.
But sadly there is nothing we can do about it if vendors don't respect the OS or don't implement its features correctly.

**Comment by mirko77** [comment]
@jcesarmobile 
On a Samsung A33, Android 12, the splash screen does not show at all with Capacitor 4, but no problems with Capacitor 3.
However, I do notice the same with other apps (Amazon, Outlook, Waze, even the Google ones...)

**Comment by DennisHerr** [comment]
> @jcesarmobile
> On a Samsung A33, Android 12, the splash screen does not show at all with Capacitor 4, but no problems with Capacitor 3.
> However, I do notice the same with other apps (Amazon, Outlook, Waze, even the Google ones...)

Did you find a config or a programmatical solution to this problem with capacitor 4?

**Comment by mirko77** [comment]
> > On a Samsung A33, Android 12, the splash screen does not show at all with Capacitor 4, but no problems with Capacitor 3.
> > However, I do notice the same with other apps (Amazon, Outlook, Waze, even the Google ones...)
> 
> Did you find a config or a programmatical solution to this problem with capacitor 4?

No, it depends on the device OS, on another Android 12 with Lineage OS it sort of works (shows the app icon as a splash screen instead of the splash.png) so we'll live with that for the time being.

**Comment by sorenjuul** [comment]
I have tried to solve this issue for weeks now and have found no solution. 

I have the exact same issue described here on a OnePlus 8T with Android 12.

This makes upgrading to Capacitor 4 a no go for me.

Hope someone finds a solution.

**Comment by jcesarmobile** [comment]
This is a bug on OnePlus devices, they shouldn't show your app name on the Splash Screen. It's the OS doing it, not the plugin.

Looks like you can remove it by adding this to your `Theme.SplashScreen` style
```
    <item name="android:windowNoTitle">true</item>
    <item name="android:windowFullscreen">true</item>
```

**Comment by jlebras** [comment]
I had the same problem with an OPPO A94 5G on Android 12 (App name showing on the top left + a flattened app icon...)
Fixed it by reusing my old splashscreen drawable as the android:background and by adding
```
<item name="android:windowNoTitle">true</item>
```
to the splashscreen theme.
This is what the final theme looks like:
```
<style name="AppTheme.NoActionBarLaunch" parent="Theme.SplashScreen">
    <item name="android:background">@drawable/splash</item>
    <item name="android:windowNoTitle">true</item>
</style>
```
