### ISSUE TITLE
bug: `npx cap migrate` deletes package-lock.json

### ISSUE THREAD

**Issue by nunoarruda** [ionic-team/capacitor#5817]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/core: not installed
  @capacitor/android: not installed
  @capacitor/ios: not installed
  @capacitor/cli: 4.0.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

All

### Current Behavior

Capacitor v4 migration deleted my package-lock.json.  Also `npx cap doctor` now lists some Capacitor dependencies as `not installed`. Here is my `npx cap migrate` logs:

<img width="834" alt="Screenshot 2022-08-02 at 15 18 21" src="https://user-images.githubusercontent.com/1189149/182399546-358a88c9-1f45-4b8f-be86-a828d5b555ae.png">

### Expected Behavior

It should not delete package-lock.json.

### Code Reproduction

Migrate a Capacitor v3 project to v4.

### Other Technical Details

`npm --version` output: 8.5.5

`node --version` output: v16.15.0

`pod --version` output (iOS issues only): 1.11.2

### Additional Context

I'm not using Ionic. I'm just using a regular Angular 14.1 project with Capacitor.

**Comment by ekrapfl** [comment]
I am also seeing this when running the migrate command from Capacitor 3 to Capacitor 4.  I am running node v16.17.0, npm version 8.15.0

Any update on this?

Fwiw, as a workaround, I discarded the changes to the `package-lock.json` (discarded the deletion, that is), and then explicitly installed the versions of all of the dependencies that `cap migrate` did for me.  It defeats some of the handiness of the migration, but at least I got the package.lock back to showing ONLY the changes I wanted.

**Comment by jcesarmobile** [comment]
`npx cap migrate` deletes the package-lock.json if you choose yes in the "run npm install" question to prevent npm from install 3.x (that can happen in some cases).

As it runs `npm install` it should create a new package-lock.json file.

If the package-lock.json file was not created it's because npm install failed, at the moment no error is shown, we have created [an issue](https://github.com/ionic-team/capacitor/issues/5897) to fix that.

If you don't want the package-lock.json file to be deleted you can answer no to the run npm install question and run npm install yourself

**Comment by jcesarmobile** [comment]
closing as it can be prevented by not installing packages
