### ISSUE TITLE
App API Plugin canOpenUrl() fails

### ISSUE THREAD

**Issue by murraybauer** [ionic-team/capacitor#583]
I just installed the new Capactior Beta and the latest xCode.

Using your example code:

```
var ret = await App.canOpenUrl({ url: 'com.getcapacitor.myapp://page?id=ionicframework' });
console.log('Can open url: ', ret.value);
```

Returns error:
```
App canOpenUrl 25556797
2018-06-16 22:01:34.339286+1000 App[55652:5714153] -canOpenURL: failed for URL: "com.getcapacitor.myapp://page?id=ionicframework" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
```

 I have setup the `LSApplicationQueriesSchemes` array with item 0 string `com.getcapacitor.myapp` in `Info.plist`.

If I change that value to put a 1 at the end I get:
```
"This app is not allowed to query for scheme com.getcapacitor.myapp"
```
So the Info.plist entry is not the issue.

I have tried simulator iOS 11.4 and iPhone 11.4 - no difference.

**Comment by jcesarmobile** [comment]
That error code appears when there is no app with that scheme.

So, canOpenUrl returns false if
1. It can't query for a app scheme because it's not included in the `LSApplicationQueriesSchemes`
2. There is no app installed for the required scheme

It returns true if the `LSApplicationQueriesSchemes` is properly configured and you have an app that responds to that scheme.

To make an app respond to an scheme you have to configure `CFBundleURLSchemes` inside `CFBundleURLTypes`

**Comment by murraybauer** [comment]
@jcesarmobile thank you! It worked.  The capacitor documentation only mentions setting `LSApplicationQueriesSchemes` nothing about `CFBundleURLSchemes` and it wasn't obvious in anything I googled.

**Comment by jcesarmobile** [comment]
That's because the docs are about how to use `canOpenUrl` to open other apps, what you search is how to register your own scheme for your app

Here you can find more information about how to communicate iOS apps by using url schemes
https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/communicating_with_other_apps_using_custom_urls

And here a list of Apple's Apps url schemes
https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/Introduction/Introduction.html

There was a website that registered 3rd party apps url schemes, but it's been down for a long time, I don't think they are maintaining it anymore
