### ISSUE TITLE
feat: Add Mac Catalyst Support

### ISSUE THREAD

**Issue by jrbj** [ionic-team/capacitor#5855]
### Description
It would be useful if support for Catalyst would be added. This would allow using our iOS code to build a macOS desktop app.

### Platform(s)
- macOS

### Preferred Solution
It would be ideal to be able to enable the macOS catalyst target and have it build a macOS app.

**Comment by folsze** [comment]
Isn't this enabled already? I published a capacitor catalyst app and it worked fine

**Comment by folsze** [comment]
also to check whether platform is Catalyst check here:
https://github.com/ionic-team/capacitor/issues/7239#issuecomment-1936082650

**Comment by jcesarmobile** [comment]
Since we are focusing in SPM, to support Catalyst or other architectures we would need to build the .xcframeworks with Catalyst, visionOS or any other architecture we would want to support and that's not something we plan to do anytime soon, so I'm going to close the issue.

An alternative would be to build "iPad style" apps, those work on macOS and visionOS already.
