### ISSUE TITLE
bug: minWebViewVersion is not working as expected

### ISSUE THREAD

**Issue by daniel-zero** [ionic-team/capacitor#5898]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/ios: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
```

### Platform(s)

- Android

### Current Behavior

The specified min webview version is ignored when changed in the capacitor.config.ts config. Also is the option [not documented](https://capacitorjs.com/docs/config)  as expected.

```
  android: {
    minWebViewVersion: 80,
  },
```

The log prints the following version

`I/WebViewFactory: Loading com.google.android.webview version 61.0.3163.98 (code 316409850)`

### Expected Behavior

The app should prompt the user to update the webview package

### Code Reproduction

Create an Android 8 Emulator, set the min sdk to version 70 and start the capacitor app. The Log will print out web view version 61 but the user is not prompted to update the web view package

**Comment by daniel-zero** [comment]
I created a PR to fix the missing config option presented in the docs: https://github.com/ionic-team/capacitor-docs/pull/64

**Comment by daniel-zero** [comment]
I digged trough the code as far as I understood the Capacitor functions. The minimum version is checked as expected and also the `MINIMUM_ANDROID_WEBVIEW_ERROR` is thrown. My expectation is now that the App shows the user an native error dialog with an error message.

**Comment by jcesarmobile** [comment]
It works as expected, it only shows an error on logcat, not to the user.

It can be combined with `errorPath` config option to let the developer show a local html page where they can show the custom error/message they want and localize it if necessary. That should be more clear in the docs, so I'll keep this issue open until it's properly explained.

We evaluated the prompt to update the web view package, but is not a viable option because there are a lot of devices without google play or that don't allow to update the web view package (in example the emulators that were created without google play, zebra devices, chinese vendors, etc.), which are the bigger % of devices with outdated WebView version.
