### ISSUE TITLE
bug: capacitor:sync:before also runs on copy and/or update

### ISSUE THREAD

**Issue by maxfloden** [ionic-team/capacitor#5982]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

### Current Behavior

I added `capacitor:sync:before` to my package.json, with a script to increment build number.
`"capacitor:sync:before": "npx trapeze run trapeze.config.yaml -y"`
However the script runs three times instead of one. Looking at screen output, it seems to also be running at cap copy and/or update.
Tested with same result both `ionic cap sync` and `npx cap sync`

### Expected Behavior

Script should run only once, before cap sync

### Code Reproduction

Add below line to package.json, then run `npx cap sync`and you will se HELLO! three times instead of one
`"capacitor:sync:before": "echo 'HELLO!'"`

### Other Technical Details

`npm --version` output:
6.14.15

`node --version` output:
v14.16.0

`pod --version` output (iOS issues only):

**Comment by jcesarmobile** [comment]
The hook runs once per platform, so if you have 3 (web, ios and android) it will run three times. On each run the `$CAPACITOR_PLATFORM_NAME` variable value will have a different value, so you can use that variable in the hook to do different things based on the platform it's running.

If instead of `npx cap sync` you run `npx cap sync ios` then it will run only once with the ios value on `$CAPACITOR_PLATFORM_NAME`.

But maybe we should have `capacitor:copy:before:platformName` to allow platform specific hooks and make the `capacitor:copy:before` without platform to run only once.

**Comment by maxfloden** [comment]
@jcesarmobile Thanks for explanation.

> But maybe we should have `capacitor:copy:before:platformName` to allow platform specific hooks and make the `capacitor:copy:before` without platform to run only once.

Good idea, I think this would make sense.

**Comment by jcesarmobile** [comment]
Will mark it as feature request, but if we do we would have to wait for Capacitor 5 since it would be breaking as `capacitor:copy:before` wouldn't contain the `$CAPACITOR_PLATFORM_NAME` variable anymore and some users might be depending on it.

**Comment by jcesarmobile** [comment]
we have discussed it internally and we won't be changing the behavior.
If you want to run it only once then use the command with a platform, i.e. `npx cap sync ios`.
If you want to keep using `npx cap sync` without a platform, you can use a custom npm script that does what you want and also runs sync, something like:
"customsync": "echo 'HELLO!' && npx cap sync"
and run `npm run customsync` instead of `npx cap sync`.
