### ISSUE TITLE
feat: Possibility to translate in the camera plugin when it does not exist.

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/capacitor#6140]
Hello, when there is no camera, the texts: "No camera found" and "Choose image" appear. Add the possibility to change the texts as in the rest of promptLabel.

<img width="458" alt="Captura de pantalla 2022-11-18 212228" src="https://user-images.githubusercontent.com/18282247/205373165-67c395ca-3584-4953-8b94-32540042f87c.png">

Thanks!

**Comment by jcesarmobile** [comment]
I moved your previous issue to pwa-elements repository, since the changes need to be done there, it's not possible to change those texts at the moment without changing pwa-elements.

Not sure if you see a "[jcesarmobile](https://github.com/jcesarmobile) transferred this issue from ionic-team/capacitor [14 days ago](https://github.com/ionic-team/pwa-elements/issues/113#event-7855491067)" in the issue or if that's only visible for the repo maintainers
