### ISSUE TITLE
bug: Capacitor 4 - Android - No startup splash screen on real device

### ISSUE THREAD

**Issue by JumBay** [ionic-team/capacitor#6190]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1

[success] Android looking great! 👌
```

### Platform(s)

Android

### Current Behavior

On an Android device (xiaomi mi 11 lite, running Android 12) the startup splash screen doesn't show up. Calling `SplashScreen.show` when the app is loaded, works without any issue. This used to work on capacitor 3, but after the upgrade to capacitor 4 it doesn’t anymore. 
On a simulator, it display a splash screen, but it's different from the one displayed by calling `SplashScreen.show` 

Here is a video of the issue:

https://user-images.githubusercontent.com/216573/209322302-78436702-030c-4e6e-bda6-2dcc63659ce1.mp4

And here is the splash screen displayed on a simulator:
<img width="437" alt="Screenshot 2022-12-23 at 11 09 34" src="https://user-images.githubusercontent.com/216573/209322408-c72c4e42-4fec-48b1-8eea-7592709d93a2.png">

### Expected Behavior

Display the splash screen

### Code Reproduction

I've made a repository with the issue. It's based on ionic starter app, with `@capacitor/splash-screen` installed
https://github.com/JumBay/capacitor-splashscreen

### Other Technical Details

`npm --version` output: 8.19.2

`node --version` output: v18.12.1

**Comment by yugandhargangu** [comment]
Same issue in Realme device, Android 12.

**Comment by hiiimgary** [comment]
I updated capacitor 3 to capacitor 4 and and the update wizard updated the old splash screen to the new API. On iOS everything works fine but on Android 12 the splash screen not showing at all (On emulator i see the icon lagging when i push it, 3 second delay and the application opens without splash) and on Android 13 i see the app icon instead of the splash screen as shown in the issue.

**Comment by d00ML0rDz** [comment]
@hiiimgary How are you calling `SplashScreen.show()`? I previously was doing it in a react `useEffect()` which was causing problems for me. Moving it to the top level of my TypeScript file fixed it for me.

**Comment by hiiimgary** [comment]
@d00ML0rDz  I am not calling show, only hide as i configured the SplashScreen to `launchAutoHide: false` so it will stay open until the application fetches the necessary data from the backend.

```
    SplashScreen: {
      launchAutoHide: false,
      backgroundColor: '#143344',
      androidSplashResourceName: 'splash',
      androidScaleType: 'CENTER_CROP',
      splashFullScreen: true,
      splashImmersive: true,
      layoutName: 'launch_screen',
      // useDialog: true,
    },
```

I am using Angular and I am calling hide in the app component.

**Comment by d00ML0rDz** [comment]
@hiiimgary As far as I understand, Android 12+ devices now always make use of the new SplashScreen API which doesn't make use of the SplashScreen settings in the capacitor.config file, which you've posted above. I was having an issue on Android where my splashscreen was vertically stretched on my phone, which I was able to solve using the config settings, however with Android 12+ ignoring most of these, it became an issue again.

The only solution I found was to just use the app icon splashscreen for Android 12+ as that at least that displayed correctly. On Android 11 and under devices, I still have a proper splashscreen.

**Comment by hiiimgary** [comment]
@d00ML0rDz Well i would be satisfied with the icon on new devices and the splash on older devices, but with the new SplashScreen api it seems to be broken. Or I am doing something wrong.

Are you saying that you are using the old api?

**Comment by d00ML0rDz** [comment]
@hiiimgary I'm using the old API for Android 11 and under devices, yes. Android 12+ has to use the new API when using Capacitor v4 as far as I understand.

Might be worth trying `SplashScreen.show()` at the top of your app component just to see if that makes a difference, but the splash screen functionality definitely seems to have gotten more difficult to make proper use of in Capacitor 4.

**Comment by JumBay** [comment]
Thanks for your explanation, but how come it works with Capacitor 3 then?

**Comment by jcesarmobile** [comment]
In Capacitor 3 it was not really working correctly neither, it shows a duplicated splash screen, first the OS splash screen and then old Capacitor splash screen. But since in your device the OS splash screen is not working you probably didn't notice as you only see a black screen for ~1/2 second or so and then the old Capacitor splash screen. In my Android 12 device I see the app icon for ~1/2 second and the the old Capacitor splash screen. 

That duplicated splash screen is documented on the official Google docs for [Android 12 Splash Screen migration](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate) docs

> If your existing splash screen is implemented using a dedicated Activity, launching your app on devices running Android 12 or higher results in duplicate splash screens: [the new system splash screen](https://developer.android.com/about/versions/12/features/splash-screen) displays, followed by your existing splash screen activity.

**Comment by JumBay** [comment]
My phone get updated to android 13 and the issue is still present

**Comment by eeschiavo** [comment]
Issue is present on Android 13 too

**Comment by jcesarmobile** [comment]
As I said, this is a Android OS issue, Google claims that they have fixed it, but if it's not fixed, you should report it to google, there is nothing we can do about it.

**Comment by eeschiavo** [comment]
Are you sure about it? Because it was working with Capacitor 3

**Comment by jcesarmobile** [comment]
No, it was not working, I already explained it on a [previous comment](https://github.com/ionic-team/capacitor/issues/6190#issuecomment-1398133924)

On devices where the new Splash Screen API doesn't work it will look like it's working because it shows the blank screen for less than a second and then the Capacitor SplashScreen plugin will show a fake splash screen.
But on devices where new Splash Screen API works it would show a duplicated splash screen, first the OS splash screen and then the Capacitor SplashScreen plugin fake one.
