### ISSUE TITLE
Splash screen blinking in IOS

### ISSUE THREAD

**Issue by dfjmax** [ionic-team/capacitor#620]
Just created a new project(Ionic + Capacitor) following the instructions on:
[https://capacitor.ionicframework.com/docs/getting-started/with-ionic](url)

And then changed the splash screens using these instructions:
[https://www.joshmorony.com/adding-icons-splash-screens-launch-images-to-capacitor-projects/](url)

When I start the application the splash screen image is blinking like in the attached video.
[IMG_0189.TRIM.MOV.zip](https://github.com/ionic-team/capacitor/files/2145611/IMG_0189.TRIM.MOV.zip)

Any clues?

**Comment by wtrocki** [comment]
http://www.giphy.com/gifs/ag3qU174aW4jkC8lvw

**Comment by wtrocki** [comment]
@dfjmax it could be related with the type of the image that is being used. Can you upload this image so we can reproduce that issue.

**Comment by jcesarmobile** [comment]
The flash is because iOS first shows the launch storyboard and then the splash plugin shows the same image again, will look into it. Depending on the image it might be more or less noticeable.

When it shows the capacitor image first is because the emulator cached it, you’ll have to delete the app from the simulator. That only happens while in development, not when released from the App Store

**Comment by bitflower** [comment]
Having this too.

**Comment by jcesarmobile** [comment]
Linking related issue https://github.com/ionic-team/capacitor/issues/1003

**Comment by M00dl3** [comment]
Having this issue as well, using Ionic 4 together with Angular. Adding a delay before hiding the splash screen 'fixes' the flickering of screens. But this is bottlenecking performance.
