### ISSUE TITLE
bug: Android Livereloading not executing

### ISSUE THREAD

**Issue by kpat-omf** [ionic-team/capacitor#6204]
When I Execute this command: ionic capacitor run android -l --external
It does not ask me at any point to select a target device, instead it reaches 
capacitor copy android, 
then capacitor open android and it opens Android Studio. 
It used to open an emulator device and I was able to live reload. 
It states this as well: 

 Ready for use in your Native IDE!
 To continue, run your project on a device or emulator using Android Studio!

These are my versions:
“@capacitor/android”: “4.3.0”,
“@capacitor/app”: “4.0.1”,
“@capacitor/core”: “4.3.0”,
“@capacitor/device”: “4.0.1”,
“@capacitor/ios”: “4.3.0”,
node 16
npm 7.24.0
openjdk 11.0.17

Android Root set correctly as well, I am working on an M1 Mac, cocoapods is installed through brew.
If I run the command npx cap run android, it lets me select a device, but the command ionic capacitor run android -l --external does not select device it just opens android studio.

**Comment by jcesarmobile** [comment]
looks like you are using an old version of Ionic CLI or even the deprecated ionic package 
run 
```
npm uninstall ionic -g
npm uninstall @ionic/cli -g
npm install @ionic/cli -g
```
then if you run `ionic --version` you should get 6.20.6 or newer

**Comment by jcesarmobile** [comment]
Ionic CLI should be global, so it should not appear in your package-lock file.
If `ionic --version` is not returning anything try with `ionic version`, both of them should work, but if none is working there is something wrong with your Ionic CLI install. Try running those commands I shared and don't miss the `-g` at the end as that means the package will be global instead of local.
