### ISSUE TITLE
bug: ionic cap run android --livereload --external, hangs if there are build warnings

### ISSUE THREAD

**Issue by expresspotato** [ionic-team/capacitor#6262]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Code Reproduction

See attached test project, it's the menu example with one simple addition, IonAvatar as an include in App.vue. When build time warnings are produced, the capacitor command is not run.

https://drive.google.com/file/d/10BGo3a0WDsa0JUPC1vIhALaW_ay_q0wE/view?usp=share_link

**Comment by expresspotato** [comment]
Found a work around, you can run:

`ionic cap run android -l --external -- --skip-plugins eslint`

**Comment by jcesarmobile** [comment]
Ionic CLI issues should be reported on it's own repository
https://github.com/ionic-team/ionic-cli/issues

But doesn't look like an issue to me but a configuration thing, if your project is configured to not run if there are lint problems, then it won't finish running because of that. And as you have figured out, the lint can be skipped. 
There are probably other ways of doing it so you don't have to pass that parameter every time, you should check vue docs as that's vue related, not really ionic CLI related.

**Comment by expresspotato** [comment]
Thanks, I will post it here. But I don't feel simply unused import warnings should cause the build process to hang without any output. That's not acceptable behaviour for a build process.
