### ISSUE TITLE
bug: backButton priorities in ionic components

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/capacitor#6343]
### Capacitor Version
```
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 4.7.0
  @capacitor/cli: 4.7.0
  @capacitor/android: 4.7.0
```

### Platform(s)
Android

### Current Behavior
Hi, Capacitor's backbutton doesn't respect priorities like Ionic's does, which causes it to do weird things like dismiss an alert and go back one page at a time.

### Expected Behavior
addListener('backButton', ...)​ is expected to dismiss by priority like Ionic does: https://ionicframework.com/docs/developing/hardware-back-button#internal-framework-handlers

### Code Reproduction
1. https://github.com/Marius-Romanus/ionic-bug-back-button-android
2. npm i
3. npm run android:dev
4. AuthGuard navigate to page 2 (guards/auth.guard.ts)
5. navigate page3
6. click button "Click Me"
7. press the physical button to dismiss the alert. Observe how apart from dismissing the alert, navigate to page 2.

### Other Technical Details

`npm --version` output: 9.5.1

`node --version` output: v18.14.0

`pod --version` output (iOS issues only):

### Additional Context
related to: https://github.com/ionic-team/capacitor/issues/6267

**Comment by jcesarmobile** [comment]
Capacitor knows nothing about your framework, your code is telling the back button handler to navigate back when the back button is pressed, and I guess when you present a modal it's not considered a navigation, so your `window.history.back();` will go from page 3 to page 2.

If you are using Ionic you should use Ionic back button handler, not the Capacitor back button handler, because Ionic back button handler is supposed to handle those kind of things.
