### ISSUE TITLE
bug: backButton canGoBack always returns true AuthGuard Angular

### ISSUE THREAD

**Issue by Marius-Romanus** [ionic-team/capacitor#6344]
### Capacitor Version
```
Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/core: 4.7.0
  @capacitor/cli: 4.7.0
  @capacitor/android: 4.7.0
```

### Platform(s)
Android

### Current Behavior
Hi, In the physical Android button, when you have an Angular guard, and you navigate to another page that is not the main one, canGoBack always returns true.
A very clear example is if you want to skip the main login page (in the example page1) because the user is already logged in with a guard and redirect him to home (in the example page2).

### Expected Behavior
canGoBack is expected to return false when the back button is clicked on page 2 and can decide to exit the app.

### Code Reproduction
https://github.com/Marius-Romanus/ionic-bug-back-button-android

1. npm i
2. npm run android:dev
3. AuthGuard navigate to page 2 (guards/auth.guard.ts)
4. navigate page3
5. press the physical button to navigate back and go to page 2
6. press the physical button to try to exit the application (app.component.ts line 23)
7. look at the log with the chrome inspector - chrome://inspect/#devices

### Other Technical Details

`npm --version` output: 9.5.1

`node --version` output: v18.14.0

`pod --version` output (iOS issues only):

### Additional Context
related to: https://github.com/ionic-team/capacitor/issues/6267

**Comment by jcesarmobile** [comment]
As I mentioned on https://github.com/ionic-team/capacitor/issues/6343, Capacitor knows nothing about your framework, if the authGuard is navigating from the "index.html" to the page 2, that counts as a WebView navigation.
The Capacitor canGoBack returns true if it's possible to navigate back because there are pages that have been navigated before, and in your app is possible to navigate back because it navigated from the "index.html" to the page 2, but your guard is blocking the navigation.


If you are using Ionic you should use Ionic back button handler, not the Capacitor back button handler, because Ionic back button handler is supposed to handle those kind of things. And if it's not working properly you should report them in the Ionic Framework repository or in the angular repository (whoever handles the guard navigation)
