### ISSUE TITLE
bug: Share plugin strips url's parameters when using share via messages in IOS native

### ISSUE THREAD

**Issue by huantrinh1802** [ionic-team/capacitor#6355]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/ios: 4.7.0

[success] iOS looking great! 👌
```

### Platform(s)

- IOS

### Current Behavior

- Using: "@capacitor/share": "^4.1.1"
- In IOS native build, when I choose to share via messages, the url ('https://www.humaniti.com/referral/?ftName=john&signupCode=923') is striped all the parameters into ('https://www.humaniti.com/referral/')
- Other options (copy, whatsapp, facebook, team,...) work fine.
- I tried with 'https://example.com/?ftName=john&signupCode=923' and it works. It seems to be domain related.

### Expected Behavior

- Share plugin works with messages option.

### Code Reproduction

https://github.com/huantrinh1802/capacitor-share-plugins-bugs

### Other Technical Details

`npm --version` output: 8.11.0

`node --version` output: v16.16.0

`pod --version` output (iOS issues only): 1.11.3

### Additional Context

N/A

**Comment by jcesarmobile** [comment]
I can't reproduce on the sample app.
Notice that you didn't add the ios platform, so I had to add it to test, so, in case you had made any manual changes in the project I couldn't see them.

Anyway, this looks like a messages bug/feature/limitation since other apps are getting the url properly, the plugin just send the url to the sharing sheet, and if the other apps are getting it, then it's being sent properly, if messages strips data there is nothing we can do about it.
