### ISSUE TITLE
Live Deploy plugin don't work

### ISSUE THREAD

**Issue by dimarkov-git** [ionic-team/capacitor#638]
I install npm i --save cordova-plugin-ionic and write options to android ... /values/strings.xml
IonicDeploy download build and unzip it, but not reload the view

**Comment by mlynch** [comment]
We haven't quite gotten this plugin to work officially w/ Capacitor yet. It's certainly something we plan to do. Leaving this open to track that

**Comment by bashoogzaad** [comment]
Any update on the progress? Live deploy is certainly one of reasons I happily pay for ionic 😉

**Comment by nikmartin** [comment]
Would love an update on this, I suspect adoption of Capacitor will be exactly 0 without IOnic Pro integration :)

**Comment by adrm** [comment]
There is no workaround for this at the moment? I would love to try even if it is a not supported method.

**Comment by rfarko** [comment]
Any update on Live Deploy support with Capacitor projects?

**Comment by davidseek** [comment]
+1

**Comment by prud** [comment]
+1 Would also love to see this coming in the future

**Comment by arthurrmp** [comment]
+1 
We had to go back to cordova

**Comment by nikmartin** [comment]
Yeah, it's now 2019 ands the lack of Appflow/Live Deploy in Capacitor is now getting suspicious. Capacitor support almost every other cordova plugin feature except Appflow/Live Deploy.

**Comment by jcesarmobile** [comment]
Capacitor has supported AppFlow Deploy for a long time, but we didn't announce it because as Capacitor doesn't support plugin variables, it was a bit hard to configure as required a few manual changes in the native project.

Good news is, starting in ionic CLI 5.1.0, some commands have been added to make it easier for you.

First of all, link your capacitor app with AppFlow
`ionic link`
Then add Deploy to it
`ionic deploy add`
It will prompt you for the channel and update method and it will write the values in the native projects. (those that I said that were manual)

When you make changes in the code you'll have to run `ionic deploy manifest` to generate a new manifest file, that is used to compare files and see what has changed and know what it has to download. It's not a big problem if you don't run it, but it will download more files and will take more time to download them. This was not needed in Cordova because cordova had hooks, but those are not supported in Capacitor. 


There will be official docs about it soon, but I'm going to close as the Capacitor work is done.
If you try it and find bug in Capacitor, report them here.
If you find bugs in the ionic commands report them in cli repo https://github.com/ionic-team/ionic-cli

**Comment by nikmartin** [comment]
Any idea on how to change the channel in the iOS project? It's in values.xml on Android, but I canl;t find it anywhere in the iOS source tree

**Comment by jcesarmobile** [comment]
It should be in the Info.plist

But you can use `ionic deploy configure` command to set the values again.

**Comment by sikfreeze** [comment]
Hi, I tried capacitor with Appflow's live update. I got it to work fine with Android but can't say the same for Electron. Does Appflow's live update (web deploy) support electron?
