### ISSUE TITLE
feat: better localhost development

### ISSUE THREAD

**Issue by kristojorg** [ionic-team/capacitor#6388]
### Description
I often want to run my app with live reloading for development on both iOS and Android platforms. This is currently very cumbersome. I have tried using the Ionic CLI as referenced in the docs, but it has never worked for me and I have been told by Ionic employees that the Capacitor CLI is more up to date and the Ionic one is not maintained. 

I would like to propose an easier way to run an app with live reloading.

#### The Problem(s)

1. The iOS simulator and Android emulator have different means of accessing a server on the host machine's `localhost`. In the iOS simulator this can be done by simply connecting to `localhost` or `127.0.0.1` just like a normal web browser on the host machine. In the Android emulator, the `localhost` refers to the emulator's loopback interface, not the host machine's. Thus there is no one setting I have found for the `server.url` field in `capacitor.config.ts` that will tell iOS and Android where to find the web bundle. 
2. Changing the `server.url` field every time you want to develop your app is problematic. **This field should not ever be set in production**, yet it is very easy to mistakenly commit the change. It's not a great development experience. 

### Platform(s)

- iOS
- Android
- Capacitor CLI
- **Not** the Ionic CLI

### Preferred Solution
One solution I have thought of is:

1. A way to set a `server.url` when running capacitor commands. This should override the value in `capacitor.config.ts`, allowing us to set `"sync: live": "npx cap sync --server-url http://0.0.0.0:8100"` in our package.json and then just run `npm run sync:live`. No more setting temporary values in the `capacitor.config.ts` file.
2. If we set `server.url` to `localhost`, capacitor should interpret that as the host machine's localhost and set it to `10.0.2.2` in the Android emulator.

### Alternatives

There are many other options - and maybe something better? Another option is to allow multiple `capacitor.config.ts` files. One for development and another for production. There is probably another way to solve the ip address issue as well, and honestly it would be awesome if there was one command (`npx cap run --live`) that runs the dev server, syncs, and runs both the iOS simulator and Android emulator. 

### Additional Context
This is related to many tickets and posts in the Ionic Forum referencing the `ERR_CONNECTION_REFUSED` message on Android.

**Comment by jcesarmobile** [comment]
`npx cap run` now has a `-l, --live-reload` parameter, that in conjunction with ` --host` and `--port` allow you to run your app directly on the device or emulator on the desired live reload url, only when you are running the app, and removes the values once you stop the command.
https://github.com/ionic-team/capacitor/pull/6831

**Comment by 5im0n** [comment]
@jcesarmobile, I just test the new CLI options and it works great but only for the web part. 

When I try to launch a native plugin function, I get an error `plugin is not implemented on android`.

I dont have this error when use the Ionic cli: `ionic cap run -l --external --host=192.168.X.X`

Any ideas ?

**Comment by kristojorg** [comment]
Thanks for the update here! This is a really, really handy function. It works great on ios. On android, I am still seeing a connection refused:

<img width="462" alt="image" src="https://github.com/ionic-team/capacitor/assets/4398775/cf7bfa23-137a-4939-8b9f-2d6eee2df6e8">

Any idea why that might be? This is when running with `npx cap run -l --port 8100 --host localhost android`

**Comment by kristojorg** [comment]
I see that the command is only adding a config to the `capacitor.config.json`. I thought it would be temporarily adding cleartext permissions to the android and ios projects. Is there anything you can recommend to enable this cleartext? I've searched the forums, the docs, etc. Nothing seems to work for me

**Comment by AlansCodeLog** [comment]
Ran into this. Can this be re-opened?

Live reload prevents the setting of cleartext because it overrides all server settings in [this line](https://github.com/ionic-team/capacitor/blob/fe5333082622f549f81541369feeb12ca0945e03/cli/src/util/livereload.ts#L171). I'm not sure if all settings should be merged, am new to android dev, but some definitely should.

As a workaround what I ended up doing is generating different capacitor configs depending on env variable, but this is quite annoying.

In this case I chose NODE_ENV, but you can use anything. 

```
server: {
	...(process.env.NODE_ENV === "DEVELOPMENT"
		? {
			url: `http://10.0.2.2:${process.env.VITE_DEV_PORT}`,
			cleartext: true,
		}
		: {
			//...
		}),
},
```
Then I run it like `NODE_ENV="DEVELOPMENT" VITE_DEV_PORT=3000 npx cap run android`. Although it will not appear to be waiting, reading the code I believe it is almost functionally the same since it just does a dummy sleep forever. `--live-reload` by itself only temporarily changes config options and does not appear to watch/do anything on changes, except to return the config back when you quit the command.

Personally if there is no plan to trigger a reload on the app side when files change (if that's even possible) I think it would be better to just remove it or rename it ( to --temporary maybe to indicate a temporary override?).
