### ISSUE TITLE
How to handle translations?

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#665]
capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

```
JSObject fromPhotos = new JSObject();
      fromPhotos.put("title", "From Photos");
      JSObject takePicture = new JSObject();
      takePicture.put("title", "Take Picture");
```

Trying out the Camera-plugin. My phone is in Swedish but I got titles in English "From Photos" and "Take Picture". Was able to find relevant file. 

What are you thinking with regards to being able to translate titles/buttons/whatever?

I'm suggesting being able to pass custom texts whenever relevant like in this case (in the options object for example).

**Comment by solojuve1897** [comment]
This specific issue is not relevant for me anymore since I have changed the logic so that the user chooses Photos or Camera as CameraSource before the call is made. Still relevant though to handle places where texts are hard-coded.

**Comment by jcesarmobile** [comment]
Going to close the issue.

For hardcoded texts we plan to do something like what explained in this issue https://github.com/ionic-team/capacitor/issues/872
or use the native ways, but we will get rid of hardcoded english messages.

For buttons on native UIs, that's really handled by the system, english is default because that's the default development region. If you want just to support a different language change the region in the info.plist.
If you want to support multiple languages you can add the CFBundleLocalizations key with multiple values, and if the user's device language matches one of those it will automatically show the screens with proper messages
