### ISSUE TITLE
bug: sync removes swift package linked to plugin

### ISSUE THREAD

**Issue by justinpathrose** [ionic-team/capacitor#6668]
### Capacitor Version
```
Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/core: 5.0.4
  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4
```

### Platform(s)
iOS

### Current Behavior
We have a plugin which has a dependency on a swift package. After adding the package to the plugin iOS project, running npx cap sync removes the dependency. Because of this, we are having to link the dependency after sync is completed.

### Expected Behavior
npx cap sync does not remove the swift package dependency added to the custom capacitor plugin.

### Other Technical Details

`npm --version` output: 9.6.7

`node --version` output: v16.16.0

`pod --version` output (iOS issues only): 1.12.1

### Additional Context

We get around the issue by manually adding the package after sync. We build our app in cloud and hence we would need an alternate way to do this. Any help is much appretiated.

**Comment by jcesarmobile** [comment]
This is not a bug, if you do manual changes on plugins they get removed on sync because Capacitor plugins are CocoaPods libraries, and CocoaPods libraries should not be edited and CocoaPods regenerates them on update/sync commands.

If you need to make changes after the sync you can use [Capacitor hooks ](https://capacitorjs.com/docs/cli/hooks), in example `capacitor:sync:after` so it runs after the sync finished doing the changes.
