### ISSUE TITLE
IOS Error if Network offline when using AngularFireAuth

### ISSUE THREAD

**Issue by ghq2340** [ionic-team/capacitor#667]
If the network is not connected/offline, the IOS module throws this error when using AngularFireAuth. Android and PWA seem ok. Any ideas on how to custom handle that exception?  I already tried using a Global Custom Error handler without success.

constructor(public afAuth: AngularFireAuth, private router: Router) {
.......
......
}

![cap_ios_network_offline](https://user-images.githubusercontent.com/41524283/43039870-3af09b04-8ceb-11e8-9621-5a5f8d0c7509.png)

**Comment by ghq2340** [comment]
This issue is still present with Capacitor Beta3

**Comment by jcesarmobile** [comment]
I've looked into it and the problem is firebase SDK throws a `Error('Network Error')`when it fails to create the iframe because of not having internet connection. 
Also happens in Cordova when using WKWebView.

Not even putting the initializeApp in a try catch is able to catch that error.

I'll close as this is the firebase SDK throwing the error, not us.

If you are worried about the white dialog showing the error, that's only shown while in debug, it's disabled in release, so users won't see it. But maybe we should provide a way of disabling it even for debug builds.
