### ISSUE TITLE
How to use appUrlOpen - Vue.js and Android-app

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#674]
From the docs:

"Listen for url open events for the app. This handles both custom URL scheme links as well as URLs your app handles (Universal Links on iOS and App Links on Android)"

In Android Studio I have gone through the "App Links Assistant" and get green flags wherever possible:
- Added autoVerify to intent filter elements.
- Success! Your app is associated with the selected domain(s).
- This URL maps to com.muslimtraff.app.MainActivity (app)

In my Vue.js-application I have in the App.vue-component added:

**import { Plugins } from '@capacitor/core'
const { App } = Plugins**

And in the **created()**-hook:

**let _this = this
    App.addListener('appUrlOpen', (data) => {
      _this.$router.push({name: 'EmailConfirmed'})
    })**

What am I missing? When trying to access the mapped URL via the browser I'm not prompted or get sent to the app. In the console I can see the following:

**Uncaught (in promise) App does not have web implementation**

**Comment by wtrocki** [comment]
@solojuve1897 Please note that this feature will work only on the IOS and Android platforms - web is not supported. Error that was send happens when webpage is opened in browser.

**Comment by solojuve1897** [comment]
@wtrocki 

I tried it on my Android-phone with the app installed, I wasn't forwarded to the app. What am I missing?

**Comment by wtrocki** [comment]
It's up to developer to configure app to respond to scheme (if you using custom one).
See: https://developer.android.com/guide/components/intents-filters#Resolution

**Comment by solojuve1897** [comment]
@wtrocki 

I added the following in config.xml in the widget-tag (I hadn't done anything in that file before):

`<content src="index.html" />
  <access origin="*" />
  <allow-intent href="http://*/*" />
  <allow-intent href="https://*/*" />`

And since before I have in my AndroidManifest.xml the following in the activity-tag:

`<intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>

      <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="https"
          android:host="myhost.com" />
      </intent-filter>
      <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="https"
          android:host="myhost.com"
          android:pathPattern="/#/epost-bekraftad" />
      </intent-filter>
      <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="https"
          android:host="myhost.com"
          android:pathPattern="/#/epost-bekraftad2" />
      </intent-filter>`

I also have a assetlinks.json-file in my .well-known-folder in the root which contains the following. This also passes the verification by AndroidStudios App Links Assistant. I signed with a debug keystore.

`[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.muslimtraff.app",
    "sha256_cert_fingerprints":
    ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"]
  }
}]`

* myhost.com = just a placeholder for domain
* XXXX(...) = placeholder

What have I missed or gone wrong?

**Comment by wtrocki** [comment]
Place breakpoint in your project here: 
https://github.com/wtrocki/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java#L190

If breakpoint is not activated then issue is related with scheme configuration.

**Comment by ArmorDarks** [comment]
Seems issue to be reproducible only with `release` built. Many other things in `release` are broken too #739

**Comment by MichaelMalony** [comment]
I've found two issues. 

First, I am definitely configured correctly. You can test using:

`
adb shell am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d "https://www.example.com/somepath"
`

This correctly launches my app but the appUrlOpen listener never gets called.

**The first issue:**

Android documentation for app links shows handling the app link intent in onCreate() as well as onNewIntent(): https://developer.android.com/studio/write/app-link-indexing#handling

BridgeActivity does not do this. An extra catch here is the intent has to be handled after init() is called but that is done in MainActivity. This probably isn't where you want this to live, but for debugging I updated MainActivity.onCreate():

```
@Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
    }});

    Intent intent = getIntent();
    if (intent != null) {
      this.onNewIntent(intent);
    }
  }
```

After that I can put a breakpoint in App.handleOnNewIntent() and it gets hit correctly. I can also confirm that this block gets hit with the correct url:

```
JSObject ret = new JSObject();
ret.put("url", url.toString());
notifyListeners(EVENT_URL_OPEN, ret);
```

But still my appUrlOpen listener never gets called.

**Which brings me to the second problem:**

At this point if I debug the notifyListeners() call, the eventListeners map is always empty.

I'm assuming it's because this code is getting hit before my app is actually loaded so the App.addListener call hasn't happened yet.

I'm working on an Ionic/Angular project so I true putting the call in an APP_INITIALIZER but it still wasn't early enough.

I'm thinking the Bridge or the Plugin has to delay the handling of that intent until the web view has actually been loaded.

**Comment by solojuve1897** [comment]
Any status on this? A way forward?

**Comment by romucci** [comment]
Any good way to implement this with Auth0 too? :D

**Comment by solojuve1897** [comment]
@mlynch @jcesarmobile 

Sorry for the ping, guys. Would appreciate any info on this. My purpose for using "appUrlOpen" is to be able to route the user forward to the correct page in the app (with potential parameters) after it's launch, using deep linking. Maybe there is another way of doing this without appUrlOpen? Because this event isnt, as others have reported, working as expected.

**Comment by philipp-schaerer-lambdait** [comment]
I'm currently working on a project which uses capacitor to wrap an Angular application into native apps and it worked well so far, but I've got a similar timing issue. We are currently patching the Capacitor implementation via [`patch-package`](https://github.com/ds300/patch-package) so that the Deep-Link notification gets buffered till a subscriber has registered, following patch is applied:
```diff
--- a/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/App.java
+++ b/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/App.java
@@ -124,7 +129,7 @@ public class App extends Plugin {
 
     JSObject ret = new JSObject();
     ret.put("url", url.toString());
-    notifyListeners(EVENT_URL_OPEN, ret);
+    notifyListeners(EVENT_URL_OPEN, ret, true);
   }
 
 }
```

The third parameter for `notifyListeners` is named `retainUntilConsumed`, changing it to true will prevent notifications when the underlying frameworks are not ready yet. Could this change probably be useful for other scenarios as well?

**Comment by WoMayr** [comment]
I got it to work by adding the property `android:launchMode="singleTop"` to the activity in the Android Manifest

```xml
        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale"
            android:launchMode="singleTop"
            android:name="<path to MainActivity>"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/custom_url_scheme" />
            </intent-filter>

        </activity>
```
