### ISSUE TITLE
Some more Keyboard-issues

### ISSUE THREAD

**Issue by solojuve1897** [ionic-team/capacitor#676]
Hi.

1. Keyboard not respecting input type "number".

2. Keyboard not giving me word completion (suggested words).

Both issues on Android. Haven't tried it on iOS.

**Comment by jcesarmobile** [comment]
In my tests, input type number shows an alphanumeric keyboard, but only accepts numbers (like on iOS)

This is caused by this https://github.com/ionic-team/capacitor/pull/372 as it changed the default input connection to `BaseInputConnection` which is a more basic keyboard.

I think we should add a preference to allow choosing the default input connection or the `BaseInputConnection ` that allows capturing the key presses, but that has limitations like the mentioned here, and no emoji. And the default being the default as most people will probably not need to capture the key press

**Comment by solojuve1897** [comment]
@jcesarmobile 
"This is caused by this #372 as it changed the default input connection to BaseInputConnection which is a more basic keyboard"

This explains alot with regards to the limited experience one gets by the keyboard.

"I think we should add a preference to allow choosing the default input connection or the BaseInputConnection that allows capturing the key presses, but that has limitations like the mentioned here, and no emoji. And the default being the default as most people will probably not need to capture the key press"

I think it's a good idea to have the option to change between different keyboard-setups. At the moment the keyboard is too simplistic in it's features for my specific needs.
