### ISSUE TITLE
bug: Filesystem.readdir can only list directory name

### ISSUE THREAD

**Issue by newproplus** [ionic-team/capacitor#6843]
### Capacitor Version

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0

[success] Android looking great! 👌
```

### Platform(s)

Android (Android12)

### Current Behavior

`Filesystem.readdir` can only list directory names.

### Expected Behavior

`Filesystem.readdir` can list all the directories and files under the specific directory.

### Code Reproduction

```js
 const contents = await Filesystem.readdir({
   path: '/storage/emulated/0/aaa_data/ielts/15',
    // directory: Directory.ExternalStorage,
  });
```

My directory tree like:
```
/storage/emulated/0/aaa_data/ielts:

├─1
│      Test1-s1.mp3
│      Test1-s2.mp3
│
...
├─15
│      Test1-s1.mp3
│      Test1-s2.mp3
│
└─16
       Test1-s1.mp3
       Test1-s2.mp3
```

There are some  mp3 files under **/storage/emulated/0/aaa_data/ielts/15**, but the result of **Filesystem.readdir** is `[]`.
After I change the **path** to **/storage/emulated/0/aaa_data/ielts**, it will show the right directory names list of this directory, including 1 to16.

### Other Technical Details

`npm --version` output: 9.3.1

`node --version` output: v18.14.0

`pod --version` output (iOS issues only):

**Comment by newproplus** [comment]
[Here is the sample repo](https://github.com/newproplus/reproduction_ionic_fs)

**Comment by newproplus** [comment]
I reckon it may caused by permission, and [this link has the similar issue](https://stackoverflow.com/questions/69472550/android-11-30-api-file-listfiles-doesnt-return-all-files)

**Comment by jcesarmobile** [comment]
I can only list the files I've created, but I think that's expected since Android 11 as we have documented on https://capacitorjs.com/docs/apis/filesystem#android

The only way of creating a file browser that works on all android versions would be to request `MANAGE_EXTERNAL_STORAGE` permission, but that's a dangerous permission that would cause app rejections if your app is not a file browser, so it's not something we will be adding to the filesystem plugin, users who need that permission can request it themselves with their own plugin.
