### ISSUE TITLE
bug: errorPath not displaying error page when trying to access an external website

### ISSUE THREAD

**Issue by aljones15** [ionic-team/capacitor#7005]
### Capacitor Version

```
npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/cli: 4.8.1
  @capacitor/core: 4.8.1
  @capacitor/ios: 4.8.1
  @capacitor/android: 4.8.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)

Android API Level 33 on a google pixel 6

### Current Behavior

When I am on an external server and quit the app and then switch to airplane mode
when I re-open the app I get the Android error that it can not load whatever site I was just on.
I have `errorPath` set to a file that is inside of my `www` dir and have seen the error page shown.
The HTML page specified in `errorPath` shows up if I started the app in offline mode, but once
a service worker registration has occurred subsequent re-openings of the app in offline mode result in failure.

### Expected Behavior

When I resume and I'm offline I expect to see my custom error page.

### Code Reproduction

Repo with reproducible Android project here: https://github.com/aljones15/capacitor4-serviceWorker-errorPath/tree/main

Steps are in the README, but:

1. Have an existing Android emulator open in airplane mode.
2. Use `npx cap run android` and choose the existing emulator.
3. You should see a bare bones error page that matches `www/applicationError.html`
![Bare Bones Error Page](https://github.com/aljones15/capacitor4-serviceWorker-errorPath/blob/main/images/Step1.png)
4. Turn off airplane mode
5. Resume the app and click on reload
6. Should see the angular home page
![Angular HomePage](https://github.com/aljones15/capacitor4-serviceWorker-errorPath/blob/main/images/Step2.png)
7. Close the app entirely (no resume)
8. Turn airplane mode back on
9. Reopen the app should see crash screen.
![Crash Screen](https://github.com/aljones15/capacitor4-serviceWorker-errorPath/blob/main/images/Step3.png)

### Other Technical Details

`npm --version` output:
9.6.7
`node --version` output:
v18.17.0
`pod --version` output (iOS issues only):
1.11.3

**Comment by aljones15** [comment]
closing as this appears to be the result of registering a service worker in android. Hope that future versions of Capacitor are more service worker friendly.

**Comment by aljones15** [comment]
Reopening as I can reproduce now https://github.com/aljones15/capacitor4-serviceWorker-errorPath/tree/main

**Comment by jcesarmobile** [comment]
This happens because that web uses service workers and you are killing the app before they have finished caching all the assets, so it ends in an unstable state.
When using service workers, they prevent the WebView from calling the `onReceivedError` method that Capacitor relies on to show the error page, but also, since the service worker didn't cache all the assets loads that error page (provided by the WebView itself).

There are no event for service workers failing to load that we could use to show the error page, that's something that people should request to google for the [ServiceWorkerController](https://developer.android.com/reference/android/webkit/ServiceWorkerController), it should include a `onReceivedError` on the [ServiceWorkerClient](https://developer.android.com/reference/android/webkit/ServiceWorkerClient) as it has for the `WebViewClient`
