### ISSUE TITLE
cordova-plugin-ibeacon - plugin not installed

### ISSUE THREAD

**Issue by netomarchiori** [ionic-team/capacitor#708]
started a fresh ionic beta 4 project for iOS, added cordova-plugin-ibeacon as per the docs using `npm install cordova-plugin-ibeacon`, `npx cap sync`, `ionic cordova plugin add cordova-plugin-ibeacon` and also the latest beta for the ionic native wrapper using `npm install npm install @ionic-native/ibeacon@5.0.0-beta.14`.

Im able to see the plugin files in XCode but whenever tried to use on the app, it does not work and the following message is presented on the log:

> `⚡️ [warn] - Native: tried calling IBeacon.requestAlwaysAuthorization, but the IBeacon plugin is not installed.`
`⚡️  [warn] - Install the IBeacon plugin: 'ionic cordova plugin add cordova-plugin-ibeacon'`
`⚡️  [warn] - Native: tried accessing the IBeacon plugin but it's not installed.`
`⚡️  [warn] - Install the IBeacon plugin: 'ionic cordova plugin add cordova-plugin-ibeacon'`

any help is appreciated

**Comment by jcesarmobile** [comment]
I faced a few issues while testing ibeacon plugin. But all of them are merged now.
https://github.com/ionic-team/capacitor/pull/710
https://github.com/ionic-team/capacitor/pull/711
https://github.com/ionic-team/capacitor/pull/712

Was able to see the requestAlwaysAuthorization prompt on an ionic 4 angular, but wasn't able to make the plugin properly work, but my angular skills aren't very good, not really sure if the problem was related to my skills or to `@ionic-native/ibeacon@5.0.0-beta.14`.

I was able to make the plugin work on a regular Cordova app though. (And by work I only mean it request the permission and I can see didstartmonitoring and some other functions called, I don't really have a beacon to properly test.

So I'm closing the issue for now, if you try master CLI version (or when we release next beta) and still face issues, please, report them again, if possible, provide a sample app.

**Comment by netomarchiori** [comment]
@jcesarmobile you were able to see requestAlwaysAuthorization on a device or on the simulator?

any date for next beta release ? thanks gracias

**Comment by jcesarmobile** [comment]
I only test on real devices

There is no date yet, but probably soon

**Comment by netomarchiori** [comment]
@jcesarmobile 1.0.0-beta.4 did the trick! plugin is loading now, thanks!

**Comment by PacoMP** [comment]
Have you managed to implement iBeacons with Ionic 4? I'm trying to use Ibeacons but I can't' understand really how to since there's no real documentation for ionic 4, everything that I find is from 2015 or so
