### ISSUE TITLE
Run 'npx cap run ios' will show 'the backing file has been modified outside of Xcode' in Xcode after upgrade from V4 to V5.

### ISSUE THREAD

**Issue by CyrusNG** [ionic-team/capacitor#7188]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Platform(s)
iOS

### Code Reproduction
upgrade V4 to V5, then:
```
npx cap run ios
```

### Current Behavior
Pods.xcodeproj file will always be changed, so xCode14.1 shows 'the backing file has been modified outside of Xcode'.
<img width="262" alt="截屏2024-01-14 11 42 29" src="https://github.com/ionic-team/capacitor/assets/16208525/ee675962-da0e-4d30-9aef-90e193ff6fd1">

### Expected Behavior
**May I know whether there is a way to disable 'the backing file has been modified outside of Xcode' shown in xCode?**

**Comment by jcesarmobile** [comment]
`npx cap run ios` also does a sync (which is copy + update), sync does a `pod install`, which is what modifies the Xcode project files.

If you are going to use `npx cap run ios`, it's better if you close Xcode. But if you want to keep it open you can run with `--no-sync` param so it doesn't run `sync` command (`npx cap run ios --no-sync`), but if you install new plugins they won't be available since `sync` command is what copies the native files

**Comment by CyrusNG** [comment]
> `npx cap run ios` also does a sync (which is copy + update), sync does a `pod install`, which is what modifies the Xcode project files.
> 
> If you are going to use `npx cap run ios`, it's better if you close Xcode. But if you want to keep it open you can run with `--no-sync` param so it doesn't run `sync` command (`npx cap run ios --no-sync`), but if you install new plugins they won't be available since `sync` command is what copies the native files

But I am NOT sure why capacitor V4 has no this warning in same xCode with the same command `npx cap run ios`. I have no changed any other dependency versions but CapacitorV5. So strange.

**Comment by jcesarmobile** [comment]
Maybe you have not noticed before, but I think that has always happened when running `pod install` in any CocoaPods project if the Xcode project was open, and Capacitor projects have always been CocoaPods projects and have always run `pod install` in `npx cap update` (and sync and run because they both run update).

Here there is a 2018 question on StackOverflow mentioning it already
https://stackoverflow.com/questions/51600853/xcode-error-failed-to-save-xcodeproj
