### ISSUE TITLE
[Bug]: statusTap emitted while browser is open

### ISSUE THREAD

**Issue by aeharding** [ionic-team/capacitor#7236]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/ios: 5.6.0

[success] iOS looking great! 👌
```

### Other API Details

```Shell
npm --version
10.1.0

node --version
v20.8.1

pod --version
1.12.1
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

statusTap emitted when tapping on status bar from in-app browser (`@capacitor/browser`)

in Ionic Framework, statusTap is used to scroll the view to the top. This means that if you have an open web browser and tap the status bar while in a web page to scroll to the top of the webpage, it will scroll the underlying capacitor app to the top of the page as well.

### Expected Behavior

statusTap not emitted with open web browser

### Project Reproduction

https://github.com/aeharding/status-tap-browser

### Additional Information

https://github.com/aeharding/voyager/issues/1082

https://github.com/ionic-team/capacitor/assets/2166114/a40af3be-f43d-49c0-8389-9e16f27e03be

**Comment by jcesarmobile** [comment]
statusTap is fired when the status bar is touched, by design, so it's not a bug, it's how it's supposed to work.

If you were listening for the statusTap event yourself I would recommend stop listening or not scroll when you present a native view, but since it's automatically done by Ionic framework, I would look if it has some way to disable the scroll to top on statusTap in some cases.
