### ISSUE TITLE
[Bug]: PWAs no longer working in iOS 17.4 Beta

### ISSUE THREAD

**Issue by Wandang** [ionic-team/capacitor#7257]
### Capacitor Version

Latest

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

PWA with service workers works fine

### Expected Behavior

Continued working PWA

### Project Reproduction

https://open-web-advocacy.org/blog/did-apple-just-break-web-apps-in-ios17.4-beta-eu/

### Additional Information

According to several articles Apple is suspending service worker support in their current iOS beta version.
The reason being that the EU is requiring them to offer other browser engines as well and they are unable to provide service worker support for those other browsers.
And apparently they are afraid of paying a fine since Safari/Webkit with service worker support would have a competitive advantage on their platform.

https://open-web-advocacy.org/blog/did-apple-just-break-web-apps-in-ios17.4-beta-eu/

Currently it is unclear if they will have a fix in store until next month or if PWA are essentially breaking for all iOS users.

Is there anything capacitor can do to mitigate an outage? We will probably try to remove PWA support from our app and hold it ready to release

**Comment by jcesarmobile** [comment]
This is not a Capacitor bug and not related to Capacitor at all.

**Comment by SkaveRat** [comment]
I can understand it's not directly related to Capacitor, but I'd love to get a little more information.

With Capacitor basically providing a native wrapper around PWAs, it would be great to know if *that* specific combination will continue to work, if "normal" PWAs will stop working with the new iOS release.

because all news are talking about either PWAs or native apps, while capacitor is creating a hybrid of the two
