### ISSUE TITLE
[Feature]: Panoramic images

### ISSUE THREAD

**Issue by AsandahDevs** [ionic-team/capacitor#7399]
### Description

Camera option for taking panoramic images

### Platforms

- [X] iOS
- [X] Android
- [ ] Web

### Request or proposed solution

The current camera plugin only allows users to take pictures or upload images from the gallery . I need an additional option from the existing camera plugin to allow users to take panoramic images especially since most modern device cameras support this feature natively.

**Comment by jcesarmobile** [comment]
Plugins repository is https://github.com/ionic-team/capacitor-plugins/issues, you should report issues there.

But neither the iOS component used for taking pictures, not the Android Intent to the Camera app allow this feature at the moment, so even if you report the issue there, it won't be added because it's not possible with the current implementation of the native components, only way would be to create a plugin that doesn't use provided components or Intents but access to the Camera directly.
