### ISSUE TITLE
[Bug]: Can't Inspect WebView on iOS when setup with SPM

### ISSUE THREAD

**Issue by abegehr** [ionic-team/capacitor#7406]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌

### Other API Details

```Shell
npm: 10.5.1
node: 20.9.0
pod: 1.14.3
```

### Platforms Affected

- [X] iOS
- [ ] Android
- [ ] Web

### Current Behavior

"No inspectable applications." on Safari for iOS projects setup with SPM (`npx cap add ios --packagemanager SPM`).

### Expected Behavior

I'd expect to inspect the web view through Safari.

### Project Reproduction

https://github.com/abegehr/capacitor-sample

### Additional Information

When I delete the `ios` folder and re-init without SPM (`npx cap add iOS`), the web view is inspectable in safari as expected. Therefore I think it is a problem with the SPM setup.

**Comment by jcesarmobile** [comment]
Sadly on iOS the xcframeworks are always in Release mode, and for SPM we have to create .xcframeworks because Capacitor is mixed Objective-C and Swift source, which prevents from building a regular SPM.
Since xcframeworks are in Release mode, by default WebView inspection doesn't work because the default value is to check if it's in `DEBUG` mode, which is always false for xcframeworks.

So, if you want to inspect the WebView you'll have to set `ios.webContentsDebuggingEnabled` to true in your capacitor config file, that makes the WebView inspectable even in production builds, but you have to remember to remove it before you publish the actual production build.

**Comment by abegehr** [comment]
Thank you for explaining, @jcesarmobile! I opened a PR on the docs repo to add a note on this: https://github.com/ionic-team/capacitor-docs/pull/299
