### ISSUE TITLE
[Bug]: All plugins are "not implemented on android" after upgrading to Capacitor 6

### ISSUE THREAD

**Issue by Linksku** [ionic-team/capacitor#7440]
### Capacitor Version

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[error] Xcode is not installed
[success] Android looking great! 👌
```

### Other API Details

```Shell
$ npm --version
10.6.0
$ node --version
v20.12.0
```
I think it affects every plugin, but confirmed the error occurs with:

```
"@capacitor/clipboard": "^6.0.0",
"@capacitor/geolocation": "^6.0.0",
"@capacitor/share": "^6.0.0",
"@capacitor/splash-screen": "^6.0.0",
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

Using any plugin triggers "[plugin name] plugin is not implemented on android"

### Expected Behavior

No errors like in Capacitor 5

### Project Reproduction

https://github.com/ionic-team/create-capacitor-app

### Additional Information

I tried:
- `npx cap migrate`
- `npx cap sync android`
- Deleted android folder, then `npx cap add android`
- Deleted node_modules, then `yarn`
- Restarted Android Studio, clean project, reload from disk, rebuild, etc
- Created a new clean project using `@capacitor/create-app`

If I use my old Android build with Capacitor 5 plugins, but load a webview containing the JS for Capacitor 6 plugins, every plugin still works. Plugins all work on iOS.

**Comment by Ionitron** [comment]
It looks like this issue didn't get the information it needed, so I'll close it for now. If I made a mistake, sorry! I am just a bot.

Have a great day!
Ionitron 💙

**Comment by Venryx** [comment]
I hit this same issue, where several plugins (including the capacitor-provided "App" plugin) were "not implemented on android". (despite them clearly existing, and my seeing their initializations in the android logs)

Base situation: My app's "public" folder merely held "stub" `index.html` and `index.js` files, which would immediately redirect to my web-hosted domain at page load time.

Fix: Rather than use those "stub" files with redirection, instead I just provided my web-hosted domain as the `server.url` field on `capacitor.config.json`.

Diagnosis: I think what happened is that somewhere in the updates from Capacitor 4 to 6, the plugin-injection system was optimized to complete earlier in the page loading process. So the redirect that my "stub" `index.js` file wants to do, used to complete _before_ the page redirect, whereas on Capacitor 6 it completes _after_ the plugins were already injected, causing the newly loaded page to then lose access to those injected plugins. (maybe a capacitor dev can confirm/deny this?)

Anyway, my redirect approach is a bit non-standard, so maybe it's not the reason for the issue you're hitting. But I figured I would mention it, since there aren't many google hits for this error message.
