### ISSUE TITLE
[Bug]: Sending TypedArray as fetch body gets JSON.stringified

### ISSUE THREAD

**Issue by marcelklehr** [ionic-team/capacitor#7473]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 5.7.5
  @capacitor/core: 5.7.5
  @capacitor/android: 5.7.5
  @capacitor/ios: 5.5.1

[success] Android looking great! 👌
[error] Xcode is not installed

### Other API Details

```Shell
npm --version
10.7.0

node --version
v20.9.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

sending a POST via fetch with a UInt8Array as body results in the TypedArray getting stringified as JSON.

callback: 40428488, pluginId: CapacitorHttp, methodName: request, methodData: {"url":"https:\/\/github.com\/marcelklehr\/test.git\/git-upload-pack","method":"POST","data":{"0":48,"1":48,"2":56,"3":....

### Expected Behavior

The binary data sould be sent unchanged.

### Project Reproduction

https://github.com/floccusaddon/floccus

**Comment by jcesarmobile** [comment]
please, provide a sample app that reproduces the issue, not a full app with no indications about how to run or reproduce

**Comment by marcelklehr** [comment]
Here you go: https://github.com/marcelklehr/capactitor-repro-fetch-uint8array

**Comment by marcelklehr** [comment]
Is there any ETA on this issue? :pray:

**Comment by faan11** [comment]
This is how it works now from my understanding:
- for android or web: the convertBody function detects the type https://github.com/ionic-team/capacitor/blob/0ad0c3f23e1c62ade5081878e345e74f963b9ea5/core/native-bridge.ts#L767 
- the type detection is based on the content type. The integer value is treat as  text since no content-type was specified (see here: https://github.com/ionic-team/capacitor/blob/0ad0c3f23e1c62ade5081878e345e74f963b9ea5/core/native-bridge.ts#L91) .
- the function request is called 
- this is the android implementation of request: https://github.com/ionic-team/capacitor/blob/0ad0c3f23e1c62ade5081878e345e74f963b9ea5/android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorHttp.java#L91
- the capacitorhttp class calls HttpRequestHandler request method https://github.com/ionic-team/capacitor/blob/0ad0c3f23e1c62ade5081878e345e74f963b9ea5/android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java#L385 which gets the datatype and data
- calls setRequestBody https://github.com/ionic-team/capacitor/blob/0ad0c3f23e1c62ade5081878e345e74f963b9ea5/android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java#L423
- The last case should convert the raw data into string because it does not know how to handle it: https://github.com/ionic-team/capacitor/blob/0ad0c3f23e1c62ade5081878e345e74f963b9ea5/android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java#L229 
- Even if the type is recognized as json: the text is converted to string which treats integer as a string. https://github.com/ionic-team/capacitor/blob/0ad0c3f23e1c62ade5081878e345e74f963b9ea5/android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java#L201

From this analysis, all platforms should be affected by this bug since the convertBody function is shared by ios, android and web. 
In my opinion, the solution depends on the body type:
- if the body is a integer, the convertbody function should detect that the value is an integer
- if the body is a json, we should use json.Stringify instead of the common toString method.

Please correct me if I said something wrong. I hope this might help to solve this issue.

**Comment by jongbonga** [comment]
I'm facing with uploading images on Android on capacitor 6, the same code was working well on Capacitor 5. iOS is working okay, but I'm getting `java.lang.ArrayIndexOutOfBoundsException: length=1; index=1` on Android
