### ISSUE TITLE
[Bug]: A change in active Bluetooth devices crashes app

### ISSUE THREAD

**Issue by Martijn0405** [ionic-team/capacitor#7543]
### Capacitor Version

6.0.0

### Other API Details

```Shell
npm --version output: 7.6.1
node --version output: v20.11.0
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

I have a React, NextJS, and Capacitor app built and running on my Android device. When I pause the app by going to the home screen and then open the app again, nothing happens and the app gets resumed without restarting or crashing (as expected). But when I go to the home screen, connect a Bluetooth device, and then open the app, it gets destroyed, crashes, and restarts the app.

The Bluetooth device I am connecting is an iRig BlueTurn, which acts as a BlueTooth Low-Energy (BLE) keyboard.

### Expected Behavior

The expected behavior would mean the app no longer crashes after a Bluetooth device gets connected or disconnected.

### Project Reproduction

https://github.com/Martijn0405/ble-crash-frontend

### Additional Information

Install the app by running `npm i`, then `npm run app`. Connecting a BLE device crashes the app, and immediately restarts it, which updates the time on the home page.
![image](https://github.com/ionic-team/capacitor/assets/43009057/d28e5fa8-9ec6-442d-ab94-d976272d322f)

**Comment by jcesarmobile** [comment]
Android restarts activities on configuration changes.
Capacitor handles some cases, but looks like `navigation` is needed on some Android devices for not restarting the activity on bluetooth connection/disconnection.

I've updated your sample app with a fix, since the Capacitor fix will be on the android-template and won't have any effect on existing apps, only on newly created apps

https://github.com/Martijn0405/ble-crash-frontend/pull/1
