### ISSUE TITLE
[Feature]: localhost sharing between mac and iOS simulator

### ISSUE THREAD

**Issue by Aarbel** [ionic-team/capacitor#7562]
### Description

Being able to launch a service on localhost and connect to it thru simulator

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

### Request or proposed solution

Hi Capacitor team,

It would be amazing to be able to share the localhost between the simulator and the local OSX machine.

Example:
- i run a react app on localhost:3000 on my mac
- i want to access this localhost:3000 on my simulator, filling localhost:3000 in mobile's Safari App.

Thanks a lot for your help ! 

### Alternatives

Using ngrok exposing an url thru localhost (but very slow and not easy to maintain)

**Comment by Aarbel** [comment]
cc @mtarzi

**Comment by jcesarmobile** [comment]
This is out of the scope of Capacitor.

Most web frameworks already provide local web servers that do this.
In example if you create a Capacitor app using `npm init @capacitor/app@latest`, the generated app has `vite` configured and running `npm start` will start vite serving your app in `http://localhost:3000/`, which is accessible from a web browser on both your computer and the iOS simulator.

Not sure why do you say you need ngrok, ngrok should only be needed if you want to use a `https` url instead of a `http` one, or if you want to share the url with real devices or computers outside your local network.

**Comment by Aarbel** [comment]
@jcesarmobile yes we need https, as we are using Auth0 for the app login: https://auth0.com/

Is there any way to expose https between local machine and simulator ? 

Thanks a lot for your help
