### ISSUE TITLE
iOS WebView doesn't use https

### ISSUE THREAD

**Issue by ArmorDarks** [ionic-team/capacitor#758]
## Version

1.0.0-beta.6

## Platfrom

iOS built application

## Issue

iOS localhost is loaded with `http` protocol.

It results in issue with some services, which stricly requring secure connection.

For instance, when `navigation.geolocation.watchPosition()` used, it results in following error:

![image](https://user-images.githubusercontent.com/4460311/44405824-dabd0980-a562-11e8-9053-55c71db66664.png)

**Comment by ajayak** [comment]
Any update on this issue??

@ArmorDarks, on a side note, how to access these logs in ios device? 😄

**Comment by ArmorDarks** [comment]
@ajayak Briefly mentioned in my other issue.

Basically, install Safari Tech Preview, launch it, enable Develop menu, then launch Xcode and run your app in the simulator.

After that you should see in Safari Develop menu entry `iPhone Simulator`, and there should be your launched simulator instance. Just run it and you'll see devtools for launched WebView.

**Comment by ghenry22** [comment]
I doubt this will be changed, GCD we Server which is used on iOS specifically does not support HTTPS I believe.

**Comment by ArmorDarks** [comment]
Wow, that sounds really bad...

**Comment by mlynch** [comment]
Regardless, use the native Geolocation Plugin we provide as it will work in this case. Will look into the HTTPS issue here.

**Comment by ghenry22** [comment]
Https on a local host only web server is really a waste of time, you don’t use encryption when reading by file protocol for your local files either.  Also you can’t get a valid certificate for localhost anyway.

But it would be good to work out what is up with the geolocation plugin regardless.

**Comment by jcesarmobile** [comment]
The native geolocation plugin works fine, it's the webview implementation what doesn't work (`navigation.geolocation`) because it requires https to work.

We use `GCDWebServer` as the web server and it doesn't support https, nor it's going to support it in the future, so to "fix" this we will have to use a different web server with https support, or use a custom scheme instead of `http:` or `https:`, but that's only supported on iOS 11+, and I'm not really sure `navigation.geolocation` will work with a custom scheme.

Closing it for now as the rest of issues tagged with feature request tag. 
If you are interested in https feature add the +1 reaction (thumbs up)on the issue as we use it to gauge interest on feature request issues.

**Comment by ArmorDarks** [comment]
Sadly to see how on Apple devices everything screwed up. Like, they really hate developers.

I have a feeling that `http`-only will eventually result in other issues with mixed content anyway.

**Comment by jcesarmobile** [comment]
changing from feature request to won't do, we have removed the web server and we are using `capacitor://` as scheme and won't change it to https

**Comment by ArmorDarks** [comment]
I assume this is a good thing.

Not that proper place to ask, but still — how iOS treats such a scheme? Like it is a `https` or not? Will it complain about mixed content?

**Comment by glebmachine** [comment]
any news? this is still a problem(
