### ISSUE TITLE
[Bug]: Smooth switching between native keyboard and emoji picker

### ISSUE THREAD

**Issue by SvenBudak** [ionic-team/capacitor#7612]
### Capacitor Version

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0
  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0

### Other API Details

```Shell
npm: 10.7.0
node: v18.20.4
```

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

My team and I have been trying to smoothly switch from the native ios / android keyboard to an ionic custom div. We have also asked in the ionic community where some have tried to help us. But it was never as clean as it looks in a native app like whatsapp when you switch from keyboard mode to emoji picker.

The best we was able to do in ionic:

https://github.com/user-attachments/assets/c3a20adf-075a-47e5-9d3d-61e964ab43d4

### Expected Behavior

I have not found a way to implement it without jumpings.

What i Expect:

https://github.com/user-attachments/assets/cffecc75-4139-4a07-b207-ff4d2a831bdf

### Project Reproduction

https://github.com/SvenBudak/Keyboard-Test-App

### Additional Information

I don't know how often people need something like this, but there should be a way to toggle an emojipicker without flickering. If it is currently possible and someone knows the solution, I would be very happy about a solution. otherwise it would be nice if a build in solution could be implemented.

**Comment by dev-charles15531** [comment]
I don't understand "smooth switching"

You already have a layout of where your emojis would be displayed, and to me, that's like a 50% work done.

Recently made plans to work on a project that provides  emoji keyboards  along other cool features. 

Well, let me know how you managed to solve yours

**Comment by jcesarmobile** [comment]
Most native keyboards already have a emoji button that changes the native qwerty keyboard to a native emoji picker seamlessly, see the emoji button in the keyboard shown in your videos. If you click it it shows emojis replacing the characters. 

But if instead of using the native emoji picker you want to hide the keyboard and show a custom div with emojis, you can try listening for the `keyboardWillHide` to show the emoji picker right before the keyboard is hidden, or if that still makes it hard to make it smooth, you can disable the whole keyboard resizing using the `None` resize mode and move/hide/show the divs when the keyboard shows/hides

https://capacitorjs.com/docs/apis/keyboard#keyboardresize
