### ISSUE TITLE
Cordova snackbar plugin, not working.

### ISSUE THREAD

**Issue by moda20** [ionic-team/capacitor#770]
hey I am using the Cordova snacker plugin : https://www.npmjs.com/package/cordova-plugin-snackbar
and It doesn't see to work with capacitor. I did follow the official way of making Cordova plugins work with capacitor.

I am using ionic 4 beta 4.0.6
and 

```
💊   Capacitor Doctor  💊 

Dependencies:

  @capacitor/cli: 1.0.0-beta.7

  @capacitor/core: 1.0.0-beta.7

  @capacitor/android: 1.0.0-beta.7

  @capacitor/ios: 1.0.0-beta.7

  Capacitor Android: not installed

[success] Android looking great! 👌

```

When ic all the plugin to create a snackbar, nothing happens. I do that form the app code and from the remote devices console on chrome.
Is the plugin not compatible with capacitor or I am having a bug somewhere ?

**calling code**
```
  createSnackBar(text,duration?,callback?){
        cordova.plugins.snackbar.create(text ||'', duration || 'SHORT','', callback?callback():()=>{
          console.log("SnackbarClosed")
        });
  }
```

**Comment by jcesarmobile** [comment]
The problem is the plugin expect the layout to be `FrameLayout`, but Capacitor uses `CoordinatorLayout`. I don't think we will change the `CoordinatorLayout` to `FrameLayout` at this point.

I see two options here:
1. Fork the plugin and change the two `FrameLayout` entries to `CoordinatorLayout` and use your fork.
2. In capacitor-android module => `res/layout/bridge_layout_main.xml` file, change the `android.support.design.widget.CoordinatorLayout` to `FrameLayout`. But you'll have to remember to change it every time you update `@capacitor/android` and might cause undesired effects. 

I tried both and both worked, I would recommend the 1.
