### ISSUE TITLE
Monorepo Support

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor#792]
```
> capacitor add android
✔ Installing android dependencies in 1.64s
✔ Adding native android project in: /Users/dan/apps/angular/monorepo/packages/capacitor-app/android in 52.64ms
✔ Syncing Gradle in 1.11s
✔ add in 2.80s
✔ Copying web assets from www to android/app/src/main/assets/public in 274.30ms
[error] Unable to find node_modules/@capacitor/core/native-bridge.js. Are you sure @capacitor/core is installed? This file is required for Capacitor to function
```

`@capacitor/core` should be found via node resolution algorithm

**Comment by dwieeb** [comment]
TODO:

```
[error] Capacitor needs to run at the root of an npm package.
    Make sure you have a "package.json" in the directory where you run capacitor.
    More info: https://docs.npmjs.com/cli/init
```

Why?

**Comment by GuilhermeBCC** [comment]
I do not think there is doc yet. Please, could you give me an example of how to create a new App with monorepo

**Comment by Sina7312** [comment]
It's still not clear how to do Capacitor with monorepos!

**Comment by GuilhermeBCC** [comment]
Capacitor does not work with monorepos because there is no need for it. Basically what you need to do is build a production version of your website and place it inside the Android / IOS project created by the capacitor, that's it.

Today I'm creating my apk with a single command without opening Android Studio.

**Comment by jwrunner** [comment]
I disagree. There is a need for Capacitor to work with monorepos. For example, a company has a long-standing website and are now using Ionic to build an app. The app and the website need to share services, interfaces, etc... and can't easily do this outside the monorepo option without building and publishing a library on every change of the shared resources.

**Comment by y0nd0** [comment]
I created a monorepo by following [this guide](https://github.com/ionic-team/ionic-cli/wiki/Angular-Monorepo). It looks good. Only one node_modules folder. Really great. But now I have to bring each app to the mobile device. It's a monorepo with a bunch of Ionic apps. Each app uses the same dependencies, Cordova plugins and configs. I have no exp with Capacitor yet. But also no idea how to integrate Cordova or Capacitor in that Ionic monorepo. Is Ionic not oriented for mobile apps? So, monorepos should be supported.

**Comment by alimcharaniya** [comment]
> I disagree. There is a need for Capacitor to work with monorepos. For example, a company has a long-standing website and are now using Ionic to build an app. The app and the website need to share services, interfaces, etc... and can't easily do this outside the monorepo option without building and publishing a library on every change of the shared resources.

Agree here as well. Does support for monorepo exist? I'd like to use AppFlow but it doesn't work when running inside of a monorepo.

**Comment by corysmc** [comment]
App flow does work in a monorepo @alimcharaniya  - just got that working today following this outline from the ionic team:
https://ionic.io/docs/appflow/cookbook/appflow-config
A little guess and check I got app flow working with this config file (we use nx):
```ts
// appflow.config (root of your monorepo)
{
    "apps": [
        {
            "appId": "d77609ad",
            "root": "client-apps/apps/tn-pos",
            "dependencyInstallCommand": "cd ../../ && npm install",
            "webBuildCommand": "cd ../../ && npx nx run tn-pos:build:production"
        }
    ]
}
```

Then inside the tn-pos (one of our apps) folder:
```ts
// capacitor.config.json
{
  "appId": "<app_id_here>",
  "appName": "tn-pos",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "../../dist/apps/tn-pos",
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    }
  },
  "cordova": {}
}
```

 But I have been struggling with local development in the monorepo. Any tips would be appreciated! I can manually get it to build, by opening the app folder, and running capacitor commands there, but that adds `node_modules` in the app folder instead of at the root where they belong in the monorepo.
