### ISSUE TITLE
[iOS] Enable cross-site tracking 😀 

### ISSUE THREAD

**Issue by sneko** [ionic-team/capacitor#922]
Hi,

As posted on Slack, I'm trying to access my protected development environment through HTTP calls but unfortunately Safari has by default "Prevent cross-site tracking" enabled 😢 .

Inside my Safari settings I'm able to disable it and it works. I succeed in reaching my protected API from my single page application (hosted remotely).

But when building the app for iOS, the settings are not spread to my Capacitor webview 😭 . I took a look inside your Swift code but didn't find where to set the parameter to accept cookies...

Here a related post that could help to understand my issue:
https://stackoverflow.com/questions/47309048/enable-cross-site-tracking-in-wkwebview?rq=1

Could you please indicate me how I could modify your webview settings in a proper way to change this?

Thank you 😀 

EDIT: another example:
https://github.com/apigee/appservices-phonegap-ios-push-example/blob/master/pushtest/Classes/AppDelegate.m#L43-L45

**Comment by rj33** [comment]
The issue here is that at some stage apple changed the default cookie privacy policy from
NSHTTPCookieAcceptPolicyAlways
to
NSHTTPCookieAcceptPolicyOnlyFromMainDocumentDomain

It is confusing, because their own documentation page on this API still states that Always is the default, but it clearly isn't on recent iOS versions (I'm not sure how long ago it was the default).

So if you're doing something like trying to login from your app to your external server it currently will not work (unless the server hostname is called localhost).

If you open up App/AppDelegate.swift and go to this line:
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    // Override point for customization after application launch.
    return true
  }

And before the return add this:
HTTPCookieStorage.shared.cookieAcceptPolicy = HTTPCookie.AcceptPolicy.always

so it now looks like this:

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    // Override point for customization after application launch.
   HTTPCookieStorage.shared.cookieAcceptPolicy = HTTPCookie.AcceptPolicy.always
    return true
  }

In the startup log you should now see this after all the plugins have been registered:
DiskCookieStorage changing policy from 2 to 0

This fixed the issue for me at least, but there may be other issues with your server's configuration of CORS that may also need attention. 

The Capacitor folks should probably put this in the core as default as there are probably a lot of people who are struggling to get their cookie based auth system working without the above snippet.

Thanks for posting your issue, and the links, as it helped set me in the right direction on what was required.

**Comment by rj33** [comment]
I should add that even after the above setting, I still have some other issues with cookies not working on first launch, but working after that which I'm still in the process of resolving. There is a discussion
here that looks relevant:
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/22
None of those solutions look very pretty so still investigating.

**Comment by rj33** [comment]
And here is another addition to AppDelegate.swift that solved the "cookies not stored until second launch of app" issue, just below the cookie accept policy change code also add:
let cookie = HTTPCookie(properties: [HTTPCookiePropertyKey.domain: ".yourdomainhere.com",
                                         HTTPCookiePropertyKey.path: "/",
                                         HTTPCookiePropertyKey.name: "dummy",
                                         HTTPCookiePropertyKey.value: "dummy value"])!
HTTPCookieStorage.shared.setCookie(cookie)

Where yourdomainhere.com is the external domain you want cookies supplied to. This seems to get the cookie store fired up before the webview is launched and everything works fine from the very first launch after this.

**Comment by sneko** [comment]
Hi @rj33 I appreciate your detailed answers!

I put the cookies part aside while waiting for a more official way. Maybe the Capacitor team could reference these steps somewhere? @mlynch? And if no "official way of doing" is given, I will give it a try with what's you gave 😃 

Thank you again 👍

**Comment by NiklasMerz** [comment]
This Webkit bug may be related:
https://bugs.webkit.org/show_bug.cgi?id=140205

**Comment by jcesarmobile** [comment]
The `HTTPCookie.AcceptPolicy.always` was added in Capacitor long ago, closing the issue.

Other Cookie issues are probably Apple bugs, but in any case, report new issues if you find them.
