### ISSUE TITLE
Need dedicated method for checking if a file exists

### ISSUE THREAD

**Issue by bdsimmons** [ionic-team/capacitor#957]
I have been using stat for this, but it's not semantically ideal and it is a common enough action that I think it should be part of the core API.

**Comment by jcesarmobile** [comment]
Issues tagged with feature request are closed but tracked for reactions to gauge interest.

Since our file API is similar to the node one, I think we should use [access](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback) instead of fileExists.
Also, it should cover web and electron too.

**Comment by ahollandusc** [comment]
Would love this - currently getUri throws exception of web if file doesnt exist but on device returns a formulated string so is messy to work with.
Using stat can emulate this but a fileExists fn would be much better - any chance ionic can reconsider and resolving merge conflicts from the provided PR to include this change?
