### ISSUE TITLE
Windows: Nothing happens on `npm run capacitor open android`

### ISSUE THREAD

**Issue by janpio** [ionic-team/capacitor#96]
```
C:\Projects\Capacitor
λ git clone https://github.com/ionic-team/capacitor-starter my-app
Cloning into 'my-app'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 12 (delta 2), reused 12 (delta 2), pack-reused 0
Unpacking objects: 100% (12/12), done.

C:\Projects\Capacitor
λ cd my-app

C:\Projects\Capacitor\my-app (master -> origin) (capacitor-starter@1.0.0)
λ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
added 155 packages in 11.61s

C:\Projects\Capacitor\my-app (master -> origin) (capacitor-starter@1.0.0)
λ npm run capacitor init

> capacitor-starter@1.0.0 capacitor C:\Projects\Capacitor\my-app
> capacitor "init"



⚡️  Initializing Capacitor project in C:\Projects\Capacitor\my-app ⚡️


? Is this a new app? Answer 'n' if adding Capacitor to an existing project y
√ Creating capacitor.config.json in 3.19ms
√ Downloading and installing seed project in 1.69s
√ Installing dependencies for seed project (npm install) in 3.26s
√ Installing Capacitor dependencies (npm install --save @capacitor/core@latest @capacitor/cli@latest) in 12.77s
√ Adding native android project in: C:\Projects\Capacitor\my-app\android in 85.23ms
√ Adding native platforms in 95.32ms


🎉   Your Capacitor project is ready to go!  🎉

Follow the Getting Started guide for next steps:
https://capacitor.ionicframework.com/docs/getting-started

C:\Projects\Capacitor\my-app (master -> origin) (capacitor-starter@1.0.0)
λ ls
android/  capacitor.config.json  node_modules/  package.json  package-lock.json  public/  README.md

C:\Projects\Capacitor\my-app (master -> origin) (capacitor-starter@1.0.0)
λ npm run capacitor copy android

> capacitor-starter@1.0.0 capacitor C:\Projects\Capacitor\my-app
> capacitor "copy" "android"

√ Copying web assets from public to android\app\src\main\assets\public in 27.10ms

C:\Projects\Capacitor\my-app (master -> origin) (capacitor-starter@1.0.0)
λ npm run capacitor open android

> capacitor-starter@1.0.0 capacitor C:\Projects\Capacitor\my-app
> capacitor "open" "android"

  [info] Opening Android project at C:\Projects\Capacitor\my-app\android

C:\Projects\Capacitor\my-app (master -> origin) (capacitor-starter@1.0.0)
λ
```

Nothing happens.

**Comment by mlynch** [comment]
Thanks, more windows Testing is called for clearly 😅

**Comment by mlynch** [comment]
```
opn("..\\capacitor\\example\\android", { app: 'C:\\Program Files\\Android\\Android Studio\\bin\\studio64.exe', wait: false });
```

**Comment by mlynch** [comment]
Should be working in `@capacitor/cli` `0.0.17`. Also made it configurable for Windows since it's not possible to just launch it by program name (as far as I can tell at least):

```
{
  "windows": {
    "androidStudioPath": "H:\\path\\to\\Android Studio\\bin\\studio64.exe"
  }
}
```

**Comment by jcesarmobile** [comment]
It requires Android Studio, what open do is to open Android Studio

**Comment by prantikv** [comment]
@jcesarmobile  can there be a work around to use Android SDK instead?

**Comment by jcesarmobile** [comment]
We are considering it because of CIs, but I don't think it's a priority at the moment.

Nevertheless, the project Capacitor creates includes gradle, so, from the android folder you can use gradle scripts like `gradlew installDebug` to create a debug build and install it on a connected device, or `gradlew assembleRelease` to build a release apk, so it's sort of supported out of the box, just not integrated in the Capacitor CLI yet.

**Comment by prantikv** [comment]
How can open build and run capacitor app on a connected Android device? Can this be done? Going through the docs I only see running in android studio.

**Comment by jcesarmobile** [comment]
how do you want to open it?

The documented way is using Android Studio, you open it with `npx cap open android` and run from there.
To run it using gradle there is nothing to open, just from the terminal, go to android folder and run `./gradlew installDebug`. It just build and install the app in the device, but doesn't launch it. 
You can launch it using adb
`adb shell am start -n your.app.package/.MainActivity`

As I said, this is not integrated in the CLI, it's just regular Android commands that are available with the Android SDK and Gradle, that's why it's not documented.

**Comment by janpio** [comment]
@prantikv You do that via Android Studio - in there you can select which device (emulator or connected real device) the app should be run on.
