### ISSUE TITLE
beta-11: IOS 10 support dropped

### ISSUE THREAD

**Issue by speyou** [ionic-team/capacitor#985]
Hi, we are surprised to see you dropping out of IOS 10 support as it still represents tens of millions of users. We surely doesn't want to lose those users right now, that's why I'm posting here: *do we have a workaround for this or are we doomed to definitely drop IOS 10 if we decide to use Capacitor?*

It's too bad because we really love the concept behind Capacitor but without IOS 10 it's a no go for us. 😢

**Comment by jcesarmobile** [comment]
Sorry, WKWebView has a lot of bugs and there are only two options to workaround most of them, using a local web server or using `WKURLSchemeHandler`.
We dropped the local web server in this release as it causes more troubles than it's worth, so our only option is to use `WKURLSchemeHandler`, but sadly it's only available on iOS 11+. 

The project started almost a year ago and we already left iOS 9 behind despite the percentage was also around 11% by that time. We [have always claimed](https://capacitor.ionicframework.com/docs/getting-started/dependencies) that we support the last 2 versions, but in this time iOS 12 came out and iOS 10 dropped to current 11% and going down every month, so we think it's better to have a more robust alternative even if that means leaving 11% of devices behind.

**Comment by mlynch** [comment]
We have been clear about our iOS support policy: the latest will support the last two iOS versions: https://capacitor.ionicframework.com/docs/getting-started/dependencies

I know that's a bit tricky right now because there aren't other older releases of Capacitor you can stay on, but usage of iOS 10 is at 10% and probably lower since this data is a month old by now: https://developer.apple.com/support/app-store/

We had a situation like this in the early Ionic days where a lot of people wanted us to keep supporting Android 2.3, even though supporting it meant a ton more work for us and a lot of hacks, and it represented 10% of the market at the time.

Not supporting it ended up being the right move because we could move on and simplify our code and focus on the core product. I believe the same thing will be the case here.

**Comment by patrickmcd** [comment]
I'll take the opposite stance of @speyou. Drop those old versions like bad habits. Onward and upward.

**Comment by speyou** [comment]
I'm sorry to insist but let's be absolutely clear: **if we want IOS 10 there is NO workaround possible with Capacitor**, that's right?
We *have to* use Cordova then.
Correct?
Thanks for your time!

**Comment by vdesaintpern** [comment]
I understand where you're coming from. This is a bold decision, it shows you have vision and know where you stand.

That being said, it means we can't use Capacitor for the new project we're working on at the moment and will sadly downgrade to Cordova at least for time being. 

It's also pretty unlikely we'll invest time in the future to migrate back to your tool if you only support 2 versions. This means you'll drop iOS 11 in a year time when iOS 13 is out...? We can't afford that.

**Comment by jcesarmobile** [comment]
Well, it says "As a rule", but in this case we are dropping iOS 10 support for good reasons, next year we might not need to drop iOS 11 support and might continue supporting it, or at least don't drop it so soon.
But also in case we do, you could still use an older version as the product will be final by then and then upgrade to a newer version when you feel ready.

Be aware that Cordova iOS support is also the same, officially only current and previous versions are supported, but it's just slower at dropping support.

Also be aware that UIWebView is deprecated and will probably go away on iOS 13 next year, Cordova should have the `WKURLSchemeHandler` in place by then, but it's not 100% assured.
